//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (InterThreadMessaging)
+ (id)originalObject;
- (id)originalObject;
- (id)onThread:(id)arg1 modes:(id)arg2 wait:(BOOL)arg3;
- (id)onThread:(id)arg1 wait:(BOOL)arg2;
- (id)onThread:(id)arg1;
- (id)onMainThreadModes:(id)arg1 wait:(BOOL)arg2;
- (id)onMainThreadWait:(BOOL)arg1;
- (id)onMainThread;
- (BOOL)isAsynchronousProxy;
@end

