//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IPCProxyObject.h"

#import "ServiceProvider.h"

@class NSString;

@interface SSHIPC_v2_ServiceProvider : IPCProxyObject <ServiceProvider>
{
}

@property(readonly, retain, nonatomic) NSString *serviceName;

@end

