//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString;

@protocol SubtaskDelegate

@optional
- (void)handleStderrLineOrEOF:(NSString *)arg1;
- (void)handleReceivedLineOrEOF:(NSString *)arg1;
- (void)handleReceivedBytes:(void *)arg1 length:(unsigned long long)arg2;
- (void)connectionClosed;
@end

