//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NotesWindowController.h"

@class FolderListTreeController, MainSplitView, MainWindow, NSIndexSet, NSSearchField, NSSegmentedControl, NSView, NoteListArrayController;

@interface MainWindowController : NotesWindowController
{
    NSView *_contentView;
    MainSplitView *_mainSplitView;
    NSSearchField *_searchField;
    FolderListTreeController *_folderListTreeController;
    NoteListArrayController *_noteListArrayController;
    NSIndexSet *_folderSelectionIndexSet;
    NSIndexSet *_noteSelectionIndexSet;
    NSSegmentedControl *_addNoteButton;
}

+ (id)keyPathsForValuesAffectingUserStyleSheetURL;
+ (id)windowIdentifier;
@property(nonatomic) __weak NSSegmentedControl *addNoteButton; // @synthesize addNoteButton=_addNoteButton;
@property(retain, nonatomic) NSIndexSet *noteSelectionIndexSet; // @synthesize noteSelectionIndexSet=_noteSelectionIndexSet;
@property(retain, nonatomic) NSIndexSet *folderSelectionIndexSet; // @synthesize folderSelectionIndexSet=_folderSelectionIndexSet;
@property(nonatomic) __weak NoteListArrayController *noteListArrayController; // @synthesize noteListArrayController=_noteListArrayController;
@property(nonatomic) __weak FolderListTreeController *folderListTreeController; // @synthesize folderListTreeController=_folderListTreeController;
@property(nonatomic) __weak NSSearchField *searchField; // @synthesize searchField=_searchField;
@property(nonatomic) __weak MainSplitView *mainSplitView; // @synthesize mainSplitView=_mainSplitView;
@property(nonatomic) __weak NSView *contentView; // @synthesize contentView=_contentView;
- (void).cxx_destruct;
- (void)window:(id)arg1 didDecodeRestorableState:(id)arg2;
- (void)window:(id)arg1 willEncodeRestorableState:(id)arg2;
- (void)restoreUserActivityState:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)sortByTagOfSender:(id)arg1;
- (void)beginNoteListSearch:(id)arg1;
- (void)toggleFoldersList:(id)arg1;
- (void)deleteFolder:(id)arg1;
- (void)newFolder:(id)arg1;
- (void)deleteNote:(id)arg1;
- (void)newNote:(id)arg1;
- (void)showSelectedNotesInSingleWindows:(id)arg1;
- (double)padViewTopMargin;
- (id)userStyleSheetURL;
@property(retain, nonatomic) MainWindow *window;
- (void)dealloc;
- (void)awakeFromNib;
- (id)windowNibName;

@end

