//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NFAttachment.h"

@interface NFAttachment (Scripting)
- (id)handleSaveScriptCommand:(id)arg1;
- (void)setScriptingContents:(id)arg1;
- (id)scriptingContents;
- (id)scriptingCID;
- (id)scriptingID;
- (id)objectSpecifier;
@end

