//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSBackgroundActivityScheduler;

@interface PowerManager : NSObject
{
    unsigned int _powerStateNotifier;
    unsigned int _powerStateSession;
    struct IONotificationPort *_powerStateNotificationPort;
    NSBackgroundActivityScheduler *_applicationRefreshActivity;
    CDUnknownBlockType _applicationRefreshCompletionHandler;
}

+ (id)sharedInstance;
+ (id)allocWithZone:(struct _NSZone *)arg1;
@property(copy) CDUnknownBlockType applicationRefreshCompletionHandler; // @synthesize applicationRefreshCompletionHandler=_applicationRefreshCompletionHandler;
@property(readonly, nonatomic) NSBackgroundActivityScheduler *applicationRefreshActivity; // @synthesize applicationRefreshActivity=_applicationRefreshActivity;
- (void).cxx_destruct;
- (void)_applicationRefreshDidEnd;
- (void)_accountSyncingDidChange:(BOOL)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (CDUnknownBlockType)_applicationRefreshShouldBegin;
- (void)_systemHasPoweredOn;
- (void)_systemWillSleep;
- (void)registerForPowerEvents;
- (void)dealloc;
- (id)init;

@end

