//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BRNonLocalVersionReceiving.h"

@class GSPermanentStorage, NSMutableArray, NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface BRNonLocalVersionReceiver : NSObject <BRNonLocalVersionReceiving>
{
    NSMutableArray *_versions;
    NSMutableDictionary *_versionsByURL;
    GSPermanentStorage *_versionsStore;
}

- (oneway void)newVersionAtURL:(id)arg1 faultURL:(id)arg2 faultExtension:(id)arg3 etag:(id)arg4 lastEditorDeviceName:(id)arg5;
- (BOOL)setVersionStoreForDocumentAtURL:(id)arg1 error:(id *)arg2;
- (void)dealloc;
- (id)initWithVersionArray:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

