//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface ASLIgnoreList : NSObject
{
    NSMutableArray *_ignoreList;
}

+ (id)ignoreMessageList;
+ (void)removeSenderFromIgnoreList:(id)arg1;
+ (void)ignoreMessages:(id)arg1;
+ (id)_ASLIgnoreListFile;
+ (id)sharedASLIgnoreList;
- (void).cxx_destruct;
- (BOOL)allowMessageSender:(id)arg1;
- (id)init;
- (id)ignoreMessageList;
- (void)removeSenderFromIgnoreList:(id)arg1;
- (void)setIgnoreList:(id)arg1;
- (void)ignoreMessages:(id)arg1;

@end

