//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSLevelIndicator.h"

@interface TagsLevelIndicator : NSLevelIndicator
{
    id _controller;
}

@property __weak id controller; // @synthesize controller=_controller;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;

@end

