//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSApplication.h"

@interface NSApplication (ScriptabilityPropertyListFile)
- (void)insertInPlistFiles:(id)arg1;
- (id)valueInPlistFilesWithName:(id)arg1;
- (id)plistFiles;
@end

