//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ScriptingClass.h"

@interface ScriptingElement : ScriptingClass
{
}

- (void)dealloc;
- (id)initWithParent:(id)arg1 andSiblings:(id)arg2;

@end

