//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCell.h"

@interface NSCell (VOUserSearchSetup)
- (void)pseudoMouseClick;
- (id)userSearchStop;
- (void)setUserSearchStop:(id)arg1;
- (id)userSearchRevealViewTag;
- (void)setUserSearchRevealViewTag:(id)arg1;
- (id)userSearchKeywords;
- (void)setUserSearchKeywords:(id)arg1;
- (id)userSearchTitle;
- (void)setUserSearchTitle:(id)arg1;
@end

