//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ReorderOption : NSObject
{
    NSString *_key;
    NSString *_title;
    BOOL _enabled;
}

+ (id)reorderOptionWithTitle:(id)arg1 enabled:(BOOL)arg2 key:(id)arg3;
@property(nonatomic) BOOL enabled; // @synthesize enabled=_enabled;
@property(retain, nonatomic) NSString *key; // @synthesize key=_key;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (id)description;
- (void)dealloc;

@end

