//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LTEAudioDevice, NSMutableArray, NSObject<OS_dispatch_queue>;

__attribute__((visibility("hidden")))
@interface LTEAudioManager : NSObject
{
    int audioRefCount;
    int connectionRefCount;
    int internalBlockSize;
    int hardwareSampleRate;
    struct AudioStreamBasicDescription vpioFormat;
    BOOL usingFloat;
    BOOL enableSpeakerPhone;
    BOOL isUsingSuppression;
    BOOL isTetheredDisplayMode;
    BOOL shouldSetupAudioSession;
    int clientPID;
    struct _opaque_pthread_mutex_t audioLock;
    NSObject<OS_dispatch_queue> *cmSessionQueue;
    NSObject<OS_dispatch_queue> *inputDeviceQueue;
    struct tagHANDLE *hAUIO;
    LTEAudioDevice *targetInputDevice;
    unsigned int preferredHardwareSampleRate;
    unsigned int currentVPOperatingMode;
    BOOL currentAudioRecordingMode;
    int currentSampleRate;
    int currentMinSamplesPerFrame;
    BOOL currentReceiverStatus;
    struct AudioEventQueue_t *eventQ;
    NSMutableArray *spkrConfList;
    NSMutableArray *micConfList;
    BOOL isGKVoiceChat;
    BOOL _microphoneMuted;
}

+ (id)defaultLTEAudioManager;
@property(nonatomic, getter=isMicrophoneMuted) BOOL microphoneMuted; // @synthesize microphoneMuted=_microphoneMuted;
@property(retain) LTEAudioDevice *targetInputDevice; // @synthesize targetInputDevice;
@property(readonly, nonatomic) BOOL usingFloat; // @synthesize usingFloat;
@property(nonatomic) int clientPID; // @synthesize clientPID;
@property(nonatomic) BOOL isUsingSuppression; // @synthesize isUsingSuppression;
@property(nonatomic) BOOL isGKVoiceChat; // @synthesize isGKVoiceChat;
- (void)onCaptureSound:(char *)arg1 numBytes:(int)arg2 numSamples:(int)arg3 timeStamp:(unsigned int)arg4 timeStampDelta:(int)arg5 bufferedSamples:(int)arg6 hostTime:(double)arg7 averagePower:(float)arg8 voiceActivity:(unsigned int)arg9;
- (void)onPlaySound:(char *)arg1 numBytes:(int)arg2 numSamples:(int)arg3 timeStamp:(unsigned int)arg4 averagePower:(float)arg5;
- (BOOL)projectionModeEnabledState;
- (unsigned int)preferredHardwareSampleRate;
- (void)setBlockSize:(BOOL)arg1;
- (void)setupVPBlockFormat;
- (void)setSampleRate;
- (void)resetAudioSessionProperties;
- (void)setAudioSessionProperties;
- (BOOL)forceBufferFrames:(int *)arg1;
- (BOOL)forceSampleRate:(double *)arg1;
- (void)tearDownAudioSession:(unsigned long long)arg1 forceTearDown:(BOOL)arg2;
- (void)stopAudioSession:(unsigned long long)arg1;
- (unsigned long long)startAudioSessionWithCompletionHandler:(CDUnknownBlockType)arg1 dispatchQueue:(id)arg2;
- (void)setAudioSessionParameters:(id)arg1;
- (void)audioSessionClientDied:(int)arg1;
- (unsigned long long)setupAudioSession;
@property BOOL shouldSetupAudioSession;
- (void)setupAudioNotifications;
@property(getter=isSpeakerPhoneEnabled) BOOL enableSpeakerPhone;
- (void)enableMetering:(BOOL)arg1 isInputMeter:(BOOL)arg2;
- (void)setSamplesPerFrame:(int)arg1;
- (void)getVpioFormat:(struct AudioStreamBasicDescription *)arg1;
- (void)processEventQueue;
- (void)removeConference:(id)arg1;
- (void)addConference:(id)arg1;
- (void)stopAudioIOWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)tearDownAudioIO:(BOOL)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (void)cleanupAUIOSetupWithResult:(int)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)startAudioIOWithFarEndVersionInfo:(struct VoiceIOFarEndVersionInfo *)arg1 minSamplesPerFrame:(int)arg2 internalFormat:(struct AudioStreamBasicDescription)arg3 allowAudioRecording:(BOOL)arg4 remoteCodecType:(unsigned int)arg5 remoteCodecSampleRate:(unsigned int)arg6 completionHandler:(CDUnknownBlockType)arg7;
- (void)AUIOTeardown:(BOOL)arg1;
- (void)AUIOSetup:(struct VoiceIOFarEndVersionInfo *)arg1 minSamplesPerFrame:(int)arg2 allowAudioRecording:(BOOL)arg3 ignoreRefCount:(BOOL)arg4 remoteCodecType:(unsigned int)arg5 remoteCodecSampleRate:(unsigned int)arg6 completionHandler:(CDUnknownBlockType)arg7;
- (void)updateTargetInputDevice;
- (BOOL)setCurrentInputDevice:(id)arg1;
- (id)currentInputDevice;
- (id)init;

@end

