//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LTENetworkAddress, NSString;

@interface LTEAudioSessionConfig : NSObject
{
    BOOL _rtcpEnabled;
    BOOL _rtcpXREnabled;
    BOOL _rtpTimeOutEnabled;
    BOOL _rtcpTimeOutEnabled;
    BOOL _octetAligned;
    BOOL _dtxEnabled;
    BOOL _rateAdaptationEnabled;
    unsigned short _rtcpRemotePort;
    long long _audioSessionMode;
    LTENetworkAddress *_localAddress;
    LTENetworkAddress *_remoteAddress;
    NSString *_cName;
    long long _codecType;
    long long _direction;
    unsigned long long _txPayloadType;
    unsigned long long _rxPayloadType;
    unsigned long long _dtmfPayloadType;
    unsigned long long _dtmfTimestampRate;
    unsigned long long _ptime;
    unsigned long long _maxPtime;
    double _rtcpSendInterval;
    double _rtpTimeOutInterval;
    double _rtcpTimeOutInterval;
    long long _rateModeMask;
}

@property(nonatomic) long long rateModeMask; // @synthesize rateModeMask=_rateModeMask;
@property(nonatomic, getter=isRateAdaptationEnabled) BOOL rateAdaptationEnabled; // @synthesize rateAdaptationEnabled=_rateAdaptationEnabled;
@property(nonatomic, getter=isDTXEnabled) BOOL dtxEnabled; // @synthesize dtxEnabled=_dtxEnabled;
@property(nonatomic, getter=isOctectAligned) BOOL octetAligned; // @synthesize octetAligned=_octetAligned;
@property(nonatomic) double rtcpTimeOutInterval; // @synthesize rtcpTimeOutInterval=_rtcpTimeOutInterval;
@property(nonatomic) double rtpTimeOutInterval; // @synthesize rtpTimeOutInterval=_rtpTimeOutInterval;
@property(nonatomic, getter=isRTCPTimeOutEnabled) BOOL rtcpTimeOutEnabled; // @synthesize rtcpTimeOutEnabled=_rtcpTimeOutEnabled;
@property(nonatomic, getter=isRTPTimeOutEnabled) BOOL rtpTimeOutEnabled; // @synthesize rtpTimeOutEnabled=_rtpTimeOutEnabled;
@property(nonatomic) double rtcpSendInterval; // @synthesize rtcpSendInterval=_rtcpSendInterval;
@property(nonatomic) unsigned short rtcpRemotePort; // @synthesize rtcpRemotePort=_rtcpRemotePort;
@property(nonatomic, getter=isRTCPXREnabled) BOOL rtcpXREnabled; // @synthesize rtcpXREnabled=_rtcpXREnabled;
@property(nonatomic, getter=isRTCPEnabled) BOOL rtcpEnabled; // @synthesize rtcpEnabled=_rtcpEnabled;
@property(nonatomic) unsigned long long maxPtime; // @synthesize maxPtime=_maxPtime;
@property(nonatomic) unsigned long long ptime; // @synthesize ptime=_ptime;
@property(nonatomic) unsigned long long dtmfTimestampRate; // @synthesize dtmfTimestampRate=_dtmfTimestampRate;
@property(nonatomic) unsigned long long dtmfPayloadType; // @synthesize dtmfPayloadType=_dtmfPayloadType;
@property(nonatomic) unsigned long long rxPayloadType; // @synthesize rxPayloadType=_rxPayloadType;
@property(nonatomic) unsigned long long txPayloadType; // @synthesize txPayloadType=_txPayloadType;
@property(nonatomic) long long direction; // @synthesize direction=_direction;
@property(nonatomic) long long codecType; // @synthesize codecType=_codecType;
@property(copy, nonatomic) NSString *cName; // @synthesize cName=_cName;
@property(retain, nonatomic) LTENetworkAddress *remoteAddress; // @synthesize remoteAddress=_remoteAddress;
@property(retain, nonatomic) LTENetworkAddress *localAddress; // @synthesize localAddress=_localAddress;
@property(nonatomic) long long audioSessionMode; // @synthesize audioSessionMode=_audioSessionMode;
- (BOOL)isAudioCodecValid;
- (BOOL)isValidConfig;
- (void)dealloc;
- (id)init;

@end

