//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NCButton.h"

@class NSMenu, NSObject<OS_dispatch_source>, NSPopUpButtonCell, NSTextField;

@interface NCAlertButton : NCButton
{
    NSPopUpButtonCell *_delayedPopupCell;
    NSObject<OS_dispatch_source> *_timer;
    id _observer;
    _Bool _menuShown;
    NSTextField *_buttonTitle;
    _Bool _showsDropdownArrow;
    _Bool _alwaysDropdown;
    _Bool __showingPopupMenu;
    id <NCAlertButtonDelegate> _delegate;
}

@property _Bool _showingPopupMenu; // @synthesize _showingPopupMenu=__showingPopupMenu;
@property _Bool alwaysDropdown; // @synthesize alwaysDropdown=_alwaysDropdown;
@property(nonatomic) _Bool showsDropdownArrow; // @synthesize showsDropdownArrow=_showsDropdownArrow;
@property __weak id <NCAlertButtonDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)__popupAction:(id)arg1;
@property(readonly, nonatomic) NSMenu *_popupMenu;
- (void)_buildAndShowMenu;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
@property(readonly, nonatomic) _Bool hasPopupMenu;
- (id)title;
- (void)setTitle:(id)arg1;
- (void)awakeFromNib;

@end

