//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSApplication.h"

@interface NCApplication : NSApplication
{
}

- (id)accessibilityAttributeValue:(id)arg1;
- (void)_cycleWindowsReversed:(BOOL)arg1;
- (id)makeWindowsPerform:(SEL)arg1 inOrder:(BOOL)arg2;
- (BOOL)_sendScreenNotificationWhenDockSizeChanges;

@end

