//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NCBannerViewController;

@interface NCBannerView : NSView
{
    NCBannerViewController *_owner;
}

@property __weak NCBannerViewController *owner; // @synthesize owner=_owner;
- (void).cxx_destruct;
- (void)updateConstraints;
- (void)awakeFromNib;

@end

