//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSExtension, NSImage, NSString;

@interface NCShareWidgetService : NSObject
{
    _Bool _hidden;
    NSImage *_image;
    NSString *_actionTitle;
    NSString *_serviceIdentifier;
    NSExtension *_extension;
}

+ (void)getServices:(CDUnknownBlockType)arg1;
@property(retain) NSExtension *extension; // @synthesize extension=_extension;
@property _Bool hidden; // @synthesize hidden=_hidden;
@property(readonly) NSString *serviceIdentifier; // @synthesize serviceIdentifier=_serviceIdentifier;
@property(readonly) NSString *actionTitle; // @synthesize actionTitle=_actionTitle;
@property(readonly) NSImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (_Bool)getServiceName;
@property(readonly) _Bool elected;
- (id)description;
- (id)initWithExtension:(id)arg1;

@end

