//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableView.h"

@interface NCTableView : NSTableView
{
    BOOL _animatorDisabled;
    _Bool _resetSelectionOnNextResign;
    double _extraSpace;
}

@property _Bool resetSelectionOnNextResign; // @synthesize resetSelectionOnNextResign=_resetSelectionOnNextResign;
@property double extraSpace; // @synthesize extraSpace=_extraSpace;
- (struct CGSize)_minimumFrameSize;
- (void)applyPermutationsFromArray:(id)arg1 toArray:(id)arg2 insertAnimation:(unsigned long long)arg3 removeAnimation:(unsigned long long)arg4;
- (void)paste:(id)arg1;
- (void)copy:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (BOOL)autoscroll:(id)arg1;
- (BOOL)resignFirstResponder;
- (void)keyDown:(id)arg1;
- (id)menuForEvent:(id)arg1;
- (void)performWithAnimatorOff:(CDUnknownBlockType)arg1;
- (id)animator;
@property id <NCTableViewDelegate> delegate;
- (void)awakeFromNib;

@end

