//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextFieldCell.h"

@class NSDictionary;

@interface NCTextFieldCell : NSTextFieldCell
{
    NSDictionary *_textAttributeOverrides;
}

@property(retain) NSDictionary *textAttributeOverrides; // @synthesize textAttributeOverrides=_textAttributeOverrides;
- (void).cxx_destruct;
- (id)_textAttributes;

@end

