//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class NSButton, NSLayoutConstraint, NSTextField;

@interface NCTodaySummaryItemController : NSViewController
{
    NSLayoutConstraint *_heightConstraint;
    NSTextField *_textField;
    NSButton *_actionButton;
}

@property NSButton *actionButton; // @synthesize actionButton=_actionButton;
@property NSTextField *textField; // @synthesize textField=_textField;
@property NSLayoutConstraint *heightConstraint; // @synthesize heightConstraint=_heightConstraint;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)setRepresentedObject:(id)arg1;
- (void)summaryClicked:(id)arg1;
- (void)awakeFromNib;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

