//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NCTodayItemViewControllerDelegate.h"

@class NCTodayHeaderViewController;

@protocol NCTodayHeaderDelegate <NCTodayItemViewControllerDelegate>
- (void)todayHeaderEditPressed:(NCTodayHeaderViewController *)arg1;
- (void)todayHeaderDeletePressed:(NCTodayHeaderViewController *)arg1;
@end

