//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCell.h"

@interface RankCell : NSCell
{
    double _rank;
}

- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)setRank:(id)arg1;
- (id)rank;

@end

