//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DUSupport/DUDisk.h>

@interface DUDiskListSeparator : DUDisk
{
}

- (id)description;
- (void)diskOneLineDescription;
- (BOOL)hasParentDisk;
- (BOOL)outlineViewCellIsEnabled;
- (BOOL)hasSpecialOutlineViewDrawing;
- (BOOL)canSelect;
- (int)calculateDUDiskType;
- (id)toolTipString;
- (id)uncachedDisplayIcon;
- (id)displayName;

@end

