//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DUSupport/DUDiskCoreStorage.h>

@interface DUDiskCoreStorageLogicalVolumeGroup : DUDiskCoreStorage
{
}

- (void)invalidateCachedData;
- (id)coreStorageData;
- (id)physicalDADisksForLogicalVolume;
- (id)physicalDiskIdentifiers;
- (unsigned long long)freeSpace;
- (unsigned long long)totalSize;
- (id)coreStorageStatus;
- (BOOL)isWhole;
- (int)calculateDUDiskType;
- (BOOL)isCoreStorageLogicalVolumeGroup;
- (id)coreStorageVolumeUUID;
- (id)toolTipString;
- (BOOL)canBeRestoreSource;
- (unsigned long long)partitionNumber;
- (id)diskDisplayType;
- (id)children;

@end

