//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class DMManager, DUDiskController, NSNumber, NSString, NSView;

@protocol DUPluginProtocol
- (void)setupModule:(id)arg1;
- (void)parentTabViewChanged:(id)arg1;
- (void)deselectTab;
- (void)becomeSelectedTab;
- (void)selectionDidChange:(id)arg1;
- (void)registerForNotifications;
- (NSString *)displayName;
- (NSNumber *)tabOrder;
- (BOOL)shouldRunOnThisConfig;
- (NSString *)dataType;
- (void)helpButtonAction:(id)arg1;
- (void)printModuleSpecific:(id)arg1;
- (BOOL)canPrint;
- (NSString *)warnOnSwitch;
- (NSString *)warnOnQuit;
- (NSString *)warnOnClose;
- (void)setActiveTab;
- (BOOL)currentActiveTab;
- (void)setParentTabViewItem:(id)arg1;
- (void)setParentTabView:(id)arg1;
- (void)setWindowController:(id)arg1;
- (NSView *)utilityView;
- (id)parentTabViewItem;
- (id)parentTabView;
- (id)windowController;
- (DUDiskController *)diskController;
- (void)resetDM;
- (DMManager *)dm;
- (void)moduleDidLoad;
@end

