//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DURebuildRAIDController : NSObject
{
    id _progress;
    NSString *_diskIdentifier;
    NSString *_raidMemberUUID;
    double _status;
    BOOL _rebuilding;
    id _timeEstimator;
}

- (void)cleanUpProgress;
- (id)raidMemberUUID;
- (id)diskIdentifier;
- (void)periodicallyCheckRAIDRebuild:(id)arg1;
- (void)getProgress:(id)arg1;
- (void)trackRebuild:(id)arg1;
- (void)dealloc;
- (id)initWithDUDisk:(id)arg1;

@end

