//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DUIndicatorSecureTextField, NSButton, NSSecureTextField, NSString, NSTextField, NSView, NSWindow, SFPasswordAssistantInspectorController, SFPasswordStrengthView;

@interface DUSecurePasswordEntryController : NSObject
{
    NSWindow *mChangePasswordSheet;
    NSView *mChangePasswordWarningView;
    NSTextField *mChangePasswordTitleTextField;
    NSTextField *mChangePasswordMsgTextField;
    NSTextField *mChangePasswordExtraWarningTextField;
    NSTextField *mChangePasswordHintTextField;
    NSButton *mChangePasswordAssistantButton;
    DUIndicatorSecureTextField *mChangePasswordNew;
    NSTextField *mChangePasswordWarningTextField;
    NSSecureTextField *mChangePasswordVerify;
    NSButton *mChangePasswordCancelButton;
    NSButton *mChangePasswordEraseButton;
    SFPasswordStrengthView *mChangePasswordStrengthView;
    SFPasswordAssistantInspectorController *mPasswordAssistant;
    NSString *mVolumeName;
    NSString *mFilesystemName;
    id delegate;
}

@property(copy) NSString *filesystemName; // @synthesize filesystemName=mFilesystemName;
@property(copy) NSString *volumeName; // @synthesize volumeName=mVolumeName;
@property(retain) id delegate; // @synthesize delegate;
- (id)buttons;
- (void)passwordAssistantButtonAction:(id)arg1;
- (void)cancelButtonAction:(id)arg1;
- (void)eraseButtonAction:(id)arg1;
- (void)getNewPasswordFromUser:(id)arg1;
- (void)setExtraWarning:(id)arg1;
- (void)setMessage:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)dealloc;
- (id)init;
- (void)controlTextDidChange:(id)arg1;
- (void)_showWarningForField:(id)arg1;
- (void)loadBundleIfNotLoaded;

@end

