//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMenu, NSMenuItem;

@interface GoMenuController : NSObject
{
    NSMenu *goMenu;
    NSMenuItem *backMenuItem;
    NSMenuItem *forwardMenuItem;
    long long _numStaticItems;
    BOOL _addedAnItem;
}

- (BOOL)validateMenuItem:(id)arg1;
- (void)addToList:(id)arg1;
- (void)hvGoForward:(id)arg1;
- (void)hvGoBack:(id)arg1;
- (void)goUsingSelectedItem:(id)arg1;
- (void)setNumStaticItems:(long long)arg1;
- (long long)numStaticItems;
- (void)setAddedAnItem:(BOOL)arg1;
- (BOOL)addedAnItem;
- (void)dealloc;
- (id)init;

@end

