//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSFileManager.h"

@interface NSFileManager (HelpViewerFileManagerAdditions)
- (id)pathOfResolvedAliasAtPath:(id)arg1;
- (BOOL)isAliasFileAtPath:(id)arg1;
- (BOOL)isAppleHelpIndexFileAtPath:(id)arg1;
- (BOOL)isHTMLOrPlainTextFileAtPath:(id)arg1;
@end

