//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CardHeaderView.h"

@class NSArray, NSTextField;

@interface CardListHeaderView : CardHeaderView
{
    NSTextField *_titleField;
    NSTextField *_subtitleField;
    NSArray *_sharees;
}

@property(retain) NSArray *sharees; // @synthesize sharees=_sharees;
@property(retain) NSTextField *subtitleField; // @synthesize subtitleField=_subtitleField;
@property(retain) NSTextField *titleField; // @synthesize titleField=_titleField;
- (void).cxx_destruct;
- (id)title;
- (void)setAddButtonHidden:(BOOL)arg1;
- (void)updateTitle:(id)arg1;
- (void)setFrameSize:(struct CGSize)arg1;
- (void)updateSubtitleField;
- (void)updateSubtitleFieldForList:(id)arg1;
- (void)updateTitleForLists:(id)arg1;
- (struct CGRect)titleFrame;
- (id)initWithFrame:(struct CGRect)arg1 controller:(id)arg2;

@end

