//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextField.h"

@class IGRecurrencePicker;

@interface IGRecurrenceSummaryField : NSTextField
{
    IGRecurrencePicker *_controller;
}

@property __weak IGRecurrencePicker *controller; // @synthesize controller=_controller;
- (void).cxx_destruct;
- (void)mouseDown:(id)arg1;
- (id)initWithController:(id)arg1;

@end

