//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CUIKUserActivityCompliant.h"

@class NSArray, NSSet, NSString;

@interface RemindersList : NSObject <CUIKUserActivityCompliant>
{
    NSString *_symbolicColor;
    NSArray *_cachedReminders;
    NSSet *_cachedReminderIDs;
}

+ (id)matchForActivity:(id)arg1;
+ (id)colorForLists:(id)arg1;
+ (id)defaultListColor;
@property(retain) NSSet *cachedReminderIDs; // @synthesize cachedReminderIDs=_cachedReminderIDs;
@property(retain) NSArray *cachedReminders; // @synthesize cachedReminders=_cachedReminders;
@property(retain) NSString *symbolicColor; // @synthesize symbolicColor=_symbolicColor;
- (void).cxx_destruct;
- (BOOL)isMatchForActivity:(id)arg1;
- (id)representedActivity;
- (id)image;
- (id)color;
- (BOOL)isVisibleInSidebar;
- (long long)displayOrder;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)swipeType;
- (BOOL)acceptsReminders;
- (BOOL)canBeMultiSelected;
- (id)shareesAndOwnerButNotMe;
- (id)sharees;
- (BOOL)canBeShared;
- (BOOL)isSharedToMe;
- (BOOL)isShared;
- (BOOL)isReorderable;
- (BOOL)canEditColor;
- (BOOL)canBeDeleted;
- (BOOL)canBeRenamed;
- (BOOL)isEditable;
- (BOOL)allowsEvents;
- (void)save;
- (void)deleteList;
- (void)acceptReminder:(id)arg1;
- (id)newReminder;
- (void)revertToLastCommittedTitle;
- (void)renameTo:(id)arg1;
- (id)identifier;
- (BOOL)shouldDisplayReminder:(id)arg1 forCompletedSide:(BOOL)arg2;
- (BOOL)shouldDisplayReminder:(id)arg1;
- (BOOL)hasCompletedReminders;
- (unsigned long long)numberOfCompletedReminders;
- (id)completedReminders;
- (id)incompleteReminders;
- (id)reminders;
- (id)fetchReminders;
- (BOOL)hasSubtitle;
- (id)title;
- (void)invalidateReminderCache;
- (void)invalidateReminderCacheIfNecessaryForChangedReminderIDs:(id)arg1;

@end

