//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMenuItem.h"

@class NSMenu;

@interface RemindersNewListMenuItem : NSMenuItem
{
    NSMenu *_accountSubmenu;
}

@property(retain) NSMenu *accountSubmenu; // @synthesize accountSubmenu=_accountSubmenu;
- (void).cxx_destruct;
- (void)refresh;
- (void)dealloc;
- (id)init;

@end

