//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RemindersUtilities : NSObject
{
}

+ (void)disableTermination:(id)arg1;
+ (void)enableTermination:(id)arg1;
+ (id)fontWithFontSize:(double)arg1 bold:(BOOL)arg2;
+ (id)remindersBundle;
+ (id)sharedNumberFormatter;
+ (id)sharedDateFormatter;
+ (void)resetSharedFormatters;

@end

