//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGLocationSubtextField, IGProximityGadget, IGRemindMeLocationField, NSError;

@interface RemindMeLocationDelegate : NSObject
{
    NSError *_locationFailure;
    IGRemindMeLocationField *_remindMeLocationField;
    IGLocationSubtextField *_locationSubtextField;
    IGProximityGadget *_proximityGadget;
}

@property(retain) IGProximityGadget *proximityGadget; // @synthesize proximityGadget=_proximityGadget;
@property(retain) IGLocationSubtextField *locationSubtextField; // @synthesize locationSubtextField=_locationSubtextField;
@property(retain) IGRemindMeLocationField *remindMeLocationField; // @synthesize remindMeLocationField=_remindMeLocationField;
- (void).cxx_destruct;
- (id)relatedGadgets;
- (long long)proximity;
- (void)proximityDidChangeToNewProximity:(long long)arg1;
@property(retain) NSError *locationFailure; // @synthesize locationFailure=_locationFailure;
- (id)init;

@end

