//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSPageController.h"

@class PagingDotView;

@interface RemindersPageController : NSPageController
{
    PagingDotView *_pagingDotView;
}

@property(retain) PagingDotView *pagingDotView; // @synthesize pagingDotView=_pagingDotView;
- (void).cxx_destruct;
- (void)navigateToPage:(long long)arg1;
- (void)updatePagingDotView;
- (BOOL)shouldShowPagingDots;
- (void)setSelectedIndex:(long long)arg1;
- (void)setArrangedObjects:(id)arg1;
- (id)init;

@end

