//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FP_INSTALLER_FPIMRootActions.h"

@interface FP_INSTALLER_FPIMRootActions (Internal)
- (void)_configureInstallHelperAtPath:(id)arg1;
- (BOOL)_authorizeUser;
- (BOOL)_executePrivilegedTaskSync:(const char *)arg1 withArguments:(char **)arg2;
- (BOOL)_executePrivilegedTaskAsync:(const char *)arg1 withArguments:(char **)arg2;
- (BOOL)__executePrivilegedTask:(const char *)arg1 withArguments:(char **)arg2 commPipe:(struct __sFILE **)arg3;
@end

