//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FPIMForwardSequencePanel.h"

@class FPIMProgressIndicator, FPIMTextField, NSButton, NSMatrix, NSTimer, NSView;

@interface FPIM_FSP_Install : FPIMForwardSequencePanel
{
    NSView *mPanelView;
    FPIMProgressIndicator *mProgressIndicator;
    FPIMTextField *mActionMessageTextField;
    FPIMTextField *mPercentCompletedTextField;
    NSButton *mDoneButton;
    FPIMTextField *mCompletedMessageTextField;
    NSMatrix *mUpdateMethodRadioButtons;
    NSButton *mClickForSupport;
    unsigned long long mBytesInstalled;
    unsigned long long mTotalBytesToInstall;
    NSTimer *mProgressUpdateTimer;
    BOOL mInstallCompleted;
    BOOL mInstallSucceeded;
}

- (void)panelDidDisplay;
- (BOOL)shouldDisplayPanel;
- (void)_startInstalling;
- (void)_installRunnable;
- (id)contentView;
- (void)_updateInstallStatus;
- (void)_installDidComplete;
- (void)_preparePanelForCompletionStateWithAddedHeight:(float)arg1 andWidth:(float)arg2;
- (void)_addPostInstallErrorUI;
- (void)_addPostInstallSuccessUI;
- (void)_addSAUUI;
- (id)_newInstallPanel;
- (void)dealloc;
- (void)iaDoneButtonPressed:(id)arg1;
- (void)iaGetSupportButtonPressed:(id)arg1;

@end

