//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FPIMDownloadProgressReceiver.h"

@class FPIMDownload, NSString;

@interface FPIMVersionManager : NSObject <FPIMDownloadProgressReceiver>
{
    FPIMDownload *mDownload;
    int mXMLDownloadState;
    NSString *mXMLVersionString;
    NSString *mHTMLDisplayString;
    NSString *mAutoUpdateModeString;
    float mDialogWidth;
    float mDialogHeight;
}

+ (int)compareTuple1:(id)arg1 withTuple2:(id)arg2;
+ (int)checkDowngradeAttempt;
+ (int)checkMinimumSystemRequirements;
+ (int)performInstallChecks;
+ (id)versionOfFlashPlayerOnSystem;
+ (id)versionOfFlashPlayerToBeInstalled;
- (float)dialogWidth;
- (float)dialogHeight;
- (id)AutoUpdateModeString;
- (id)HTMLDisplayString;
- (id)XMLVersionString;
- (int)downloadState;
- (void)downloadDidFail;
- (void)downloadDidComplete;
- (void)sendVersionXMLRequest;
- (void)dealloc;
- (id)init;

@end

