//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSView, NSWindow;

@interface FPIMApplicationManager : NSObject
{
    NSWindow *uiApplicationWindow;
    NSView *uiMainView;
    NSArray *mInstallerPanels;
    NSArray *mUninstallerPanels;
    NSArray *mAutoUpdatePanels;
    NSArray *mPanels;
    id mCurrentPanel;
    unsigned int mCurrentPanelIndex;
}

+ (int)getApplicationConfiguration;
+ (void)performUninstallation;
+ (int)performInstallationOfPkg;
+ (void)closeLogs;
+ (id)logger;
+ (id)packagePath;
+ (int)applicationMode;
+ (void)setApplicationMode:(int)arg1;
- (void)windowWillClose:(id)arg1;
- (BOOL)windowShouldClose:(id)arg1;
- (unsigned int)applicationShouldTerminate:(id)arg1;
- (BOOL)applicationShouldTerminateAfterLastWindowClosed:(id)arg1;
- (void)dealloc;
- (void)applicationDidFinishLaunching:(id)arg1;

@end

