//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FPIMForwardSequencePanel.h"

@class FPIMTextField, NSButton, NSView;

@interface FPIM_FSP_Uninstall : FPIMForwardSequencePanel
{
    NSView *mPanelView;
    FPIMTextField *mDescriptionText;
    NSButton *mDoneButton;
}

- (void)panelDidDisplay;
- (BOOL)shouldDisplayPanel;
- (id)contentView;
- (void)iaDoneButtonPressed:(id)arg1;
- (void)dealloc;
- (void)_uninstallDidCompleteHandler;
- (void)_performUninstallRunnable;
- (id)_newUninstallPanel;

@end

