//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FPIMForwardSequencePanel.h"

@class FPIMConflictingProcesses, NSButton, NSMutableArray, NSView;

@interface FPIM_FSP_CloseFPClients : FPIMForwardSequencePanel
{
    NSView *mPanelView;
    NSButton *mRetryButton;
    NSMutableArray *mOpenPIDButtons;
    FPIMConflictingProcesses *mConflictingProcesses;
}

- (void)iaQuitButtonPressed:(id)arg1;
- (void)iaRetryButtonPressed:(id)arg1;
- (void)iaForceCloseAllButtonPressed:(id)arg1;
- (void)iaCloseApplicationButtonPressed:(id)arg1;
- (void)panelDidDisplay;
- (void)panelWillDisplay;
- (BOOL)shouldDisplayPanel;
- (id)contentView;
- (void)dealloc;
- (id)init;
- (id)_newCloseFPClientsPanel;

@end

