//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSFormatter.h"

@class NSMutableParagraphStyle;

@interface IASPParagraphStyleFormatter : NSFormatter
{
    NSMutableParagraphStyle *_paragraphStyle;
}

- (id)attributedStringForObjectValue:(id)arg1 withDefaultAttributes:(id)arg2;
- (id)stringForObjectValue:(id)arg1;
- (void)setLineBreakMode:(unsigned long long)arg1;
- (void)dealloc;
- (id)init;

@end

