//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewAnimation.h"

@class NSString;

@interface IAViewAnimation : NSViewAnimation
{
    NSString *_identifier;
}

- (id)identifier;
- (void)setIdentifier:(id)arg1;
- (void)dealloc;

@end

