//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ShareKit/SHKBorderlessEffectWindow.h>

@class CALayer, NSWindow;

@interface SHKDimAndShadowWindow : SHKBorderlessEffectWindow
{
    BOOL animatesTransitions;
    CALayer *dimLayer;
    CALayer *shadowLayer;
    CALayer *shadowCenterKnockoutLayer;
    NSWindow *_remoteWindow;
    NSWindow *_sourceWindow;
}

@property __weak NSWindow *sourceWindow; // @synthesize sourceWindow=_sourceWindow;
@property __weak NSWindow *remoteWindow; // @synthesize remoteWindow=_remoteWindow;
@property BOOL animatesTransitions; // @synthesize animatesTransitions;
- (void).cxx_destruct;
- (void)startTransitionOut;
- (void)continueTransitionInWithIdentityLayerTransformAfterDelay:(double)arg1;
- (void)startTransitionInWithDimFrame:(struct CGRect)arg1 serviceScreenFrame:(struct CGRect)arg2 initialLayerTransform:(struct CGAffineTransform)arg3;
- (id)initWithFrame:(struct CGRect)arg1 noSourceWindow:(BOOL)arg2;

@end

