//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSVisualEffectView.h>

@class NSView;

@interface NSBackdropView : NSVisualEffectView
{
}

- (BOOL)allowsVibrancy;
@property(readonly) NSView *contentView;
- (long long)blendingMode;
- (void)setBlendingMode:(long long)arg1;
@property unsigned long long compositingOperation;
- (void)setState:(long long)arg1;
- (long long)state;
@property long long materialType;
- (id)initWithFrame:(struct CGRect)arg1;

@end

