//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSAppearance.h>

@class NSBundle;

__attribute__((visibility("hidden")))
@interface NSVibrantDarkAppearance : NSAppearance
{
    NSBundle *_systemAppearanceBundle;
}

- (long long)_internalVisualEffectMaterialForTitlebar;
- (long long)_internalVisualEffectMaterialForBlendingMode:(long long)arg1;
- (int)_defaultBlendMode;
- (BOOL)allowsVibrancy;
- (id)init;
- (void)dealloc;
- (id)name;

@end

