//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PhotoLibrary/PHLIngestRequest.h>

@class NSArray, NSDictionary, PHLIngestAsset;

@interface PHLMutableIngestRequest : PHLIngestRequest
{
}


// Remaining properties
@property(retain) NSArray *adjustments;
@property(retain) PHLIngestAsset *masterAsset;
@property(retain) NSDictionary *metadataProperties;
@property long long options;
@property(retain) PHLIngestAsset *renderedAsset;
@property(retain) PHLIngestAsset *thumbnailAsset;
@property(retain) NSDictionary *userInfo;
@end

