//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CPAlias : NSObject
{
    id mReference;
}

+ (id)aliasWithReference:(id)arg1;
- (void)forwardInvocation:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;
- (void)setReference:(id)arg1;
- (id)reference;
- (void)dealloc;
- (id)initWithReference:(id)arg1;

@end

