//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDocument.h"

@class NSMutableDictionary;

@interface CPBasicDocument : NSDocument
{
    BOOL mActive;
    NSMutableDictionary *mSettings;
}

+ (void)initializeFormatMenu;
+ (id)currentSettings;
+ (id)currentDocument;
- (void)removeDocumentMenus:(id)arg1;
- (void)addDocumentMenus:(id)arg1;
- (id)settings;
- (void)dealloc;
- (void)windowControllerDidLoadNib:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)windowDidBecomeKey:(id)arg1;
- (void)becomesInactive;
- (void)becomesInactiveSelf;
- (void)becomesActive;
- (void)becomesActiveSelf;
- (id)init;

@end

