//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableColumn.h"

@class EQFieldCell;

@interface CPEquationTableColumn : NSTableColumn
{
    EQFieldCell *mEquationFieldCell;
}

- (id)dataCell;
- (void)dealloc;
- (void)awakeFromNib;

@end

