//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CPPreferencePanelItem.h"

@interface CPGeneralPreferencePanelItem : CPPreferencePanelItem
{
    id mShowSyntaxError;
    id mDefaultLengthUnit;
    id mDocumentLevelsOfUndo;
    id mEquationLevelsOfUndo;
    id mAdjustMargin;
    id mZoomFactor;
    id mUseSelectionColor;
    id mResolutionForTIFF;
    id mSnapshotFormat;
    id mParamCriticalNumber;
}

- (id)iconName;
- (id)group;
- (id)label;
- (void)update:(id)arg1;
- (void)didHide;
- (void)willShow;

@end

