//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CPTableView.h"

@interface CPPatternTableView : CPTableView
{
}

- (BOOL)acceptsFirstMouse:(id)arg1;
- (BOOL)needsPanelToBecomeKey;
- (BOOL)isStriped;

@end

