//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CPScaleDialog.h"

@interface CPScale2DDialog : CPScaleDialog
{
    id mScaleArray;
}

- (long long)scaleIndex;
- (void)selectScaleAtIndex:(long long)arg1;

@end

