//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CPStretchAxisAction.h"

@interface CPStretchPolarLogAxisAction : CPStretchAxisAction
{
}

- (void)stretchScaleTo:(struct CGPoint)arg1;
- (BOOL)startMove:(struct CGPoint)arg1;

@end

