//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class CPView3D;

@protocol CPView3DSource
- (void)glDrawView:(CPView3D *)arg1 opaque:(BOOL)arg2;
- (void)applySettingsToView:(CPView3D *)arg1;
- (void)glDrawBackgroundOfView:(CPView3D *)arg1 withWidth:(double)arg2 height:(double)arg3;
@end

