//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CPViewAction.h"

@interface CPZoomAction : CPViewAction
{
}

+ (id)actionIdentifier;
- (SEL)menuItemAction;
- (id)cursorWithModifierFlags:(unsigned long long)arg1;
- (void)performWithEvent:(id)arg1 inView:(id)arg2;

@end

