//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class GSystem, NSArray;

@interface DDiffEqVector : NSObject <NSCoding>
{
    GSystem *mSystem;
    NSArray *mAxes;
}

+ (id)vectorFromOperation:(id)arg1 inSpace:(id)arg2 withVariable:(id)arg3;
- (id)axes;
- (BOOL)isSameAs:(id)arg1;
- (void)dealloc;
- (id)initWithSystem:(id)arg1 axes:(id)arg2;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

