//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class EEvaluator;

@interface EOutputView : NSView
{
    EEvaluator *mEvaluator;
}

+ (id)textForDerivativeOf:(id)arg1 withRespectTo:(id)arg2 order:(unsigned long long)arg3;
- (void)display:(id)arg1;

@end

