//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDouble.h"

@interface FMultiple : FDouble
{
}

+ (unsigned long long)argumentNumber;
- (BOOL)acceptArgumentCount:(unsigned long long)arg1;
- (unsigned long long)minArgumentNumber;

@end

