//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GView, NSColor;

@interface GCursor : NSObject
{
    BOOL mVisible;
    GView *mView;
    NSColor *mColor;
}

+ (BOOL)instancesCanBeDrawnInView:(id)arg1;
- (void)takeColorFrom:(id)arg1;
- (void)setColor:(id)arg1;
- (void)stroke;
- (void)draw;
- (void)drawSelf;
- (void)hide;
- (void)show;
- (void)setVisible:(BOOL)arg1;
- (BOOL)isVisible;
- (void)dealloc;
- (id)initWithView:(id)arg1;

@end

