//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GAction.h"

@interface GInsertObjectAction : GAction
{
    Class mObject;
}

+ (id)actionWithView:(id)arg1 object:(Class)arg2;
- (void)performWithEvent:(id)arg1;
- (id)initWithView:(id)arg1 object:(Class)arg2;

@end

