//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPolygon.h"

@interface GPolygon3D : GPolygon
{
}

- (id)glObjectWithAttributes:(id)arg1;
- (void)lineToCoord:(double [3])arg1;
- (void)moveToCoord:(double [3])arg1;
- (void)lineToPoint:(struct _GPoint3D)arg1;
- (void)moveToPoint:(struct _GPoint3D)arg1;

@end

