//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GLinearAxis3D.h"

@interface GPolarRadial3D : GLinearAxis3D
{
}

- (void)axisCoord:(double *)arg1 forValue:(double)arg2 offset:(double)arg3:(double)arg4;
- (id)defaultInternalName;

@end

