//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GAttributeView.h"

@interface GTicksLabelAttributeView : GAttributeView
{
    id mMajorTick;
    id mMajorNumbered;
    id mMinorTick;
    id mMinorNumbered;
    id mLabel;
}

- (void)awakeFromNib;

@end

