//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NRootFinder.h"

@interface NGradientDescent : NRootFinder
{
}

- (void)findExtremumFromInitialPoint;
- (void)findRootFromInitialPoint;
- (void)gradient:(double *)arg1 at:(const double *)arg2;

@end

