//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSum : NSObject
{
    struct _NComplex mValue;
}

+ (id)sum;
- (struct _NComplex)result;
- (void)add:(struct _NComplex)arg1;
- (id)init;

@end

