//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NDerivator.h"

@class NSObject<NEvaluable>, NSObject<NVariableValue>;

@interface NVariableValueDerivator : NDerivator
{
    NSObject<NEvaluable> *mMember;
    NSObject<NVariableValue> *mVariable;
}

+ (id)variableValueDerivatorWithMember:(id)arg1 variable:(id)arg2;
- (struct _NComplex)complexValueAt:(double)arg1;
- (void)dealloc;
- (id)initWithMember:(id)arg1 variable:(id)arg2;

@end

