//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OPOperation.h"

@interface OPNegative : OPOperation
{
}

+ (id)negativeOf:(id)arg1;
- (id)partialDerivative:(unsigned long long)arg1;
- (id)simplified;
- (struct _NComplex)computeComplexWith:(struct _NComplex)arg1;
- (double)computeRealWith:(double)arg1;

@end

