//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSOpenSavePanelDelegate.h"

@class ConvertHelper, CryptoHelper, NSPopUpButton, NSSavePanel, NSString, NSView;

@interface ConvertImageController : NSObject <NSOpenSavePanelDelegate>
{
    NSView *accessoryView;
    NSPopUpButton *encryptPopup;
    NSPopUpButton *formatPopup;
    CryptoHelper *_cryptoHelper;
    ConvertHelper *_convertHelper;
    NSSavePanel *_savePanel;
    BOOL _allowIFFFormats;
}

+ (id)convertImageController;
- (void)setAllowIFFFormats:(BOOL)arg1;
- (BOOL)allowIFFFormats;
- (void)formatPopupChanged:(id)arg1;
- (void)encryptPopupChanged:(id)arg1;
- (void)setupAccessoryView;
- (void)cleanupAccessoryView;
- (id)getAccessoryView;
- (void)getImageParameters:(id)arg1 withWindow:(id)arg2 withDefaultDirectory:(id)arg3 andDefaultFilename:(id)arg4 selectorData:(id)arg5 selector:(SEL)arg6 controller:(id)arg7;
- (void)dealloc;
- (id)init;
- (id)extractInfoFromSavelPanel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

