//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CalUIEventSuggestionsManager : NSObject
{
}

+ (id)timeZoneForStructuredLocation:(id)arg1;
+ (id)fetchEventsWithTitleMatchingQuery:(id)arg1 inEventStore:(id)arg2;
+ (id)stripRanges:(id)arg1 fromString:(id)arg2;
+ (id)performTimeDetection:(id)arg1 options:(unsigned long long)arg2 referenceDate:(id)arg3;
+ (void)findSuggestionsForQuery:(id)arg1 withDefaultCalendar:(id)arg2 options:(unsigned long long)arg3 referenceDate:(id)arg4 withHandler:(CDUnknownBlockType)arg5;

@end

