//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSImageView.h"

@class NSImage;

@interface CalUIFace : NSImageView
{
    NSImage *_faceImage;
}

@property(retain) NSImage *faceImage; // @synthesize faceImage=_faceImage;
- (void).cxx_destruct;

@end

