//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@interface NSView (OverlayUtilities)
- (struct CGRect)convertRect:(struct CGRect)arg1 toOverlayView:(id)arg2;
- (struct CGRect)convertRect:(struct CGRect)arg1 fromOverlayView:(id)arg2;
- (struct CGPoint)convertPoint:(struct CGPoint)arg1 toOverlayView:(id)arg2;
- (struct CGPoint)convertPoint:(struct CGPoint)arg1 fromOverlayView:(id)arg2;
@end

