//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCNRenderer.h"

@class PVC3DContainer;

@interface PVC3DThumbnailRenderer : SCNRenderer
{
    PVC3DContainer *_container;
}

- (void)dealloc;
- (void)setContainer:(id)arg1;
- (id)initWithContainer:(id)arg1;

@end

