//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSMutableArray, NSURL;

@interface PVFileCreatorOperation : NSOperation
{
    CDUnknownBlockType _blockToExecute;
    NSURL *_basePath;
    NSMutableArray *_resultArray;
}

- (void)main;
- (void)dealloc;
- (id)initWithBlock:(CDUnknownBlockType)arg1 usingBasePath:(id)arg2 resultArray:(id)arg3;

@end

