//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class PVFloatingSidebarWindow;

@protocol PVFloatingSidebarDelegate

@optional
- (void)floatingSidebarWillExpand:(PVFloatingSidebarWindow *)arg1 needsUpdate:(BOOL)arg2;
- (void)floatingSidebar:(PVFloatingSidebarWindow *)arg1 didResizeToWidth:(double)arg2;
- (double)maxWidthForFloatingSidebar:(PVFloatingSidebarWindow *)arg1;
- (double)minWidthForFloatingSidebar:(PVFloatingSidebarWindow *)arg1;
@end

