//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArrayController, NSTableView, PVInspectorPanelController;

@interface PVInspectorKeywordsController : NSObject
{
    PVInspectorPanelController *_panelController;
    NSTableView *_tableView;
    NSArrayController *_keywords;
}

- (void)removeSelectedKeywords:(id)arg1;
- (void)addKeyword:(id)arg1;
- (void)selectLastRowOfTable;
- (void)commitEditsInTable;

@end

