//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSCondition;

@interface PVOperation : NSOperation
{
    NSCondition *_finishedCond;
}

- (void)_broadcastFinishedCondition;
- (void)waitUntilFinished;
- (void)didChangeValueForKey:(id)arg1;
- (void)dealloc;
- (id)init;

@end

