//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableCellView.h"

@class NSImageView, NSTextField;

@interface PVSearchResultMediaContainerItemCellView : NSTableCellView
{
    NSTextField *_resultTitle;
    NSImageView *_thumbnailImageView;
}

+ (double)heightOfViewWithThumbnail:(BOOL)arg1;
@property(readonly) NSImageView *thumbnailImageView; // @synthesize thumbnailImageView=_thumbnailImageView;
@property(readonly) NSTextField *resultTitle; // @synthesize resultTitle=_resultTitle;
- (void)_setTextColorForBackgroundStyle:(long long)arg1;
- (void)setBackgroundStyle:(long long)arg1;
- (void)viewWillDraw;
- (void)setObjectValue:(id)arg1;
- (void)stopObservingObject:(id)arg1;
- (void)startObservingObject:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;

@end

