//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextField.h"

@class NSTrackingArea;

@interface PVStaticLinkText : NSTextField
{
    id _linkDestination;
    NSTrackingArea *_rolloverTrackingArea;
}

+ (Class)cellClass;
@property(retain) id linkDestination; // @synthesize linkDestination=_linkDestination;
- (void)_setTextUnderlineStyle:(long long)arg1;
- (struct CGRect)_textBounds;
- (void)resetCursorRects;
- (void)updateTrackingAreas;
- (void)mouseDown:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

