//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSSegmentedControl.h"

@interface PVSubToolbarSegmentedControl : NSSegmentedControl
{
    id _menuController;
}

@property(retain) id menuController; // @synthesize menuController=_menuController;
- (id)description;
- (void)setImage:(id)arg1 forSegment:(long long)arg2;
- (void)setSelected:(BOOL)arg1 forSegment:(long long)arg2;
- (void)dealloc;
- (id)init;

@end

