//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSWindow;

@interface PVWindowDebugOverlay : NSView
{
    NSWindow *_windowBeingOverlaid;
}

@property(readonly) NSWindow *windowBeingOverlaid; // @synthesize windowBeingOverlaid=_windowBeingOverlaid;
- (void)drawRect:(struct CGRect)arg1;
- (void)_drawLineWithWidth:(double)arg1 fromFirstResponder:(id)arg2 withIterator:(CDUnknownBlockType)arg3;
- (id)initWithWindow:(id)arg1;

@end

