//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SFDAMSeedFill : NSObject
{
}

+ (CDStruct_8aadf14b *)seedFillWithImage:(CDStruct_056e8d52 *)arg1 seedPoint:(struct CGPoint)arg2 context:(CDStruct_388a999f *)arg3 oldFill:(CDStruct_8aadf14b *)arg4 newFill:(CDStruct_8aadf14b *)arg5;

@end

