//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "__BKMacSelectionPopoverViewControllerAccessibility_super.h"

@class BKMacRolloverTableViewAccessibility;

@interface BKMacSelectionPopoverViewControllerAccessibility : __BKMacSelectionPopoverViewControllerAccessibility_super
{
}

+ (Class)bkaxBaseSafeCategoryClass;
+ (id)bkaxTargetClassName;
- (void)bkaxLoadAccessibilityInformation;
- (void)awakeFromNib;
@property(readonly, nonatomic) BKMacRolloverTableViewAccessibility *bkaxMoreTableView;
@property(readonly, nonatomic) BKMacRolloverTableViewAccessibility *bkaxMainTableView;

@end

