//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "__BKNSTextFieldCellAccessibility_super.h"

@class NSString;

@interface BKNSTextFieldCellAccessibility : __BKNSTextFieldCellAccessibility_super
{
}

+ (Class)bkaxBaseSafeCategoryClass;
+ (id)bkaxTargetClassName;
- (id)accessibilityAttributeValue:(id)arg1;
@property(retain, nonatomic, setter=bkaxSetValueDescription:) NSString *bkaxValueDescription;

@end

