//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BKPreferencesModule.h"

@class BKSecurePreferences, NSButton, NSTextField, NSXPCConnection, SFAuthorizationView;

@interface BKParentalPreferences : BKPreferencesModule
{
    NSButton *_disableBookstoreButton;
    NSButton *_restrictExplicitContentButton;
    NSTextField *_restrictExplicitContentExplanationField;
    SFAuthorizationView *_authorizationButton;
    struct AuthorizationOpaqueRef *_authorization;
    NSXPCConnection *_defaultsConnection;
    id <BKSecureUserDefaults> _secureUserDefaults;
    BKSecurePreferences *_securePreferences;
}

+ (id)userID;
@property(retain) BKSecurePreferences *securePreferences; // @synthesize securePreferences=_securePreferences;
@property(retain) id <BKSecureUserDefaults> secureUserDefaults; // @synthesize secureUserDefaults=_secureUserDefaults;
@property(retain) NSXPCConnection *defaultsConnection; // @synthesize defaultsConnection=_defaultsConnection;
- (void).cxx_destruct;
- (void)authorizationViewCreatedAuthorization:(id)arg1;
- (void)authorizationViewDidDeauthorize:(id)arg1;
- (void)authorizationViewDidAuthorize:(id)arg1;
- (void)restrictExplicitContentAction:(id)arg1;
- (void)disableBookstoreAction:(id)arg1;
- (void)updateControlsForAuthorizationState;
- (void)saveChanges;
- (BOOL)hasChangesPending;
- (BOOL)_needToCloseStore;
- (BOOL)isResizable;
- (void)awakeFromNib;
- (id)authBlobError:(id *)arg1;
- (void)_unloadXPCConnection;
- (void)_loadXPCConnection;
- (void)dealloc;
- (id)init;

@end

