//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSPreferences.h"

#import "BKPreferences.h"

@class BKPreferencesModule, NSString, NSToolbar;

@interface BKPreferences : NSPreferences <BKPreferences>
{
    BKPreferencesModule *_currentPreferencesModule;
    NSToolbar *_toolbar;
    unsigned long long _preferenceCount;
}

+ (void)initialize;
@property(nonatomic) unsigned long long preferenceCount; // @synthesize preferenceCount=_preferenceCount;
@property(nonatomic) NSToolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(nonatomic) BKPreferencesModule *currentPreferencesModule; // @synthesize currentPreferencesModule=_currentPreferencesModule;
- (void)p_ensureToolbarCentered;
- (void)toolbarWillAddItem:(id)arg1;
- (id)windowTitle;
- (void)applicationWillTerminate:(id)arg1;
- (BOOL)usesButtons;
- (void)moduleWillBeDisplayed:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

