//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "__BKToolbarAccessibility_super.h"

@interface BKToolbarAccessibility : __BKToolbarAccessibility_super
{
}

+ (Class)bkaxBaseSafeCategoryClass;
+ (id)bkaxTargetClassName;
- (void)bkaxDisableFullScreenAutohiding;
- (void)bkaxEnableFullScreenAutohiding;
- (void)bkaxToggleFullScreen;
- (void)bkaxUnloadAccessibilityInformation;
- (void)bkaxLoadAccessibilityInformation;
@property(nonatomic, setter=bkaxSetAutohidingDisabled:) BOOL bkaxIsAutohidingDisabled;

@end

