//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <FinderKit/FI_TViewController.h>

#import "NSAnimationDelegate.h"

@class FI_TBrowserContainerController, FI_TSidebarViewController, NSString, NSView;

__attribute__((visibility("hidden")))
@interface FI_TSidebarSplitterController : FI_TViewController <NSAnimationDelegate>
{
    NSView *_sidebarViewContainer;
    NSView *_browserViewContainer;
    FI_TBrowserContainerController *_containerController;
    FI_TSidebarViewController *_sidebarViewController;
    _Bool _windowIsResizing;
    _Bool _browserWidthIsDynamic;
    _Bool _animatingSidebar;
    _Bool _snapToOptimalPosition;
    _Bool _initialSizeDone;
    double _lastSplitterPosition;
    double _resizePosition;
}

@property(nonatomic) _Bool animatingSidebar; // @synthesize animatingSidebar=_animatingSidebar;
@property(nonatomic) double lastSplitterPosition; // @synthesize lastSplitterPosition=_lastSplitterPosition;
@property(nonatomic) _Bool browserWidthIsDynamic; // @synthesize browserWidthIsDynamic=_browserWidthIsDynamic;
@property(readonly, nonatomic) FI_TBrowserContainerController *browserContainerController; // @synthesize browserContainerController=_containerController;
- (void)splitViewDidResizeSubviews:(id)arg1;
- (struct CGRect)splitView:(id)arg1 effectiveRect:(struct CGRect)arg2 forDrawnRect:(struct CGRect)arg3 ofDividerAtIndex:(long long)arg4;
- (_Bool)splitView:(id)arg1 shouldHideDividerAtIndex:(long long)arg2;
- (double)splitView:(id)arg1 constrainSplitPosition:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMaxCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMinCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (void)splitView:(id)arg1 resizeSubviewsWithOldSize:(struct CGSize)arg2;
- (_Bool)splitView:(id)arg1 canCollapseSubview:(id)arg2;
- (void)resizeEnd;
- (void)resizeStart;
- (void)animateSidebarToggle:(_Bool)arg1;
- (void)addSidebarIfNecessary;
- (void)sidebarToggleForAppCentric:(_Bool)arg1 newSplitterPosition:(double)arg2 animate:(_Bool)arg3;
- (void)initialResize;
- (void)configureSidebar:(_Bool)arg1 setSplitterPosition:(_Bool)arg2;
- (_Bool)sidebarIsVisible;
- (id)sidebarViewController;
- (void)setSplitterPosition:(double)arg1 snapToOptimalPosition:(_Bool)arg2;
- (void)setSplitterPosition:(double)arg1;
- (double)splitterPosition;
- (struct CGSize)idealViewSize;
- (struct CGSize)minimumViewSize;
- (id)browserViewContainer;
- (id)sidebarViewContainer;
- (id)sidebarSplitView;
- (void)aboutToTearDown;
- (id)initWithFrame:(struct CGRect)arg1 andParent:(id)arg2;
- (id)nibName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

