//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <FinderKit/FI_TTaskErrorOrConflictViewController.h>

__attribute__((visibility("hidden")))
@interface FI_TSkipKeepBothReplaceConflictViewController : FI_TTaskErrorOrConflictViewController
{
    _Bool _showSkipButton;
    _Bool _showKeepBothByDefault;
    _Bool _canSkip;
}

- (void)leftButtonPressed:(id)arg1;
- (void)setCanSkip:(_Bool)arg1;
- (void)setOptionKeyDown:(_Bool)arg1;
- (void)setTask:(struct TTask *)arg1;
- (void)setDefaultLeftButton;
- (void)setShowSkipButton:(_Bool)arg1;
- (_Bool)skipButtonShowing;
- (void)viewLoaded;
- (void)initCommon;

@end

