//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <FinderKit/FI_TViewController.h>

@class FI_TButton, FI_TImageView, NSImage, NSString, TProgressIndicator;

__attribute__((visibility("hidden")))
@interface FI_TStandardStatusViewController : FI_TViewController
{
    TProgressIndicator *_progress;
    FI_TButton *_cancelButton;
    FI_TImageView *_imageView;
    struct TNSRef<FI_TTargetActionFunctor *> _cancelBtnFunctorAdapter;
    struct TNSRef<NSTrackingArea *> _cancelBtnTrackingArea;
    struct TNotificationCenterObserver _cancelBtnUpdateTrackingAreaObserver;
    _Bool _isCancelButtonEnabled;
    _Bool _isCancelButtonVisible;
    struct TString _titleString;
    struct TString _messageString;
    struct TString _cancelMessageString;
    struct TNSRef<NSImage *> _image;
    _Bool _indeterminate;
    double _percentComplete;
    _Bool _shouldDisplayCancelString;
}

+ (id)keyPathsForValuesAffectingSubString;
@property _Bool shouldDisplayCancelString; // @synthesize shouldDisplayCancelString=_shouldDisplayCancelString;
@property(getter=isCancelButtonVisible) _Bool cancelButtonVisible; // @synthesize cancelButtonVisible=_isCancelButtonVisible;
@property(getter=isCancelButtonEnabled) _Bool cancelButtonEnabled; // @synthesize cancelButtonEnabled=_isCancelButtonEnabled;
@property(nonatomic) _Bool indeterminate; // @synthesize indeterminate=_indeterminate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setCancelButtonFunctor:(const function_f9feaa7d *)arg1 validatorID:(long long)arg2;
- (void)cancelButtonPressed:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)updateTrackingAreas;
- (void)setIcon:(const struct TIconRef *)arg1;
@property(copy, nonatomic) NSImage *image; // @dynamic image;
@property(readonly, nonatomic) struct CGSize imageViewSize; // @dynamic imageViewSize;
@property(copy, nonatomic) NSString *cancelMessageString; // @dynamic cancelMessageString;
@property(copy, nonatomic) NSString *messageString; // @dynamic messageString;
@property(readonly, copy, nonatomic) NSString *subString; // @dynamic subString;
@property(copy, nonatomic) NSString *titleString; // @dynamic titleString;
@property(nonatomic) double percentComplete;
- (void)viewLoaded;
- (void)aboutToTearDown;
- (void)initCommon;
- (id)initWithStatusKind:(int)arg1;
- (id)init;

@end

