//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <FinderKit/FI_TTaskErrorViewController.h>

__attribute__((visibility("hidden")))
@interface FI_TTaskErrorOrConflictViewController : FI_TTaskErrorViewController
{
    unsigned int _leftResolution;
    unsigned int _middleResolution;
    unsigned int _rightResolution;
    _Bool _optionKeyDown;
    _Bool _isShowingConflict;
    struct TNotificationCenterObserver _appFlagsDidChangeObserver;
}

@property(nonatomic) _Bool isShowingConflict; // @synthesize isShowingConflict=_isShowingConflict;
@property(nonatomic) _Bool optionKeyDown; // @synthesize optionKeyDown=_optionKeyDown;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)buttonHit:(unsigned int)arg1;
- (void)rightButtonPressed:(id)arg1;
- (void)middleButtonPressed:(id)arg1;
- (void)leftButtonPressed:(id)arg1;
- (void)setResolutionsForKind:(int)arg1;
- (void)setLeftResolution:(unsigned int)arg1;
- (void)setCanSkip:(_Bool)arg1;
- (void)initCommon;
- (id)initWithViewKind:(int)arg1;
- (void)flagsDidChange:(id)arg1;

@end

