//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <FinderKit/FIContainerController.h>

__attribute__((visibility("hidden")))
@interface FIAppCentricContainerController : FIContainerController
{
}

+ (void)initialize;
- (void)dealloc;
- (void)appResignedActive;
- (void)searchFieldCancel;
- (void)updateViewLayout:(_Bool)arg1;
- (void)configureAccessoryViews:(id)arg1;
- (void)setViewStyle:(id)arg1;
- (_Bool)allowsNewDocumentButton;
- (_Bool)uiAllowsRenamingNode:(const struct TFENode *)arg1;
- (_Bool)canShare;
- (unsigned int)defaultSearchScope;
- (_Bool)showScopeBar;
- (_Bool)isAppCentric;
- (id)containingOpenPanel;
- (id)acGutsController;

@end

