//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class TBrowserContainerController;

@protocol BrowserContainerTargeting
- (void)containerForgetSpringState:(TBrowserContainerController *)arg1;
- (void)container:(TBrowserContainerController *)arg1 adjustProposedTargetPath:(struct TFENodeVector *)arg2;
- (void)containerTargetDidChange:(TBrowserContainerController *)arg1;
- (void)containerTargetWillChange:(TBrowserContainerController *)arg1;
- (void)containerViewStyleChanged:(TBrowserContainerController *)arg1;
@end

