//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableDictionary.h"

@interface NSMutableDictionary (NSMutableDictionaryAddtions)
- (void)setDictionaryFE:(id)arg1 forKey:(id)arg2;
- (void)setArrayFE:(id)arg1 forKey:(id)arg2;
- (void)setDataFE:(id)arg1 forKey:(id)arg2;
- (void)setNumberFE:(id)arg1 forKey:(id)arg2;
- (void)setStringFE:(id)arg1 forKey:(id)arg2;
- (void)setRectFE:(const struct CGRect *)arg1 forKey:(id)arg2;
- (void)setPointFE:(const struct CGPoint *)arg1 forKey:(id)arg2;
- (void)setSizeFE:(const struct CGSize *)arg1 forKey:(id)arg2;
- (void)setFourCharCodeFE:(unsigned int)arg1 forKey:(id)arg2;
- (void)setSInt64FE:(long long)arg1 forKey:(id)arg2;
- (void)setIntegerFE:(long long)arg1 forKey:(id)arg2;
- (void)setDoubleFE:(double)arg1 forKey:(id)arg2;
- (void)setCGFloatFE:(double)arg1 forKey:(id)arg2;
- (void)setBoolFE:(_Bool)arg1 forKey:(id)arg2;
@end

