//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TScrollView.h"

@interface TAutoResizingScrollView : TScrollView
{
}

@property _Bool autoResizeHeight; // @dynamic autoResizeHeight;
@property _Bool autoResizeWidth; // @dynamic autoResizeWidth;
- (void)initCommon;

@end

