//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableRowView.h"

@class TViewBasedBrowserTableColumnViewController;

@interface TBaseColumnGroupRowView : NSTableRowView
{
    struct TFENode _node;
    TViewBasedBrowserTableColumnViewController *_tableViewController;
}

@property(nonatomic) TViewBasedBrowserTableColumnViewController *tableViewController; // @synthesize tableViewController=_tableViewController;
@property(nonatomic) struct TFENode node; // @synthesize node=_node;
- (id).cxx_construct;
- (void).cxx_destruct;

@end

