//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBulkRenameFormatterController.h"

@class NSPopUpButton, NSString, NSTextField;

@interface TBulkRenameMakeSequentialController : TBulkRenameFormatterController
{
    NSPopUpButton *_nameFormatBtn;
    NSPopUpButton *_whereBtn;
    NSTextField *_customNameFld;
    NSTextField *_startIndexFld;
    NSString *_customName;
    struct TNotificationCenterObserver _customNameTextDidChangeObserver;
    struct TNotificationCenterObserver _startIndexTextDidChangeObserver;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)reformat:(id)arg1 row:(unsigned long long)arg2;
- (id)padIndex:(unsigned long long)arg1 padAmount:(unsigned long long)arg2;
- (id)timestamp:(id)arg1;
- (void)whereChanged:(id)arg1;
- (void)nameFormatChanged:(id)arg1;
- (void)updateUI;
- (long long)customIndex;
- (_Bool)resetCounterForEachFile;
- (_Bool)allowRename;
- (id)displayName;
- (int)formatterType;
- (void)aboutToTearDown;
- (void)viewLoaded;

@end

