//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TInfoWindowViewController.h"

@class TColumnPreviewPropertyTaggingTokenFieldController, TColumnPreviewSpotlightMetaDataController, TPropertyColumnPreviewCreationDateController, TPropertyColumnPreviewKindAndSizeController, TPropertyColumnPreviewLastOpenedDateController, TPropertyColumnPreviewModificationDateController, TPropertyNameController, TPropertyShortVersionController, TSpacerView;

@interface TColumnPreviewInfoViewController : TInfoWindowViewController
{
    TPropertyNameController *_nameController;
    TPropertyColumnPreviewKindAndSizeController *_kindAndSizeController;
    TPropertyColumnPreviewCreationDateController *_createDateController;
    TPropertyColumnPreviewModificationDateController *_modDateController;
    TPropertyColumnPreviewLastOpenedDateController *_lastOpenedDateController;
    TSpacerView *_versionSpacerView;
    TPropertyShortVersionController *_versionController;
    TSpacerView *_spotlightMetaDataSpacerView;
    TColumnPreviewSpotlightMetaDataController *_spotightMetaDataController;
    TSpacerView *_taggingSpacerView;
    TColumnPreviewPropertyTaggingTokenFieldController *_taggingController;
    struct TNSRef<NSArray *> _titleFlds;
    double _leftMargin;
    double _titleAndTextGap;
    double _rightMargin;
    double _viewWidthCache;
    struct TNotificationCenterObserver _viewFrameChangedObserver;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)adjustTextFieldWidths;
- (void)nodeMDAttributeChanged:(const struct TFENode *)arg1 attributes:(id)arg2 isDisplayAttributes:(_Bool)arg3;
- (void)bulkNodesChanged:(const struct TCoalescedNodesChangedMap *)arg1;
- (void)viewFrameChanged;
- (void)refresh;
- (void)setNodes:(const struct TFENodeVector *)arg1;
- (void)setSubviewsHidden:(_Bool)arg1;
- (_Bool)expandedDefaultValue;
- (_Bool)expanded;
- (void)configureMinRowCount:(double)arg1 maxRowCount:(double)arg2 resizable:(_Bool)arg3;
- (unsigned int)notificationOptionsForNodes:(const struct TFENodeVector *)arg1;
- (void)aboutToTearDown;
- (void)loadValueControllers;
- (void)viewLoaded;

@end

