//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TDateTextField.h"

#import "TTextWithTitleFieldImplProtocol.h"

@class NSString, TTitleField;

@interface TDateTextWithTitleField : TDateTextField <TTextWithTitleFieldImplProtocol>
{
    struct TNSRef<TTextWithTitleFieldImpl *> _implementation;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (double)calcHeightToFitOfTextFieldOnly:(struct CGSize)arg1;
- (double)calcHeightToFit:(struct CGSize)arg1;
@property TTitleField *titleFld; // @dynamic titleFld;
- (void)initCommon;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

