//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TTextField.h"

@interface TEditTextField : TTextField
{
    unsigned long long _maxChars;
}

@property(nonatomic) unsigned long long maxChars; // @synthesize maxChars=_maxChars;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)applySettingsFrom:(id)arg1;
- (void)initCommon;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

