//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TInfoWindowViewController.h"

@class TPropertyCalculateContentSizeButtonController, TPropertyContentSizeController, TPropertyDeviceController, TPropertyMediaCapacityController;

@interface TInfoWindowBurningViewController : TInfoWindowViewController
{
    TPropertyDeviceController *_deviceController;
    TPropertyMediaCapacityController *_mediaCapacityController;
    TPropertyContentSizeController *_contentSizeController;
    TPropertyCalculateContentSizeButtonController *_calculateButtonController;
}

+ (id)controller;
- (unsigned int)scriptingID;
- (void)loadValueControllers;
- (id)expandedPrefKey;
- (double)bottomMargin;

@end

