//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableCellView.h"

@interface TListHeaderCellView : NSTableCellView
{
    struct TNSRef<TImageView *> _tagImageView;
    struct TNSRef<TUpdateLayerView *> _separatorView;
    double _rightTextMargin;
    double _leftTextMargin;
    _Bool _isSortAscending;
}

@property(nonatomic, getter=isSortAscending) _Bool sortAscending; // @synthesize sortAscending=_isSortAscending;
@property(nonatomic) double leftTextMargin; // @synthesize leftTextMargin=_leftTextMargin;
@property(nonatomic) double rightTextMargin; // @synthesize rightTextMargin=_rightTextMargin;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)layout;
- (_Bool)hitTestInSeparator:(const struct CGPoint *)arg1;
@property(nonatomic, getter=isSeparatorHidden) _Bool separatorHidden; // @dynamic separatorHidden;
@property(nonatomic, getter=isSortTriangleHidden) _Bool sortTriangleHidden; // @dynamic sortTriangleHidden;
- (id)sortTriangleView;
- (void)setTagImage:(id)arg1;
- (void)cloneFrom:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

