//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TViewController.h"

@class NSString, TTextField;

@interface TMeetingRoomErrorViewController : TViewController
{
    TTextField *_errorTextFld;
    struct TNSRef<TLayoutBinder *> _layoutBinder;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)viewDidMoveToSuperview;
@property(retain, nonatomic) NSString *errorTextStr; // @dynamic errorTextStr;
- (void)dealloc;
- (void)viewLoaded;

@end

