//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TViewController.h"

@class TPopoverController;

@interface TPopoverContentViewController : TViewController
{
    TPopoverController *_popoverController;
}

- (void)keyDown:(id)arg1;
- (void)performClose:(id)arg1;
- (id)initWithPopover:(id)arg1;

@end

