//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TChooseFolderController.h"

@class TGeneralPaneController;

@interface TSelectLocationController : TChooseFolderController
{
    TGeneralPaneController *_parent;
}

- (_Bool)shouldEnableNode:(const struct TFENode *)arg1;
- (int)defaultOptions;
- (_Bool)validateNode:(const struct TFENode *)arg1;
- (void)setParent:(id)arg1;

@end

