//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextField.h"

@class TTagsPrefTableView;

@interface TTagsPrefTextField : NSTextField
{
    TTagsPrefTableView *_tableView;
    _Bool _becomingFirstResponder;
}

@property(nonatomic) TTagsPrefTableView *tableView; // @synthesize tableView=_tableView;
- (BOOL)becomeFirstResponder;
- (BOOL)acceptsFirstResponder;

@end

