//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BookletResourceLoadDelegate : NSObject
{
    unsigned long long mStoreID;
    unsigned long long mPersistentID;
    unsigned short mXID[256];
}

- (id)webView:(id)arg1 resource:(id)arg2 willSendRequest:(id)arg3 redirectResponse:(id)arg4 fromDataSource:(id)arg5;
- (id)initWithTrackInfo:(struct TrackInfo *)arg1;
- (id)initWithPlaylistItem:(struct PlaylistItem *)arg1;

@end

