//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "CRCodeRedeemerViewDelegate.h"

@class CRCodeRedeemerView, NSDictionary, WebView;

@interface CodeRedeemer : NSView <CRCodeRedeemerViewDelegate>
{
    CRCodeRedeemerView *_crView;
    WebView *_webView;
    NSDictionary *_arguments;
    struct OpaqueJSContext *_webViewContext;
    _Bool hackForCoreRecognition;
}

+ (void)showCameraRedeemStatus:(id)arg1 color:(struct CGColor *)arg2 duration:(double)arg3 style:(int)arg4;
+ (void)setCameraRedeemFadeDuration:(float)arg1;
+ (void)restartCameraRedeem;
+ (void)shutdownCameraRedeem;
+ (void)stopCameraRedeem;
+ (void)fadeCameraRedeemIn;
+ (void)fadeCameraRedeemOut;
+ (BOOL)isKeyExcludedFromWebScript:(const char *)arg1;
+ (BOOL)isSelectorExcludedFromWebScript:(SEL)arg1;
+ (id)plugInViewWithArguments:(id)arg1;
+ (_Bool)supportsAutoCodeRedeemer;
@property(copy, nonatomic) NSDictionary *arguments; // @synthesize arguments=_arguments;
- (oneway void)release;
- (id)retain;
- (void)notifyCodeRedeemer:(id)arg1;
- (void)fadeIn;
- (void)codeRedeemerView:(id)arg1 sendCodesViaJavaScript:(id)arg2 forWillRecognize:(_Bool)arg3;
- (void)createCameraRedeemViewWithFrame:(struct CGRect)arg1;
- (void)codeRedeemerViewCameraDidStart:(id)arg1;
- (void)codeRedeemerViewDidFindBox:(id)arg1;
- (void)codeRedeemerViewDidFadeStatus:(id)arg1;
- (void)codeRedeemerViewWillFadeStatus:(id)arg1;
- (void)codeRedeemerView:(id)arg1 didFailWithError:(id)arg2;
- (void)codeRedeemerView:(id)arg1 didSucceedWithCodes:(id)arg2;
- (void)codeRedeemerView:(id)arg1 willRecognizeCodes:(id)arg2;
- (id)objectForWebScript;
- (id)attributeKeys;
- (void)setFrame:(struct CGRect)arg1;
- (void)setWebView:(id)arg1;
- (void)webPlugInSetIsSelected:(BOOL)arg1;
- (void)webPlugInDestroy;
- (void)webPlugInStop;
- (void)webPlugInStart;
- (void)webPlugInInitialize;
- (void)dealloc;
- (id)init;

@end

