//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSAnimation.h"

@class NSView;

@interface FadeAnimation : NSAnimation
{
    NSView *_viewToFade;
    _Bool _fadingIn;
}

- (void)setCurrentProgress:(float)arg1;
- (void)setFadeIn:(_Bool)arg1;
- (void)setView:(id)arg1;

@end

