//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ITPopupButtonNativeTarget : NSObject
{
    struct weak_ptr<ITPopupButtonNative> mPopupButtonNative;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setITPopupButtonNative:(shared_ptr_b05016cb)arg1;
- (void)handlePopupButton:(id)arg1;

@end

