//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSColor.h"

@interface NSColor (ITColorAdditions)
+ (id)colorWithITColor:(const struct ITColor *)arg1;
+ (id)colorWithRGBColor:(const struct RGBColor *)arg1;
- (struct RGBColor)RGBColor;
- (struct ITColor)ITColor;
@end

