//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSPredicateEditorRowTemplate.h"

@class NSTextField;

@interface TimeRowTemplate : NSPredicateEditorRowTemplate
{
    NSTextField *_textField;
}

@property(readonly) NSTextField *textField; // @synthesize textField=_textField;
- (double)matchForPredicate:(id)arg1;
- (id)templateViews;

@end

