//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MapsDebugTableRow.h"

__attribute__((visibility("hidden")))
@interface MapsDebugSwitchTableRow : MapsDebugTableRow
{
    CDUnknownBlockType _set;
    CDUnknownBlockType _get;
}

@property(copy, nonatomic) CDUnknownBlockType get; // @synthesize get=_get;
@property(copy, nonatomic) CDUnknownBlockType set; // @synthesize set=_set;
- (void).cxx_destruct;
- (void)_checkboxDidChange;
- (void)configureCell:(id)arg1;
- (id)_checkboxForCell:(id)arg1;

@end

