//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MKLabelMarker.h"

@class NVPlace;

@interface MKLabelMarker (Navigo)
+ (id)keyPathsForValuesAffectingSubtitle;
- (BOOL)resolveWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)setPlace:(id)arg1;
@property(readonly) NVPlace *place;
- (id)subtitle;
@end

