//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MKMapView.h"

@class NSArray;

@interface MKMapView (NVReportAProblem)
- (void)_searchForQuery:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)_reportAProblemDropPinAtCoordinate:(CDStruct_c3b9c2ee)arg1;
@property(readonly, nonatomic) NSArray *displayedPins;
@end

