//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MKMapService.h"

@interface MKMapService (Maps)
- (void)submitUsageAction:(int)arg1 includeStarkInfo:(BOOL)arg2 mapItem:(id)arg3 timestamp:(double)arg4 resultIndex:(int)arg5 mapRegion:(id)arg6 zoomLevel:(double)arg7;
- (void)submitUsageAction:(int)arg1 mapRegion:(id)arg2 zoomLevel:(double)arg3 includeStarkInfo:(BOOL)arg4;
- (void)submitUsageAction:(int)arg1 includeStarkInfo:(BOOL)arg2;
- (id)ticketForQuerySearch:(id)arg1 source:(int)arg2;
- (id)ticketForSearchQuery:(id)arg1 completionItem:(id)arg2 source:(int)arg3 mapRegion:(id)arg4;
- (id)_ticketForSearchQuery:(id)arg1 completionItem:(id)arg2 traits:(id)arg3;
- (id)ticketForReverseGeocodeDroppedPinCoordinate:(CDStruct_c3b9c2ee)arg1;
- (id)ticketForReverseGeocodeCoordinate:(CDStruct_c3b9c2ee)arg1 includeETA:(BOOL)arg2;
- (id)ticketForForwardGeocodeAddressString:(id)arg1 source:(int)arg2;
- (id)ticketForForwardGeocodeAddress:(id)arg1 source:(int)arg2;
- (id)ticketForForwardGeocodeAddress:(id)arg1 source:(int)arg2 mapRegion:(id)arg3;
- (id)ticketForMUIDs:(id)arg1 includeETA:(BOOL)arg2 mapRegion:(id)arg3;
- (id)mapsDefaultTraitsForAction:(int)arg1 includeStarkInfo:(BOOL)arg2;
- (id)mapsDefaultTraitsForSource:(int)arg1;
- (id)mapsDefaultTraitsForMapRegion:(id)arg1;
- (id)mapsDefaultTraitsForMapRegion:(id)arg1 source:(int)arg2;
- (id)mapsDefaultTraits;
@end

