//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindow.h"

@class NSView;

__attribute__((visibility("hidden")))
@interface NVNavWindow : NSWindow
{
    NSView *_sideView;
}

@property __weak NSView *sideView; // @synthesize sideView=_sideView;
- (void).cxx_destruct;
- (id)accessibilityChildren;
- (id)initWithContentRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2 backing:(unsigned long long)arg3 defer:(BOOL)arg4;

@end

