//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface NVPrintUtils : NSObject
{
}

+ (struct CGSize)snapshotSize;
+ (void)fetchN:(unsigned long long)arg1 snapshotsWithGeoBounds:(CDStruct_90e2a262 *)arg2 sizes:(struct CGSize *)arg3 completion:(CDUnknownBlockType)arg4 errorHandler:(CDUnknownBlockType)arg5;
+ (void)drawLabel:(id)arg1 inRect:(struct CGRect)arg2;

@end

