//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MKMapSnapshot, MKMapSnapshotOptions, MKMapSnapshotter, NSObject<OS_dispatch_semaphore>;

__attribute__((visibility("hidden")))
@interface NVPrintSnapshotJob : NSObject
{
    NSObject<OS_dispatch_semaphore> *is_fetched;
    MKMapSnapshotter *_snapshotter;
    BOOL _jobDone;
    MKMapSnapshotOptions *_options;
    MKMapSnapshot *_mapSnapshot;
    unsigned long long _timeoutInSeconds;
}

@property(nonatomic) unsigned long long timeoutInSeconds; // @synthesize timeoutInSeconds=_timeoutInSeconds;
@property(retain, nonatomic) MKMapSnapshot *mapSnapshot; // @synthesize mapSnapshot=_mapSnapshot;
- (void).cxx_destruct;
- (void)waitForJobDone;
- (void)startJob:(CDUnknownBlockType)arg1;
- (id)initWithSnapshotOptions:(id)arg1;

@end

