//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSImageView.h"

@class NVRouteStep;

__attribute__((visibility("hidden")))
@interface NVPrintSimpleBorderImageView : NSImageView
{
    NVRouteStep *_step;
}

@property(retain, nonatomic) NVRouteStep *step; // @synthesize step=_step;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;

@end

