//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class NSButton, NSLayoutConstraint, NSTextField, NSView, NVMultilineCheckboxButton, NVMultilineCheckboxLabel, RAPSubmissionOutcome;

__attribute__((visibility("hidden")))
@interface NVRAPAcknowledgmentViewController : NSViewController
{
    RAPSubmissionOutcome *_outcome;
    CDUnknownBlockType _completion;
    NSTextField *_thankYouTitleLabel;
    NSTextField *_thankYouMessageLabel;
    NSButton *_doneButton;
    NVMultilineCheckboxButton *_checkbox;
    NVMultilineCheckboxLabel *_checkboxLabel;
    NSView *_collapsibleView;
    NSLayoutConstraint *_checkboxToDoneButtonSpacingConstraint;
}

- (void).cxx_destruct;
- (void)_done:(id)arg1;
- (void)viewDidLoad;
- (id)initWithSubmissionOutcome:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

