//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GEOMapRegion, NSDate, NSString;

__attribute__((visibility("hidden")))
@interface NVSearchManagerContext : NSObject
{
    BOOL allowLocationFix;
    int source;
    GEOMapRegion *mapRegion;
    NSDate *mapViewportChangeDate;
    NSDate *mapEnteredForegroundDate;
    NSString *suggestionsPrefix;
}

@property BOOL allowLocationFix; // @synthesize allowLocationFix;
@property(retain, nonatomic) NSString *suggestionsPrefix; // @synthesize suggestionsPrefix;
@property(retain, nonatomic) NSDate *mapEnteredForegroundDate; // @synthesize mapEnteredForegroundDate;
@property(retain, nonatomic) NSDate *mapViewportChangeDate; // @synthesize mapViewportChangeDate;
@property int source; // @synthesize source;
@property(retain, nonatomic) GEOMapRegion *mapRegion; // @synthesize mapRegion;
- (void).cxx_destruct;
- (void)setMapRect:(CDStruct_90e2a262)arg1;
- (id)initWithMapRect:(CDStruct_90e2a262)arg1 source:(int)arg2 mapViewportChangeDate:(id)arg3 mapEnteredForegroundDate:(id)arg4 allowLocationFix:(BOOL)arg5;
- (id)initWithMapRegion:(id)arg1 source:(int)arg2 mapViewportChangeDate:(id)arg3 mapEnteredForegroundDate:(id)arg4 allowLocationFix:(BOOL)arg5;

@end

