//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NVDropTargetSearchField.h"

#import "NSPopoverDelegate.h"
#import "NSTextFieldDelegate.h"
#import "NVRecentsViewControllerDelegate.h"

@class CNContactPicker, NSString, NVRecentsViewController;

__attribute__((visibility("hidden")))
@interface NVSearchField : NVDropTargetSearchField <NSPopoverDelegate, NVRecentsViewControllerDelegate, NSTextFieldDelegate>
{
    unsigned long long _displayType;
    NVRecentsViewController *_recentsPopover;
    CNContactPicker *_bookmarksPopover;
    BOOL _showingPopover;
    BOOL _closingPopover;
}

@property(nonatomic) unsigned long long displayType; // @synthesize displayType=_displayType;
- (void).cxx_destruct;
- (BOOL)control:(id)arg1 textView:(id)arg2 doCommandBySelector:(SEL)arg3;
- (void)recentsViewControllerShouldMakeSearchFieldFirstResponder:(id)arg1;
- (void)recentsViewController:(id)arg1 selectedPlaceOrTrip:(id)arg2;
- (void)recentsViewControllerSelectedSavedLocations:(id)arg1;
- (void)popoverWillClose:(id)arg1;
- (BOOL)popoverShouldClose:(id)arg1;
- (BOOL)popoverShouldDetach:(id)arg1;
- (void)closePopover;
- (void)showPopoverIfNecessary;
- (void)updatePopover;
- (BOOL)isViewOrSubviewFirstResponder:(id)arg1;
- (id)bookmarksPopover;
- (id)recentsPopover;
- (BOOL)becomeFirstResponder;
- (void)textDidChange:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (void)viewWillMoveToWindow:(id)arg1;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

