//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AMSItemSizeInfo.h"

@class AMSDeviceLayer;

@interface AMSDeviceLayerSizeInfo : AMSItemSizeInfo
{
    AMSDeviceLayer *layer;
}

@property AMSDeviceLayer *layer; // @synthesize layer;
- (BOOL)canShrink;
- (double)minSize;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithDeviceLayer:(id)arg1;

@end

