//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSBundle, NSImage, NSString;

@interface SPInfoDisplay : NSObject
{
    NSBundle *_bundle;
    int _displayID;
    unsigned int _ioService;
    NSImage *_displayIcon;
    NSString *_displayName;
    NSString *_model;
    NSString *_gfxName;
    NSString *_gfxMemory;
    NSString *_gfxPort;
    BOOL _isMainScreen;
    BOOL _isBuiltIn;
    BOOL _isApple;
    BOOL _isRetina;
    BOOL _isTV;
    unsigned int _panelWidth;
    unsigned int _panelHeight;
    unsigned int _horzDPI;
    unsigned int _vertDPI;
    unsigned long long _serialNumber;
    unsigned long long _sortHash;
    BOOL _isHiDPI;
    NSString *_gfxDisplayName;
}

@property(readonly) unsigned long long serialNumber; // @synthesize serialNumber=_serialNumber;
@property BOOL isRetina; // @synthesize isRetina=_isRetina;
@property BOOL isHiDPI; // @synthesize isHiDPI=_isHiDPI;
@property(readonly) NSString *gfxDisplayName; // @synthesize gfxDisplayName=_gfxDisplayName;
@property BOOL isTV; // @synthesize isTV=_isTV;
@property BOOL isApple; // @synthesize isApple=_isApple;
@property BOOL isBuiltIn; // @synthesize isBuiltIn=_isBuiltIn;
@property BOOL isMainScreen; // @synthesize isMainScreen=_isMainScreen;
@property int displayID; // @synthesize displayID=_displayID;
@property(readonly) NSString *modelNumber;
@property(readonly) NSString *resolutionString;
@property(readonly) unsigned long long sortHash;
- (void)refreshDisplayInfo;
- (id)localizedString:(id)arg1;
@property(readonly) NSString *displayName;
@property(readonly) NSImage *image;
- (void)dealloc;
- (id)initWithCGSDisplayID:(int)arg1;
- (id)bundle;

@end

