//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SPDocument, SPInfoDisplayList, SPInfoMacVariant, SPInfoMemory, SPInfoSystem;

@interface SPInfoData : NSObject
{
    SPDocument *_spDoc;
    SPInfoSystem *_systemInfo;
    SPInfoMemory *_memoryInfo;
    SPInfoMacVariant *_variantInfo;
    SPInfoDisplayList *_displaysInfo;
}

+ (id)sharedData;
@property(readonly) SPDocument *spDocument; // @synthesize spDocument=_spDoc;
- (void)openMonitorManualURL:(id)arg1;
- (void)openMemoryHelpURL;
- (id)opticalInfo;
- (id)disksInfo;
- (void)buyAppleCare;
- (void)openServiceURL;
- (void)openWarrantyURL;
- (void)openOSHelp;
- (void)openOSManualURL;
- (void)openOSSupportURL;
- (void)openSpecsURL;
- (void)openManualURL;
- (void)openSupportURL;
@property(readonly) NSString *macVariant;
- (void)setDisplaysInfoChanged;
@property(readonly) SPInfoDisplayList *displaysInfo;
@property(readonly) SPInfoMacVariant *variantInfo;
@property(readonly) SPInfoMemory *memoryInfo;
@property(readonly) SPInfoSystem *systemInfo;
- (void)dealloc;
- (id)initWithDocument:(id)arg1;

@end

