//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSString;

@interface SPInfoMemory : NSObject
{
    NSMutableArray *_modules;
    BOOL _usesECC;
    BOOL _hasUpgradeableMemory;
    unsigned long long _totalSlots;
    unsigned long long _unusedSlots;
}

@property(readonly) BOOL hasUpgradeableMemory; // @synthesize hasUpgradeableMemory=_hasUpgradeableMemory;
@property(readonly) NSArray *modules; // @synthesize modules=_modules;
@property(readonly) unsigned long long unusedSlots; // @synthesize unusedSlots=_unusedSlots;
@property(readonly) unsigned long long totalSlots; // @synthesize totalSlots=_totalSlots;
@property(readonly) BOOL usesECC; // @synthesize usesECC=_usesECC;
@property(readonly) NSString *dimmType;
- (id)initWithDocument:(id)arg1;

@end

