//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class UAAlertController;

@protocol UAAlertControllerDelegate
- (void)volumeUnmountedSheetClosed;
- (void)confirmationSheetButtonPressed:(long long)arg1;
- (void)alert:(UAAlertController *)arg1 buttonPressed:(long long)arg2;
@end

