//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol BKBookDownloadController <NSObject>
@property(nonatomic) BOOL explicitContentRestricted;
- (void)restartDownloadForAssetID:(NSString *)arg1;
- (void)cancelDownloadForAssetID:(NSString *)arg1;
- (void)resumeDownloadForAssetID:(NSString *)arg1;
- (void)pauseDownloadForAssetID:(NSString *)arg1;
- (void)updateDownloadStatus;
@end

