//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSEvent, NSMenu;

@protocol BKMacHighlightViewDelegate <NSObject>

@optional
- (NSMenu *)highlightView:(id <BKMacHighlightView>)arg1 menuForEvent:(NSEvent *)arg2;
- (void)highlightViewWillBecomeFirstResponder:(id <BKMacHighlightView>)arg1;
@end

