//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BKMarginNoteSideLayoutControllerView, NSArray;

@interface BKMarginNoteSideLayoutController : NSObject
{
    int _side;
    NSArray *_items;
    BOOL _invalidatedViewScale;
    BOOL _invalidatedWidth;
    double _height;
    double _viewScale;
    double _width;
    BKMarginNoteSideLayoutControllerView *_view;
}

@property(readonly, nonatomic) BKMarginNoteSideLayoutControllerView *view; // @synthesize view=_view;
@property(nonatomic) double width; // @synthesize width=_width;
@property(nonatomic) double viewScale; // @synthesize viewScale=_viewScale;
- (void).cxx_destruct;
- (void)validateLayout;
- (void)updateWithItems:(id)arg1;
- (double)p_moveItem:(id)arg1 upByDistance:(double)arg2 items:(id)arg3;
- (void)p_positionItems:(id)arg1;
- (void)p_positionItems;
- (BOOL)p_truncateItems:(id)arg1;
- (void)p_untruncateItems:(id)arg1;
- (double)p_totalHeightUserForItems:(id)arg1;
- (id)p_collapseItemsIntoStacks:(id)arg1;
- (id)p_collapseItemsIntoSingleStack:(id)arg1;
- (id)p_collapseAdjacentStacks:(id)arg1;
- (id)p_collapseSameLineItems:(id)arg1;
- (void)p_resizeItemsToWidth;
- (void)p_resizeItemToWidth:(id)arg1;
- (id)initWithView:(id)arg1 side:(int)arg2 viewScale:(double)arg3 width:(double)arg4;

@end

