//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BKPageCurlDelegate.h"

@class NSMutableArray;

@interface BKPageCurlManager : NSObject <BKPageCurlDelegate>
{
    NSMutableArray *_queue;
    struct {
        unsigned int respondsToDelay:1;
        unsigned int respondsToDuration:1;
        unsigned int respondsToStabilization:1;
        unsigned int respondsToDidBeginCurl:1;
        unsigned int respondsToRemovesViews:1;
        unsigned int respondsToKillLastCurl:1;
        unsigned int respondsToWillCancelCurl:1;
    } _delegateFlags;
    BOOL _nightMode;
    int _spineLocation;
    id <BKPageCurlManagerDelegate> _delegate;
    struct CGColor *_pageColor;
    struct CGColor *_backColor;
}

@property(nonatomic) BOOL nightMode; // @synthesize nightMode=_nightMode;
@property(retain, nonatomic) struct CGColor *backColor; // @synthesize backColor=_backColor;
@property(retain, nonatomic) struct CGColor *pageColor; // @synthesize pageColor=_pageColor;
@property(nonatomic) id <BKPageCurlManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) int spineLocation; // @synthesize spineLocation=_spineLocation;
- (void).cxx_destruct;
- (void)killAllCurls;
- (void)pageCurl:(id)arg1 finished:(BOOL)arg2;
- (void)cancelManualCurl:(id)arg1;
- (void)finishManualCurl:(id)arg1;
- (void)updateManualCurl:(id)arg1 toLocation:(struct CGPoint)arg2;
- (id)beginManualCurl:(BOOL)arg1 atLocation:(struct CGPoint)arg2 inPage:(id)arg3 fromPages:(id)arg4 backPage:(id)arg5 inContainer:(id)arg6;
- (void)uncurlPages:(id)arg1 backPage:(id)arg2 inContainer:(id)arg3;
- (void)curlPages:(id)arg1 backPage:(id)arg2 inContainer:(id)arg3;
- (void)curlPages:(id)arg1 backPage:(id)arg2 inContainer:(id)arg3 curlPage:(BOOL)arg4;
- (BOOL)killACurl:(BOOL)arg1;
- (void)_startQueuedCurls;
- (long long)numberOfQueuedCurls;
- (id)pageCurls;
- (id)enqueuePageCurlWithType:(int)arg1;
- (void)dealloc;
- (id)init;

@end

