//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BKPlatformAlerts : NSObject
{
}

+ (void)showNoInternetDownloadThisBookAlertWindow:(id)arg1;
+ (void)showNoInternetDownloadBooksAlertWindow:(id)arg1;
+ (void)showNoInternetStoreAlertWindow:(id)arg1;
+ (void)_presentAlert:(id)arg1 withWindow:(id)arg2;
+ (id)alertHostWindowFromWindow:(id)arg1;

@end

