//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class CAShapeLayer;

@interface BKPlatformPopoverBackgroundView : NSView
{
    BOOL _topLeftCornerRadiusIsZero;
    BOOL _topRightCornerRadiusIsZero;
    unsigned int _chevronEdge;
    NSView *_popoverContentView;
    double _chevronHeight;
    double _chevronWidth;
    double _cornerRadius;
    double _lineSize;
    NSView *_layerHostingView;
    CAShapeLayer *_fillLayer;
    CAShapeLayer *_strokeLayer;
    struct CGPoint _chevronPoint;
    struct CGRect _screenTargetRect;
    struct CGRect _targetRect;
}

@property(retain) CAShapeLayer *strokeLayer; // @synthesize strokeLayer=_strokeLayer;
@property(retain) CAShapeLayer *fillLayer; // @synthesize fillLayer=_fillLayer;
@property(retain) NSView *layerHostingView; // @synthesize layerHostingView=_layerHostingView;
@property struct CGRect targetRect; // @synthesize targetRect=_targetRect;
@property BOOL topRightCornerRadiusIsZero; // @synthesize topRightCornerRadiusIsZero=_topRightCornerRadiusIsZero;
@property BOOL topLeftCornerRadiusIsZero; // @synthesize topLeftCornerRadiusIsZero=_topLeftCornerRadiusIsZero;
@property struct CGRect screenTargetRect; // @synthesize screenTargetRect=_screenTargetRect;
@property double lineSize; // @synthesize lineSize=_lineSize;
@property double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property double chevronWidth; // @synthesize chevronWidth=_chevronWidth;
@property double chevronHeight; // @synthesize chevronHeight=_chevronHeight;
@property unsigned int chevronEdge; // @synthesize chevronEdge=_chevronEdge;
@property(retain) NSView *popoverContentView; // @synthesize popoverContentView=_popoverContentView;
@property struct CGPoint chevronPoint; // @synthesize chevronPoint=_chevronPoint;
- (void).cxx_destruct;
- (struct CGPath *)p_createPathForBounds:(struct CGRect)arg1 stroke:(BOOL)arg2 outChevronPoint:(struct CGPoint *)arg3;
- (void)setFrame:(struct CGRect)arg1 animated:(BOOL)arg2;
- (void)p_updatePathInBounds:(struct CGRect)arg1 animated:(BOOL)arg2;
- (void)updateLayer;
- (BOOL)wantsUpdateLayer;
- (BOOL)wantsLayer;
- (void)setup;
- (struct CGRect)p_contentViewFrameForBounds:(struct CGRect)arg1;
- (void)updateEdge;
- (id)hitTest:(struct CGPoint)arg1;
- (void)viewDidMoveToWindow;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

