//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMWindowToolbarViewController.h"

@class IMFourStateImageButton;

@interface BKReaderWindowToolbarViewController : IMWindowToolbarViewController
{
    IMFourStateImageButton *_bookmarkButton;
    BOOL _bookstoreDisabled;
    long long _colorThemeCode;
    id _preferenceDidChangeObservation;
}

+ (id)createControlWithImages:(id)arg1 height:(double)arg2 target:(id)arg3 action:(SEL)arg4 dropDownAction:(SEL)arg5 lockOutFade:(BOOL)arg6 toolTip:(id)arg7 dropDownToolTip:(id)arg8;
+ (id)createControlWithImages:(id)arg1 height:(double)arg2 target:(id)arg3 action:(SEL)arg4 toolTip:(id)arg5;
+ (id)createControlWithImages:(id)arg1 size:(struct CGSize)arg2 target:(id)arg3 action:(SEL)arg4 toolTip:(id)arg5;
+ (id)createControlWithImages:(id)arg1 size:(struct CGSize)arg2 target:(id)arg3 action:(SEL)arg4 dropDownAction:(SEL)arg5 lockOutFade:(BOOL)arg6 toolTip:(id)arg7 dropDownToolTip:(id)arg8;
@property(retain, nonatomic) id preferenceDidChangeObservation; // @synthesize preferenceDidChangeObservation=_preferenceDidChangeObservation;
@property(nonatomic) long long colorThemeCode; // @synthesize colorThemeCode=_colorThemeCode;
@property(nonatomic) BOOL bookstoreDisabled; // @synthesize bookstoreDisabled=_bookstoreDisabled;
- (void).cxx_destruct;
- (void)_updateToolbar;
- (void)_updateStoreAvailability;
- (void)_updateBuyButton;
- (void)updateColorTheme;
- (void)setToolbarItemMask:(unsigned long long)arg1;
- (void)setSupportsSearchPageNumber:(BOOL)arg1;
- (void)setSupportsStudyCards:(BOOL)arg1;
- (void)setSample:(BOOL)arg1;
- (void)setTocTitle:(id)arg1;
- (void)setTitle:(id)arg1;
- (id)title;
- (id)_titleForString:(id)arg1 faded:(BOOL)arg2;
- (id)_fadedTitleColor;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

