//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMFetchedResultsControllerDelegate.h"

@class BKAssetArrayController, BKLibraryManagedObjectContext, IMFetchedResultsController, NSArrayController, NSDictionary, NSMutableArray, NSMutableDictionary, NSMutableSet, NSObject<BKAssetHandler>, NSString;

@interface BKUpdatesAndDownloadsController : NSObject <IMFetchedResultsControllerDelegate>
{
    BKAssetArrayController *_downloadAssets;
    BKAssetArrayController *_updateAssets;
    NSMutableArray *_downloadAssetsArray;
    NSMutableArray *_updateAssetsArray;
    NSMutableDictionary *_statusDictionary;
    NSMutableDictionary *_updateDictionary;
    id <BKBookDownloadController> _downloadController;
    id <BKBookUpdateController> _updateController;
    BKLibraryManagedObjectContext *_managedObjectContext;
    IMFetchedResultsController *_frc;
    unsigned long long _canPauseCount;
    unsigned long long _canResumeCount;
    NSMutableSet *_acknowledgedDownloads;
    NSMutableSet *_acknowledgedUpdates;
    NSDictionary *_persistentInfo;
    id _mocDidSaveObserver;
    BOOL _explicitContentRestricted;
    BOOL _hasUpdatesOrDownloads;
    BOOL _checkingForUpdates;
    NSObject<BKAssetHandler> *_assetHandler;
    double _downloadAssetsTotalPercentComplete;
    unsigned long long _unacknowledgedDownloadsCount;
    unsigned long long _unacknowledgedUpdatesCount;
}

+ (id)sharedController;
@property(readonly) unsigned long long canResumeCount; // @synthesize canResumeCount=_canResumeCount;
@property(readonly) unsigned long long canPauseCount; // @synthesize canPauseCount=_canPauseCount;
@property BOOL checkingForUpdates; // @synthesize checkingForUpdates=_checkingForUpdates;
@property(readonly) BOOL hasUpdatesOrDownloads; // @synthesize hasUpdatesOrDownloads=_hasUpdatesOrDownloads;
@property(readonly) unsigned long long unacknowledgedUpdatesCount; // @synthesize unacknowledgedUpdatesCount=_unacknowledgedUpdatesCount;
@property(readonly) unsigned long long unacknowledgedDownloadsCount; // @synthesize unacknowledgedDownloadsCount=_unacknowledgedDownloadsCount;
@property(readonly) double downloadAssetsTotalPercentComplete; // @synthesize downloadAssetsTotalPercentComplete=_downloadAssetsTotalPercentComplete;
@property __weak NSObject<BKAssetHandler> *assetHandler; // @synthesize assetHandler=_assetHandler;
@property(readonly) NSArrayController *updateAssets; // @synthesize updateAssets=_updateAssets;
@property(readonly) NSArrayController *downloadAssets; // @synthesize downloadAssets=_downloadAssets;
- (void).cxx_destruct;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(id)arg5;
- (void)controllerDidChangeContent:(id)arg1;
- (void)_primaryAccountChanged:(id)arg1;
- (void)acknowledgeCurrentUpdatesAndDownloads;
- (id)statusForAssetID:(id)arg1;
- (void)checkForUpdates:(CDUnknownBlockType)arg1;
- (void)removeCompletedDownloads;
- (void)openAsset:(id)arg1 image:(id)arg2 fromScreenRect:(struct CGRect)arg3;
- (void)restartDownloadOfAsset:(id)arg1;
- (void)cancelDownloadOfAsset:(id)arg1;
- (void)resumeDownloadOfAsset:(id)arg1;
- (void)pauseDownloadOfAsset:(id)arg1;
- (void)_startUpdateForAssetID:(id)arg1;
- (void)updateAsset:(id)arg1;
- (void)makeAccountPrimaryAndCheckForUpdateAndUpdateAssetUnacknowledged:(id)arg1;
- (void)_showUpdateFailureForAssetID:(id)arg1;
- (void)_libraryOwnershipNotification:(id)arg1;
- (void)_removeTrackingOfAssetID:(id)arg1;
- (void)_libraryUpdateNotification:(id)arg1;
- (void)_downloadStatusNotification:(id)arg1;
- (void)_updateAssetsWithBlock:(CDUnknownBlockType)arg1;
- (void)_trimUpdateDictionary;
- (void)_updateAcknowledgeCountsWithAssetIDs:(id)arg1;
- (void)_updateCountsForAssetIDs:(id)arg1;
- (void)_updateSeriesContainerDownloadStatusForAssetIDs:(id)arg1;
- (void)_updateTotalPercentCompleteForAssetIDs:(id)arg1;
- (void)syncExplicitContentRestricted;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (void)setupStateObservation;
@property(readonly) unsigned long long downloadAssetsCount;
@property(readonly) unsigned long long updateAssetsCount;
- (BOOL)_filterDownloadForAssetID:(id)arg1;
- (BOOL)_filterUpdateForAssetID:(id)arg1;
- (BOOL)_hasLibraryAssetForAssetID:(id)arg1;
- (BOOL)_passesExplicitContentFilter:(id)arg1;
- (BOOL)_hasActiveDownloadForAssetID:(id)arg1;
- (BOOL)_isSignedInForAssetID:(id)arg1;
- (void)mocDidSave:(id)arg1;
- (BOOL)_isThinnedUpdateForAssetID:(id)arg1;
- (void)_removeThinnedUpdateForAssetID:(id)arg1;
- (void)_addThinnedUpdateForAssetID:(id)arg1;
- (id)_updateInfoForAssetID:(id)arg1;
- (void)_writePersistentInfoIfNeeded;
- (void)_readPersistedInfoFromDisk;
- (void)_writePersistedInfoToDisk;
- (id)_persistedInfoURL;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

