//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextView.h"

@interface NSTextView (BKAdditions)
+ (double)textHeightForString:(id)arg1 font:(id)arg2 width:(double)arg3 lineFragmentPadding:(double)arg4;
- (void)setTextColor:(id)arg1 forRange:(struct _NSRange)arg2;
- (struct CGRect)boundsRectForSelection;
- (struct CGRect)boundsRectForCharacterRange:(struct _NSRange)arg1;
- (void)endEditingWithNewFirstResponder:(id)arg1;
- (void)startEditing;
- (BOOL)isEditing;
- (void)clearSelection;
@property(readonly, nonatomic) double lineHeight;
@property(readonly, nonatomic) double textHeight;
@end

