//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVAsset, NSString;

@interface MGAssetItem : NSObject
{
    struct CGImage *_image;
    NSString *_title;
    NSString *_subtitle;
    AVAsset *_asset;
}

+ (id)assetInformationWithAsset:(id)arg1;
@property(readonly) AVAsset *asset; // @synthesize asset=_asset;
- (void).cxx_destruct;
- (id)imageSubtitle;
- (id)imageTitle;
- (id)imageRepresentation;
- (id)imageRepresentationType;
- (id)imageUID;
- (id)subtitle;
- (id)title;
- (struct CGImage *)image;
- (void)dealloc;
- (id)initWithAsset:(id)arg1;

@end

