//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "AVPlayerItemMetadataOutputPushDelegate.h"
#import "MGMapViewDelegate.h"

@class AVAsset, AVAssetReader, AVAssetReaderOutputMetadataAdaptor, AVAssetReaderTrackOutput, AVPinAnnotationView, AVPlayer, AVPlayerItemMetadataOutput, MGMapView, NSMutableArray, NSString;

@interface MGMapViewController : NSViewController <AVPlayerItemMetadataOutputPushDelegate, MGMapViewDelegate>
{
    MGMapView *_mapView;
    AVPlayer *_player;
    AVAsset *_sourceAsset;
    AVAssetReader *_reader;
    AVAssetReaderTrackOutput *_readerMetadataOutput;
    AVAssetReaderOutputMetadataAdaptor *_readerMetadataAdaptor;
    AVPlayerItemMetadataOutput *_itemMetadataOutput;
    CDStruct_2c43369c _startingCoordinate;
    AVPinAnnotationView *_currentPin;
    NSMutableArray *_locationPoints;
    NSMutableArray *_timeStamps;
    BOOL _metadataAvailable;
    BOOL _shouldCenterMapView;
    BOOL _shouldApplyMapRegion;
    struct {
        CDStruct_2c43369c center;
        struct {
            double latitudeDelta;
            double longitudeDelta;
        } span;
    } _mapRegion;
}

- (void).cxx_destruct;
- (void)discardMap;
- (void)userDidInteractWithMapView:(id)arg1;
- (void)mapView:(id)arg1 didUpdateUserSelection:(id)arg2;
- (void)mapViewWillStartLoadingMap:(id)arg1;
- (id)mapView:(id)arg1 rendererForOverlay:(id)arg2;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)updateCurrentLocation:(id)arg1;
- (void)metadataOutput:(id)arg1 didOutputTimedMetadataGroups:(id)arg2 fromPlayerItemTrack:(id)arg3;
- (void)drawPathOnMap;
@property(readonly, nonatomic) BOOL locationMetadataAvailable;
@property(readonly, nonatomic) AVPlayer *player;
- (id)locationFromMetadataGroup:(id)arg1;
- (void)readingDidFinishSuccessfully:(BOOL)arg1 withError:(id)arg2;
- (BOOL)startReadingAndOutputReturningError:(id *)arg1;
- (BOOL)setUpReaderReturningError:(id *)arg1;
- (BOOL)readMetadata;
- (id)initWithPlayer:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

