//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class CALayer;

@interface MGProgressIndicatorView : NSView
{
    CALayer *_progressBarLayer;
    double _value;
}

- (void).cxx_destruct;
@property double value;
- (void)updateLayer;
- (BOOL)wantsUpdateLayer;
- (void)layout;
- (id)initWithFrame:(struct CGRect)arg1;

@end

