//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class MGYouTubeAccount, NSImage;

@interface MGYouTubeAuthenticationViewController : NSViewController
{
    BOOL _shouldCloseAuthenticationWindow;
    id <MGYouTubeAuthenticationViewDelegate> _delegate;
    MGYouTubeAccount *_account;
}

@property(nonatomic) BOOL shouldCloseAuthenticationWindow; // @synthesize shouldCloseAuthenticationWindow=_shouldCloseAuthenticationWindow;
@property(retain, nonatomic) MGYouTubeAccount *account; // @synthesize account=_account;
@property(nonatomic) __weak id <MGYouTubeAuthenticationViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)cancelAuthentication:(id)arg1;
- (void)authenticate:(id)arg1;
@property(readonly) NSImage *warningImage;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithAccount:(id)arg1 withDelegate:(id)arg2;

@end

