//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MapKit/_MKUIViewControllerRootView.h>

@class MKMapItem, NSArrayController, NSCollectionView, NSLayoutConstraint;

@interface MKInfoCardPhotosView : _MKUIViewControllerRootView
{
    NSCollectionView *collectionView;
    NSLayoutConstraint *_constraintToRemove;
    NSArrayController *photosArrayController;
    NSLayoutConstraint *_constraint;
    MKMapItem *mapItem;
}

@property(retain, nonatomic) MKMapItem *mapItem; // @synthesize mapItem;
- (void).cxx_destruct;
- (void)updateConstraints;
- (void)refreshContent;
- (void)awakeFromNib;

@end

