//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextView.h"

@class NSString;

@interface AAUSuffixFieldEditor : NSTextView
{
    NSString *_suffixString;
}

- (void)deleteForward:(id)arg1;
- (void)setSelectedRange:(struct _NSRange)arg1 affinity:(unsigned long long)arg2 stillSelecting:(BOOL)arg3;
- (void)setSuffixString:(id)arg1;
- (void)dealloc;
- (id)init;

@end

