//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AUDataModel;

@protocol AUModelDelegate <NSObject>

@optional
- (void)dataModelDidSaveData:(AUDataModel *)arg1;
- (void)dataModelWillSaveData:(AUDataModel *)arg1;
- (void)dataModelDidLoadData:(AUDataModel *)arg1;
- (void)dataModelWillLoadData:(AUDataModel *)arg1;
@end

