//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "StepByStepNSViewController.h"

@class NetworkAndDeviceNameNSViewController, PasswordInputNSViewController;

@interface StepByStepNSViewController_Create : StepByStepNSViewController
{
    PasswordInputNSViewController *passwordView;
    NetworkAndDeviceNameNSViewController *networkAndDeviceNameView;
}

- (id)outResultsDict;
- (void)awakeFromNib;
- (void)dealloc;

@end

