//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSColor.h"

@interface NSColor (Terminal)
+ (id)vtBrightWhiteColor;
+ (id)vtBrightCyanColor;
+ (id)vtBrightMagentaColor;
+ (id)vtBrightBlueColor;
+ (id)vtBrightYellowColor;
+ (id)vtBrightGreenColor;
+ (id)vtBrightRedColor;
+ (id)vtBrightBlackColor;
+ (id)vtWhiteColor;
+ (id)vtCyanColor;
+ (id)vtMagentaColor;
+ (id)vtBlueColor;
+ (id)vtYellowColor;
+ (id)vtGreenColor;
+ (id)vtRedColor;
+ (id)vtBlackColor;
@end

