//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSColorWell.h"

@class NSButton, NSTextField, NSView;

@interface TTANSIColorWell : NSColorWell
{
    NSView *colorPanelAccessoryView;
    NSButton *colorPanelAccessoryButton;
    NSTextField *colorTitleField;
}

- (void)restoreDefaultANSIColor:(id)arg1;
- (void)activate:(BOOL)arg1;
- (void)deactivate;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)awakeFromNib;

@end

