//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSColorWell.h"

@class NSView;

@interface TTBackgroundColorWell : NSColorWell
{
    NSView *_colorPanelAccessoryView;
}

- (void)activate:(BOOL)arg1;
- (void)deactivate;

@end

