//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class NSButton, NSNumber;

@interface TTWorkspaceSaveViewController : NSViewController
{
    NSButton *_useAsStartupCheckbox;
    NSButton *_saveAllCommandsCheckbox;
    NSNumber *_savedUseAsStartup;
}

- (void)controlTextDidChange:(id)arg1;
- (void)dealloc;

@end

