//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Safari/OneStepBookmarkingBasicButton.h>

__attribute__((visibility("hidden")))
@interface OneStepBookmarkingButton : OneStepBookmarkingBasicButton
{
    BOOL _useCheckmarkIcon;
}

+ (Class)cellClass;
@property(nonatomic) BOOL useCheckmarkIcon; // @synthesize useCheckmarkIcon=_useCheckmarkIcon;
- (void)showBookmarkingCompletedUI;
- (void)_updateIcon;
- (void)_flashCheckmarkIcon;
- (void)_fadeCheckmarkToPlusIcon;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

