//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

__attribute__((visibility("hidden")))
@interface ParsecFeatureNotificationViewController : NSViewController
{
}

+ (BOOL)notificationHasEverBeenShown;
- (id)_featureNotificationView;
- (id)_iconFilenames;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (double)preferredHeightAtCurrentWidth;
- (double)preferredMinimumWidth;

@end

