//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray;

__attribute__((visibility("hidden")))
@interface WBSCloudHistorySyncThrottler : NSObject
{
    NSMutableArray *_syncOperationsWithinMonitoredPeriod;
    NSArray *_throttlingDistribution;
    double _numberOfSecondsToMonitor;
    unsigned long long _maximumNumberOfOperationWithinMonitoredPeriod;
    id <WBSCloudHistorySyncThrottlerDataStore> _dataStore;
    unsigned long long _numberOfDevicesInSyncCircle;
}

@property(nonatomic) unsigned long long numberOfDevicesInSyncCircle; // @synthesize numberOfDevicesInSyncCircle=_numberOfDevicesInSyncCircle;
@property(retain, nonatomic) id <WBSCloudHistorySyncThrottlerDataStore> dataStore; // @synthesize dataStore=_dataStore;
- (void).cxx_destruct;
- (unsigned long long)_test_maximumNumberOfOperationWithinMonitoredPeriod;
- (double)_test_numberOfSecondsToMonitor;
- (void)_saveRecordOfPastSyncOperations;
- (void)_loadRecordOfPastSyncOperations;
- (void)_addSyncOperationAtDate:(id)arg1;
- (void)_pruneExpiredOrInvalidSyncEntries;
- (double)_currentMinimumTimeIntervalBetweenSyncOperations;
- (id)_nextPermittedSyncTime;
- (void)_loadSyncDistributionConfiguration;
- (BOOL)_loadDistributionConfiguration:(id)arg1;
- (id)_distributionBucketsFromConfiguration:(id)arg1;
- (BOOL)_throttlerIsActive;
- (id)description;
- (void)syncAttemptWithPriority:(long long)arg1 didCompleteWithResult:(long long)arg2;
- (BOOL)throttlingPolicyPermitsSyncAttemptWithPriority:(long long)arg1;
- (id)init;

@end

