//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IMCollectionViewLayout;

@protocol IMCollectionViewLayoutDataSource <NSObject>
- (struct CGSize)contentSizeForCollectionViewLayout:(IMCollectionViewLayout *)arg1;
- (unsigned long long)collectionViewLayout:(IMCollectionViewLayout *)arg1 numberOfItemsInSection:(unsigned long long)arg2;

@optional
- (double)scrollerWidthForCollectionViewLayout:(IMCollectionViewLayout *)arg1;
@end

