//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMCollectionViewDelegate.h"

@class IMCollectionView, IMCollectionViewUpdate;

@protocol IMCollectionViewDelegate_Private <IMCollectionViewDelegate>
- (BOOL)collectionView:(IMCollectionView *)arg1 shouldPerformUpdate:(IMCollectionViewUpdate *)arg2;
@end

