//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IMCollectionView, IMCollectionViewAnimator, IMCollectionViewUpdate, NSArray, NSIndexPath, NSMenu, NSSet;

@protocol IMCollectionViewDelegate <NSObject>

@optional
- (IMCollectionViewAnimator *)collectionView:(IMCollectionView *)arg1 animatorForUpdate:(IMCollectionViewUpdate *)arg2 proposedAnimator:(IMCollectionViewAnimator *)arg3;
- (NSMenu *)collectionView:(IMCollectionView *)arg1 contextMenuForIndexPaths:(NSArray *)arg2;
- (void)collectionView:(IMCollectionView *)arg1 resetSashOfItemAtIndexPath:(NSIndexPath *)arg2;
- (void)collectionView:(IMCollectionView *)arg1 didEndDraggingIndexPaths:(NSSet *)arg2;
- (void)collectionView:(IMCollectionView *)arg1 willBeginDraggingIndexPaths:(NSSet *)arg2;
- (void)collectionView:(IMCollectionView *)arg1 didClickSashOfItemAtIndexPath:(NSIndexPath *)arg2;
- (void)collectionView:(IMCollectionView *)arg1 doubleClickedItemAtIndexPath:(NSIndexPath *)arg2;
- (void)collectionView:(IMCollectionView *)arg1 didDeselectItemAtIndexPath:(NSIndexPath *)arg2;
- (void)collectionView:(IMCollectionView *)arg1 didSelectItemAtIndexPath:(NSIndexPath *)arg2;
- (BOOL)collectionView:(IMCollectionView *)arg1 shouldSelectItemAtIndexPath:(NSIndexPath *)arg2;
@end

