//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class IMCollectionView, NSIndexPath, NSMutableDictionary, NSSet;

@interface IMCollectionViewLayout : NSObject <NSCopying>
{
    BOOL _pendingLayout;
    BOOL _allowsReorder;
    BOOL _hasPreparedLayout;
    IMCollectionView *_collectionView;
    id <IMCollectionViewLayoutDataSource> _dataSource;
    NSIndexPath *_emptyIndexPath;
    NSSet *_draggedIndexes;
    NSMutableDictionary *_cellLayoutAttributes;
    NSMutableDictionary *_supplementaryViewsLayoutAttributes;
    NSMutableDictionary *_decorationViewsLayoutAttributes;
    struct CGPoint _dragOffset;
    struct CGPoint _dragLocation;
}

+ (Class)layoutAttributesClass;
@property(nonatomic) BOOL hasPreparedLayout; // @synthesize hasPreparedLayout=_hasPreparedLayout;
@property(retain, nonatomic) NSMutableDictionary *decorationViewsLayoutAttributes; // @synthesize decorationViewsLayoutAttributes=_decorationViewsLayoutAttributes;
@property(retain, nonatomic) NSMutableDictionary *supplementaryViewsLayoutAttributes; // @synthesize supplementaryViewsLayoutAttributes=_supplementaryViewsLayoutAttributes;
@property(retain, nonatomic) NSMutableDictionary *cellLayoutAttributes; // @synthesize cellLayoutAttributes=_cellLayoutAttributes;
@property(nonatomic) struct CGPoint dragLocation; // @synthesize dragLocation=_dragLocation;
@property(nonatomic) struct CGPoint dragOffset; // @synthesize dragOffset=_dragOffset;
@property(retain, nonatomic) NSSet *draggedIndexes; // @synthesize draggedIndexes=_draggedIndexes;
@property(retain, nonatomic) NSIndexPath *emptyIndexPath; // @synthesize emptyIndexPath=_emptyIndexPath;
@property(nonatomic) BOOL allowsReorder; // @synthesize allowsReorder=_allowsReorder;
@property(nonatomic) __weak id <IMCollectionViewLayoutDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak IMCollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void).cxx_destruct;
- (unsigned long long)_numberOfItems;
- (id)indexPathForItemBelowIndexPath:(id)arg1;
- (id)indexPathForItemAboveIndexPath:(id)arg1;
- (id)indexPathForItemTrailingIndexPath:(id)arg1;
- (id)indexPathForItemToLeadingIndexPath:(id)arg1;
- (id)supportedDecorationViewKinds;
- (id)supportedSupplementaryViewKinds;
- (id)adjustedLayoutAttributesForSupplementaryViewOfkind:(id)arg1 atIndexPath:(id)arg2;
- (id)adjustedLayoutAttributesForItemAtIndexPath:(id)arg1;
@property(readonly, getter=isPendingLayout) BOOL pendingLayout;
- (void)setPendingLayout;
- (BOOL)shouldInvalidateLayoutForBoundsChange:(struct CGRect)arg1;
- (void)prepareLayoutIfNeeded;
- (void)invalidateLayout;
- (void)prepareLayout;
- (void)applyUpdate:(id)arg1;
- (id)layoutAttributesForElementAtPoint:(struct CGPoint)arg1;
- (id)finalLayoutAttributesForDisappearingDecorationElementOfKind:(id)arg1;
- (id)finalLayoutAttributesForDisappearingSupplementaryElementOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)finalLayoutAttributesForDisappearingItemAtIndexPath:(id)arg1;
- (id)initialLayoutAttributesForAppearingDecorationElementOfKind:(id)arg1;
- (id)initialLayoutAttributesForAppearingSupplementaryElementOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)initialLayoutAttributesForAppearingItemAtIndexPath:(id)arg1;
- (id)layoutAttributesForDecorationViewOfKind:(id)arg1;
- (id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (id)layoutAttributesForDraggedItems;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (struct CGSize)collectionViewContentSize;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithDataSource:(id)arg1;
- (id)initWithCollectionView:(id)arg1;
- (id)init;

@end

