//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IMPlatformCore/IMWindow.h>

#import "IMPlugIn.h"
#import "IMUndoDelegateHost.h"

@class NSString;

@interface IMNativeWindow : IMWindow <IMPlugIn, IMUndoDelegateHost>
{
    int state;
    id <IMWindowUndoDelegate> undoDelegate;
}

+ (unsigned long long)p_styleMaskForNewWindow;
+ (void)initialize;
@property __weak id <IMWindowUndoDelegate> undoDelegate; // @synthesize undoDelegate;
@property(nonatomic) int state; // @synthesize state;
- (void).cxx_destruct;
- (void)sendEvent:(id)arg1;
- (id)initWithPlugInInstanceDescriptor:(id)arg1;
- (double)_toolbarLeadingSpace;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

