//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "NSAnimationDelegate.h"

@class IMColoredView, IMWindowToolbarViewController, NSString, NSViewAnimation;

@interface IMToolbarWindowFrame : NSView <NSAnimationDelegate>
{
    IMColoredView *_container;
    NSView *_overlayView;
    NSView *_leftView;
    NSViewAnimation *_leftPaneAnimation;
    CDUnknownBlockType _leftPaneAnimationCompleteBlock;
    BOOL _enteringFullScreen;
    BOOL _allowFullScreenToolbar;
    BOOL _overlayInContainer;
    BOOL _overlayAllowsResize;
    double _cornerRadius;
    NSView *_contentView;
    IMWindowToolbarViewController *_toolbarViewController;
    double _toolbarHeight;
    CDStruct_3c058996 _insets;
}

@property BOOL overlayAllowsResize; // @synthesize overlayAllowsResize=_overlayAllowsResize;
@property BOOL overlayInContainer; // @synthesize overlayInContainer=_overlayInContainer;
@property double toolbarHeight; // @synthesize toolbarHeight=_toolbarHeight;
@property(nonatomic) BOOL allowFullScreenToolbar; // @synthesize allowFullScreenToolbar=_allowFullScreenToolbar;
@property(readonly) __weak IMColoredView *container; // @synthesize container=_container;
@property(readonly) IMWindowToolbarViewController *toolbarViewController; // @synthesize toolbarViewController=_toolbarViewController;
@property(retain, nonatomic) NSView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) CDStruct_3c058996 insets; // @synthesize insets=_insets;
- (void).cxx_destruct;
- (void)windowDidExitFullScreen:(id)arg1;
- (void)windowDidEnterFullScreen:(id)arg1;
- (void)windowWillExitFullScreen:(id)arg1;
- (void)windowWillEnterFullScreen:(id)arg1;
- (void)windowStateDidChange;
- (void)removeLeftPaneAnimated:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_removeLeftPaneFromFullScreenAnimated:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_removeLeftPaneFromWindowAnimated:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (void)animationDidEnd:(id)arg1;
- (void)addLeftPane:(id)arg1 width:(double)arg2 animated:(BOOL)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_addInFullScreenLeftPane:(id)arg1 width:(double)arg2 animated:(BOOL)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_addInWindowLeftPane:(id)arg1 width:(double)arg2 animated:(BOOL)arg3 completion:(CDUnknownBlockType)arg4;
- (struct CGRect)_frameForWindowFrame:(struct CGRect)arg1 withSidebarOfWidth:(double)arg2 beingAdded:(BOOL)arg3;
- (BOOL)adjustWindowFrameToAccommodateSidebarOfWidth:(double)arg1 beingAdded:(BOOL)arg2;
- (void)setFrameSize:(struct CGSize)arg1;
- (void)_setInFullScreenFrameSize:(struct CGSize)arg1;
- (void)_setInWindowFrameSize:(struct CGSize)arg1;
- (BOOL)hasOverlay;
- (void)setOverlayView:(id)arg1 inContainer:(BOOL)arg2 overlayAllowsResize:(BOOL)arg3 completion:(CDUnknownBlockType)arg4;
- (void)setOverlayView:(id)arg1 inContainer:(BOOL)arg2 overlayAllowsResize:(BOOL)arg3;
- (void)layoutFrame;
- (id)createToolbarViewController;
- (id)initWithFrame:(struct CGRect)arg1 withToolbarViewController:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

