//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableAttributedString.h"

@interface NSMutableAttributedString (IMPlatformAdditions)
- (void)truncateToFitWidth:(double)arg1 withEllipsis:(id)arg2 truncationType:(unsigned int)arg3;
- (void)trimCharactersInSet:(id)arg1 fromStart:(BOOL)arg2 fromEnd:(BOOL)arg3;
- (void)appendBaselineImage:(id)arg1;
- (void)appendImage:(id)arg1;
@end

