//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class BKLibraryManagedObjectContext, NSDate, NSNumber, NSSet, NSString;

@interface BKCollection : NSManagedObject
{
}

+ (id)mapContentTypeToDefaultCollectionIDForOS;
+ (id)availableDefaultCollectionIDsForOS;
+ (void)addCollections:(id)arg1 moc:(id)arg2;
+ (void)mergeCollections:(id)arg1 moc:(id)arg2;
+ (BOOL)isValidForDeserialization:(id)arg1;
+ (id)titleForDefaultCollectionID:(id)arg1;
+ (id)sortKeyForDefaultCollectionID:(id)arg1;
+ (id)predicateForUserCollections;
+ (id)predicateForAllDefaultCollections;
+ (id)predicateForCollectionWithCollectionIDInList:(id)arg1;
+ (id)insertNewCollectionWithCollectionID:(id)arg1 inManagedObjectContext:(id)arg2;
+ (id)collectionWithID:(id)arg1 inManagedObjectContext:(id)arg2;
+ (void)resetCollectionsWithLibraryManagedObjectContext:(id)arg1;
+ (void)setupDefaultCollectionsWithLibraryManagedObjectContext:(id)arg1;
+ (id)userCollectionsInManagedObjectContext:(id)arg1;
+ (id)defaultCollectionsInManagedObjectContext:(id)arg1;
+ (id)keyPathsForValuesAffectingLocalizedTitle;
- (void)deserializeFromBackupSummary:(id)arg1;
- (BOOL)deleteRemovesFromCollection;
- (BOOL)canDeleteLibraryAsset:(id)arg1;
- (BOOL)allowSortManual;
- (BOOL)isDefaultCollection;
- (void)evictNonMatchingDatabaseKeys:(id)arg1;
- (id)contentTypePredicate;
- (void)deserializeFromDictionary:(id)arg1;
- (void)mergeWithDictionaryRepresentation:(id)arg1;
- (id)dictionaryRepresentation;
- (BOOL)isValidForSerialization;
@property(readonly, retain, nonatomic) BKLibraryManagedObjectContext *managedObjectContext;
- (void)setLocalizedTitle:(id)arg1;
@property(readonly) NSString *localizedTitle;
@property(retain, nonatomic) NSNumber *deletedFlag; // @dynamic deletedFlag;
@property(retain, nonatomic) NSString *title; // @dynamic title;
@property(retain, nonatomic) NSNumber *sortKey; // @dynamic sortKey;
- (void)updateLastModification;
- (void)addMembers:(id)arg1;
- (BOOL)isEqualToCollection:(id)arg1;
- (BOOL)acceptsContentType:(short)arg1;
- (void)addCollectionMemberDictionaries:(id)arg1 touchDirtyFlag:(BOOL)arg2;
- (void)addCollectionMemberDictionaries:(id)arg1;
- (void)destroy;
- (void)claimLibraryAssets:(id)arg1;
- (void)queueClaimLibraryAssets:(id)arg1;
- (id)booksPredicate;
- (void)awakeFromInsert;

// Remaining properties
@property(retain, nonatomic) NSString *collectionID; // @dynamic collectionID;
@property(retain, nonatomic) NSDate *lastModification; // @dynamic lastModification;
@property(retain, nonatomic) NSSet *members; // @dynamic members;

@end

