//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BKLibraryProgressStatus.h"

@class NSString;

@interface BKLibraryDownloadStatus : NSObject <BKLibraryProgressStatus>
{
    BOOL _internetReachable;
    BOOL _waitingToBeDownloadable;
    NSString *_assetID;
    double _progressValue;
    long long _state;
    long long _timeRemaining;
    unsigned long long _bytesDownloaded;
    unsigned long long _fileSize;
}

+ (id)statusWithAssetID:(id)arg1 state:(long long)arg2 progressValue:(double)arg3 timeRemaining:(long long)arg4;
@property(readonly, nonatomic) BOOL waitingToBeDownloadable; // @synthesize waitingToBeDownloadable=_waitingToBeDownloadable;
@property(readonly, nonatomic) BOOL internetReachable; // @synthesize internetReachable=_internetReachable;
@property(readonly, nonatomic) unsigned long long fileSize; // @synthesize fileSize=_fileSize;
@property(readonly, nonatomic) unsigned long long bytesDownloaded; // @synthesize bytesDownloaded=_bytesDownloaded;
@property(readonly, nonatomic) long long timeRemaining; // @synthesize timeRemaining=_timeRemaining;
@property(readonly, nonatomic) long long state; // @synthesize state=_state;
@property(readonly, nonatomic) double progressValue; // @synthesize progressValue=_progressValue;
@property(readonly, nonatomic) NSString *assetID; // @synthesize assetID=_assetID;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (BOOL)hasFinished;
- (BOOL)canStart;
- (BOOL)canRestart;
- (BOOL)canResume;
- (BOOL)canPause;
- (void)updateWithWaitingToBeDownloadable:(BOOL)arg1;
- (void)updateWithStatus:(id)arg1;
- (id)initWithAssetID:(id)arg1 state:(long long)arg2 progressValue:(double)arg3 timeRemaining:(long long)arg4 bytesDownloaded:(unsigned long long)arg5 fileSize:(unsigned long long)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

