//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class BKLibraryManagedObjectContext, NSDate, NSNumber, NSSet, NSString;

@interface BKLibraryAsset : NSManagedObject
{
    BOOL isDecompressing;
}

+ (id)unknownTitle;
+ (id)unknownAuthor;
+ (id)keyPathsForValuesAffectingIsImporting;
+ (id)keyPathsForValuesAffectingIsLocal;
+ (id)keyPathsForValuesAffectingIsDownloading;
+ (id)libraryAssetsWithAssetIDsContainedInList:(id)arg1 inManagedObjectContext:(id)arg2;
+ (unsigned long long)numberOfLibraryAssetsInManagdObjectContext:(id)arg1;
+ (id)libraryAssetWithAssetID:(id)arg1 inManagedObjectContext:(id)arg2;
+ (id)predicateForBooksThatCanHaveHigherWaterMarks;
+ (id)predicateForSeriesContainers;
+ (id)predicateForSeriesContainerWithSeriesID:(id)arg1;
+ (id)predicateForSeriesItemsInTheStore;
+ (id)predicateForLibraryAssetsWithSeriesID:(id)arg1;
+ (id)predicateToExcludeContainerContentTypes;
+ (id)predicateForNextSeriesItems;
+ (id)predicateToExcludeSeriesBooksYouDontOwn;
+ (id)predicateForBooksShownInAllBooksWithPurchasesDisabled;
+ (id)predicateForBooksShownInAllBooks;
+ (id)_predicateForBooksShownInAllBooksShowingPurchases:(BOOL)arg1;
+ (id)predicateToExcludeHiddenSeriesAssets;
+ (id)predicateToExcludeLibraryAssetsWithExplicitContent;
+ (id)predicateForLibraryAssetsMissingExplicitContentFlag;
+ (id)predicateForLibraryAssetsThatWarnedAboutDesktopSupport;
+ (id)predicateForLibraryAssetsWithoutCoverURL;
+ (id)predicateForLibraryAssetsWithDataSourceIdentifier:(id)arg1;
+ (id)predicateForLibraryAssetsMarkedAsNew;
+ (id)predicateForLibraryAssetsMatchingSearchString:(id)arg1;
+ (id)predicateForLibraryAssetsWithGenre:(id)arg1;
+ (id)predicateForLibraryAssetsWithAuthor:(id)arg1;
+ (id)predicateForLibraryAssetsOpenedSince:(id)arg1;
+ (id)predicateForLibraryAssetsRecentlyOpened;
+ (id)predicateForNonCloudLibraryAssetsAndContainers;
+ (id)predicateForNonCloudLibraryAssets;
+ (id)predicateForLocalLibraryAssets;
+ (id)predicateForLibraryAssetsInCloud;
+ (id)predicateForLibraryAssetsFromStore;
+ (id)predicateForDownloadableLibraryAssets;
+ (id)predicateForLibraryAssetWithCollectionIDsInList:(id)arg1;
+ (id)predicateForLibraryAssetsWithAssetIDsContainedInList:(id)arg1;
+ (id)hiddenAssetsPredicate;
+ (id)excludeHiddenAssetsPredicate;
+ (id)insertNewLibraryAssetWithIdentifier:(id)arg1 assetID:(id)arg2 type:(short)arg3 inManagedObjectContext:(id)arg4;
@property(nonatomic) BOOL isDecompressing; // @synthesize isDecompressing;
- (long long)inverseCompareSortKey:(id)arg1;
- (long long)compareSortKey:(id)arg1;
- (BOOL)save:(id *)arg1;
@property(readonly, nonatomic) BKLibraryManagedObjectContext *managedObjectContext;
- (void)setCreationDateToNow;
- (void)setModificationDateToNow;
- (void)setLastOpenDateToNow;
- (id)containerChildAssetsForCoverLocalOnly:(BOOL)arg1;
@property(readonly, nonatomic) unsigned long long containerChildCountOfNonCloudAssets;
@property(readonly, nonatomic) unsigned long long containerChildCountOfPurchasedAssets;
@property(readonly, nonatomic) BOOL canEditMetadata;
@property(readonly, nonatomic) BOOL isImporting; // @dynamic isImporting;
@property(readonly, nonatomic) BOOL isSeriesContainer;
@property(readonly, nonatomic) BOOL isSeriesItem;
@property(readonly, nonatomic) BOOL isCloud;
@property(readonly, nonatomic) BOOL isLocal; // @dynamic isLocal;
@property(readonly, nonatomic) BOOL isDownloading; // @dynamic isDownloading;
@property(readonly, nonatomic) BOOL isStore;

// Remaining properties
@property(retain, nonatomic) NSString *accountID; // @dynamic accountID;
@property(retain, nonatomic) NSString *assetID; // @dynamic assetID;
@property(retain, nonatomic) NSString *author; // @dynamic author;
@property(retain, nonatomic) NSString *bookDescription; // @dynamic bookDescription;
@property(retain, nonatomic) NSNumber *bookHighWaterMarkProgress; // @dynamic bookHighWaterMarkProgress;
@property(retain, nonatomic) NSDate *bookmarksServerMaxModificationDate; // @dynamic bookmarksServerMaxModificationDate;
@property(retain, nonatomic) NSString *bookmarksServerVersion; // @dynamic bookmarksServerVersion;
@property(nonatomic) BOOL canRedownload; // @dynamic canRedownload;
@property(retain, nonatomic) NSString *collectionID; // @dynamic collectionID;
@property(retain, nonatomic) NSString *comments; // @dynamic comments;
@property(nonatomic) BOOL computedRating; // @dynamic computedRating;
@property(nonatomic) short contentType; // @dynamic contentType;
@property(retain, nonatomic) NSString *coverURL; // @dynamic coverURL;
@property(retain, nonatomic) NSDate *creationDate; // @dynamic creationDate;
@property(retain, nonatomic) NSString *dataSourceIdentifier; // @dynamic dataSourceIdentifier;
@property(nonatomic) short desktopSupportLevel; // @dynamic desktopSupportLevel;
@property(nonatomic) BOOL didWarnAboutDesktopSupport; // @dynamic didWarnAboutDesktopSupport;
@property(nonatomic) long long fileSize; // @dynamic fileSize;
@property(nonatomic) long long generation; // @dynamic generation;
@property(retain, nonatomic) NSString *genre; // @dynamic genre;
@property(retain, nonatomic) NSString *grouping; // @dynamic grouping;
@property(retain, nonatomic) NSNumber *isExplicit; // @dynamic isExplicit;
@property(nonatomic) BOOL isHidden; // @dynamic isHidden;
@property(nonatomic) BOOL isLocked; // @dynamic isLocked;
@property(nonatomic) BOOL isNew; // @dynamic isNew;
@property(nonatomic) BOOL isProof; // @dynamic isProof;
@property(nonatomic) BOOL isSample; // @dynamic isSample;
@property(retain, nonatomic) NSString *kind; // @dynamic kind;
@property(retain, nonatomic) NSDate *lastOpenDate; // @dynamic lastOpenDate;
@property(retain, nonatomic) NSSet *localOnlySeriesItems; // @dynamic localOnlySeriesItems;
@property(retain, nonatomic) BKLibraryAsset *localOnlySeriesItemsParent; // @dynamic localOnlySeriesItemsParent;
@property(retain, nonatomic) NSDate *locationServerMaxModificationDate; // @dynamic locationServerMaxModificationDate;
@property(retain, nonatomic) NSString *locationServerVersion; // @dynamic locationServerVersion;
@property(nonatomic) long long metadataMigrationVersion; // @dynamic metadataMigrationVersion;
@property(retain, nonatomic) NSDate *modificationDate; // @dynamic modificationDate;
@property(nonatomic) long long pageCount; // @dynamic pageCount;
@property(retain, nonatomic) NSString *path; // @dynamic path;
@property(retain, nonatomic) NSDate *purchaseDate; // @dynamic purchaseDate;
@property(retain, nonatomic) BKLibraryAsset *purchasedAndLocalParent; // @dynamic purchasedAndLocalParent;
@property(retain, nonatomic) NSSet *purchasedAndLocalSeriesItems; // @dynamic purchasedAndLocalSeriesItems;
@property(nonatomic) long long rating; // @dynamic rating;
@property(retain, nonatomic) NSDate *releaseDate; // @dynamic releaseDate;
@property(retain, nonatomic) NSString *sequenceDisplayName; // @dynamic sequenceDisplayName;
@property(retain, nonatomic) NSString *seriesID; // @dynamic seriesID;
@property(retain, nonatomic) NSNumber *seriesIsCloudOnly; // @dynamic seriesIsCloudOnly;
@property(retain, nonatomic) NSNumber *seriesIsHidden; // @dynamic seriesIsHidden;
@property(nonatomic) BOOL seriesNextFlag; // @dynamic seriesNextFlag;
@property(retain, nonatomic) NSNumber *seriesSortKey; // @dynamic seriesSortKey;
@property(retain, nonatomic) NSString *sortAuthor; // @dynamic sortAuthor;
@property(retain, nonatomic) NSNumber *sortKey; // @dynamic sortKey;
@property(retain, nonatomic) NSString *sortTitle; // @dynamic sortTitle;
@property(nonatomic) short state; // @dynamic state;
@property(retain, nonatomic) NSString *storeID; // @dynamic storeID;
@property(retain, nonatomic) NSString *title; // @dynamic title;
@property(retain, nonatomic) NSDate *updateDate; // @dynamic updateDate;
@property(retain, nonatomic) NSNumber *versionNumber; // @dynamic versionNumber;
@property(retain, nonatomic) NSString *year; // @dynamic year;

@end

