//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BKUserSortOrderManager : NSObject
{
}

+ (void)sendLibraryAssetToFront:(id)arg1;
+ (void)saveSortedCollectionsArray:(id)arg1 moc:(id)arg2;
+ (void)resetSortedBooksArray:(id)arg1 moc:(id)arg2;
+ (void)saveSortedBooksArray:(id)arg1 moc:(id)arg2;
+ (BOOL)resortDescendingSortKeyedObjects:(id)arg1;
+ (void)resetDescendingSortKeyedObjects:(id)arg1;
+ (BOOL)resortAscendingSortKeyedObjects:(id)arg1;

@end

