//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IMCommonCore/AEAnnotationTheme.h>

@interface AEAnnotationThemePurple : AEAnnotationTheme
{
}

- (int)annotationStyle;
- (BOOL)isUnderline;
- (id)notesSidebarBarColor;
- (id)noteMarkerBorderColor;
- (id)noteMarkerFillColor;
- (id)highlightColor;
- (id)noteTextColor;
- (id)noteBorderColor;
- (id)noteFillColor;

@end

