//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AEAnnotationFilter.h"

@class NSString;

@interface AEAnnotationBlockFilter : NSObject <AEAnnotationFilter>
{
    CDUnknownBlockType _filterBlock;
    BOOL _concurrent;
}

+ (id)filterWithConcurrentBlock:(CDUnknownBlockType)arg1;
+ (id)filterWithBlock:(CDUnknownBlockType)arg1;
- (void).cxx_destruct;
- (id)filteredAnnotations:(id)arg1;
- (id)initConcurrent:(BOOL)arg1 withBlock:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

