//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSDate, NSString;

@interface BKSeriesCheck : NSManagedObject
{
}

+ (BOOL)shouldRecheckAdamID:(id)arg1 inManagedObjectContext:(id)arg2;
+ (void)recordAdamIDsAsChecked:(id)arg1 inManagedObjectContext:(id)arg2;
+ (id)adamIDsNeedingToBeCheckedFromAdamIDs:(id)arg1 inManagedObjectContext:(id)arg2;
+ (id)predicateForSeriesCheckWithAdamIDsInList:(id)arg1;
+ (id)fetchRequest;
+ (id)insertSeriesCheckWithAdamId:(id)arg1 intoManagedObjectContext:(id)arg2;

// Remaining properties
@property(retain, nonatomic) NSString *adamId; // @dynamic adamId;
@property(retain, nonatomic) NSDate *dateChecked; // @dynamic dateChecked;

@end

