//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSOperationQueue, NSString;

@interface IMMemoryCache : NSObject
{
    BOOL _evictsItemsWithDiscardedContent;
    NSString *_name;
    id _delegate;
    unsigned long long _totalCostLimit;
    unsigned long long _countLimit;
    NSMutableDictionary *_items;
    NSMutableArray *_itemsArray;
    NSOperationQueue *_queue;
    NSObject<OS_dispatch_queue> *_accessQueue;
    double _lastCheckTime;
    unsigned long long _count;
    unsigned long long _totalCost;
}

@property(nonatomic) unsigned long long totalCost; // @synthesize totalCost=_totalCost;
@property(nonatomic) unsigned long long count; // @synthesize count=_count;
@property(nonatomic) double lastCheckTime; // @synthesize lastCheckTime=_lastCheckTime;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *accessQueue; // @synthesize accessQueue=_accessQueue;
@property(retain, nonatomic) NSOperationQueue *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSMutableArray *itemsArray; // @synthesize itemsArray=_itemsArray;
@property(retain, nonatomic) NSMutableDictionary *items; // @synthesize items=_items;
@property(nonatomic) unsigned long long countLimit; // @synthesize countLimit=_countLimit;
@property(nonatomic) unsigned long long totalCostLimit; // @synthesize totalCostLimit=_totalCostLimit;
@property(nonatomic) BOOL evictsItemsWithDiscardedContent; // @synthesize evictsItemsWithDiscardedContent=_evictsItemsWithDiscardedContent;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (void)_removeObjectForKey:(id)arg1;
- (void)_addItem:(id)arg1 forKey:(id)arg2;
- (id)description;
- (long long)numberOfCachedItems;
- (unsigned long long)costForObjectWithKey:(id)arg1;
- (void)_checkLimits;
- (void)_checkLimitsAndEvictObjects;
- (void)checkLimitsAndEvictObjects;
- (BOOL)_shouldRemoveIndex:(unsigned long long)arg1;
- (void)removeObjectsForKeyWithPrefix:(id)arg1;
- (void)removeAllObjects;
- (void)removeObjectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2 cost:(unsigned long long)arg3;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKey:(id)arg1;
- (id)allKeys;
- (void)dealloc;
- (id)init;

@end

