//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@interface AKSignatureCreationViewController : NSViewController
{
}

- (void)cancelSignatureCreation:(id)arg1;
- (void)confirmSignatureCreation:(id)arg1;
- (id)initWithController:(id)arg1;

@end

