//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSScroller.h"

@interface BlackScroller : NSScroller
{
}

+ (BOOL)isCompatibleWithOverlayScrollers;
- (void)drawKnobSlotInRect:(struct CGRect)arg1 highlight:(BOOL)arg2;
- (void)drawKnob;
- (void)drawRect:(struct CGRect)arg1;
- (struct CGRect)rectForPart:(unsigned long long)arg1;
- (void)setScrollerStyle:(long long)arg1;

@end

