//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IDSBatchIDQueryControllerDelegate.h"

@class IDSBatchIDQueryController, NSMutableDictionary, NSMutableSet, NSString;

@interface FTIDSLookupManager : NSObject <IDSBatchIDQueryControllerDelegate>
{
    id <FTIDSLoookupManagerDelegate> _delegate;
    NSMutableDictionary *_destinationToPersonID;
    NSMutableSet *_videoLookup;
    NSMutableSet *_audioLookup;
    IDSBatchIDQueryController *_batchQueryVideoController;
    IDSBatchIDQueryController *_batchQueryAudioController;
}

+ (id)sharedManager;
@property(retain, nonatomic) IDSBatchIDQueryController *batchQueryAudioController; // @synthesize batchQueryAudioController=_batchQueryAudioController;
@property(retain, nonatomic) IDSBatchIDQueryController *batchQueryVideoController; // @synthesize batchQueryVideoController=_batchQueryVideoController;
@property(retain, nonatomic) NSMutableSet *audioLookup; // @synthesize audioLookup=_audioLookup;
@property(retain, nonatomic) NSMutableSet *videoLookup; // @synthesize videoLookup=_videoLookup;
@property(retain, nonatomic) NSMutableDictionary *destinationToPersonID; // @synthesize destinationToPersonID=_destinationToPersonID;
@property(nonatomic) __weak id <FTIDSLoookupManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)idStatusUpdatedForDestinations:(id)arg1 service:(id)arg2;
- (BOOL)parseResultsDictionary:(id)arg1 service:(id)arg2;
- (void)_populateWithCachedData;
- (void)beginQueryWithCurrentPeople;
- (BOOL)audioAvailableForRowItem:(id)arg1;
- (BOOL)videoAvailableForRowItem:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

