//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMAVChat.h"

@interface IMAVChat (FaceTimeAdditions)
+ (void)getIsMissedCall:(char *)arg1 isFailure:(char *)arg2 forReason:(unsigned int)arg3 isOutgoing:(BOOL)arg4;
- (void)getErrorMainText:(id *)arg1 subText:(id *)arg2 usingName:(id)arg3;
- (void)getIsMissedCall:(char *)arg1 isFailure:(char *)arg2;
@end

