//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@interface VideoHeaderViewController : NSViewController
{
}

- (double)imageDiameter;
- (void)setImage:(id)arg1;
- (void)setSubText:(id)arg1;
- (void)setText:(id)arg1;
- (void)_updateViews;
- (void)awakeFromNib;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

