//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSApplication.h"

#import "NSApplicationDelegate.h"

@class LocationAppManager, NSStatusItem, NSString;

@interface AppController : NSApplication <NSApplicationDelegate>
{
    NSStatusItem *_statusItem;
    LocationAppManager *_locationAppManager;
}

- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)openPrefs:(id)arg1;
- (void)checkAppsOrQuit;
- (void)updateMenuWithApps:(id)arg1;
- (id)_disabledMenuItemWithTitle:(id)arg1;
- (void)setUpMenu;
- (void)dealloc;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

