//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface _IMKCandidatePrivateInfo : NSObject
{
    BOOL _checkedDefinitionFlag;
    BOOL _hasDefinition;
}

@property BOOL hasDefinition; // @synthesize hasDefinition=_hasDefinition;
@property BOOL checkedDefinitionFlag; // @synthesize checkedDefinitionFlag=_checkedDefinitionFlag;

@end

