//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (IMKUserDictionaryAdditions)
+ (struct USet *)nonHiraganaKatakanaOrBopomofoSet;
+ (struct USet *)nonCJKSymbolsSet;
+ (struct USet *)nonIdeographicCharacterSet;
+ (struct USet *)ideographicCharacterSet;
+ (struct USet *)characterSetWithPattern:(id)arg1;
- (BOOL)contentsExclusivelyInCharacterSet:(struct USet *)arg1;
- (BOOL)containsWhitespace;
- (BOOL)containsEmoji;
- (BOOL)containsHiraganaKatakanaOrBopomofo;
- (BOOL)containsCJKSymbolsAndPunctuation;
- (BOOL)containsIdeographicCharacters;
- (BOOL)containsOnlyIdeographicCharacters;
@end

