//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Automator/AMWorkflowPersonality.h>

@interface AMImageCaptureWorkflowPersonality : AMWorkflowPersonality
{
}

- (BOOL)finishSavingDocument:(id)arg1 atURL:(id)arg2 error:(id *)arg3;
- (id)infoStringForCompleteInstallationWithMetaData:(id)arg1;
- (id)imageRepresentation;
- (id)personalitySettingsDictionary;

@end

