//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCollectionView.h"

@class AMPersonalityChooserDisplayController;

@interface AMPersonalityCollectionView : NSCollectionView
{
    AMPersonalityChooserDisplayController *_personalityChooserDisplayController;
}

@property AMPersonalityChooserDisplayController *personalityChooserDisplayController; // @synthesize personalityChooserDisplayController=_personalityChooserDisplayController;
- (void)setSelectionIndexes:(id)arg1;
- (void)keyDown:(id)arg1;

@end

