//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TKToken;

@interface TKTokenSession : NSObject
{
    TKToken *_token;
}

@property(readonly) TKToken *token; // @synthesize token=_token;
- (void).cxx_destruct;
- (BOOL)deleteObject:(id)arg1 error:(id *)arg2;
- (id)generateKeyPairWithAttributes:(id)arg1 publicKey:(id *)arg2 error:(id *)arg3;
- (id)addObject:(id)arg1 error:(id *)arg2;
- (id)objectForId:(id)arg1 error:(id *)arg2;
- (id)initWithToken:(id)arg1;

@end

