//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CryptoTokenKit/TKTokenObject.h>

@interface TKTokenPrivateKey : TKTokenObject
{
}

- (id)decryptData:(id)arg1 padding:(unsigned int)arg2 error:(id *)arg3;
- (id)signData:(id)arg1 padding:(unsigned int)arg2 error:(id *)arg3;

@end

