//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableArray;

@interface TKTokenKeychainState : NSObject
{
    NSMutableArray *_pending;
    id _status;
    NSDictionary *_tokenObjects;
}

+ (void)addKeyAttributes:(id)arg1 certificate:(struct OpaqueSecCertificateRef *)arg2;
+ (void)addCertificateAttributes:(id)arg1 certificate:(struct OpaqueSecCertificateRef *)arg2;
@property(readonly) NSDictionary *tokenObjects; // @synthesize tokenObjects=_tokenObjects;
@property(readonly) id status; // @synthesize status=_status;
- (void).cxx_destruct;
- (BOOL)commitWithStatus:(id)arg1 error:(id *)arg2;
- (void)deleteObjectWithAttributes:(id)arg1;
- (void)addObjectWithAttributes:(id)arg1 objectId:(id)arg2;
- (id)initWithClassId:(id)arg1 instanceId:(id)arg2;

@end

