//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextField.h"

@class NSCursor, SMProcessController;

@interface LinkedTextField : NSTextField
{
    int _ppid;
    SMProcessController *_controller;
    NSCursor *_cursor;
}

- (void).cxx_destruct;
- (void)resetCursorRects;
- (void)mouseDown:(id)arg1;
- (void)setParentProcessID:(int)arg1 controller:(id)arg2;

@end

