//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HiCloudViewController.h"

@class CloudConfigurationManager, DiagnosticsInfoSheetController, IKProfilePictureView, LocalUserAccountManager, NSButton, NSImageView, NSLayoutConstraint, NSMatrix, NSString, NSTextField, NSTextView;

@interface CreateUserAccountController : HiCloudViewController
{
    NSTextField *accountName;
    NSTextField *password;
    NSTextField *passwordVerify;
    NSTextField *passwordHint;
    NSImageView *accountNameFail;
    NSButton *requirePasswordAtLogin;
    IKProfilePictureView *userPictureWidget;
    BOOL didWarnAboutEmptyPasswordHint;
    BOOL allowAutofill;
    BOOL controlsEditable;
    BOOL allowAppleIDPasswordReset;
    BOOL sendDiagnosticsToApple;
    BOOL setTimezoneAutomatically;
    BOOL fullNameFail;
    BOOL passwordFail;
    BOOL _hintFail;
    BOOL _passwordVerifyFail;
    BOOL _appleIDAsLoginChecked;
    NSString *fullName;
    NSTextView *diagnosticsTextView;
    NSLayoutConstraint *appleIDResetDistance;
    NSLayoutConstraint *requirePasswordDistance;
    DiagnosticsInfoSheetController *diagnosticsInfoSheet;
    NSTextField *_fullNameField;
    NSMatrix *_optionsMatrix;
    NSLayoutConstraint *_passwordFieldDistance;
}

+ (id)keyPathsForValuesAffectingUseAppleIDAsLogin;
@property NSLayoutConstraint *passwordFieldDistance; // @synthesize passwordFieldDistance=_passwordFieldDistance;
@property NSMatrix *optionsMatrix; // @synthesize optionsMatrix=_optionsMatrix;
@property BOOL appleIDAsLoginChecked; // @synthesize appleIDAsLoginChecked=_appleIDAsLoginChecked;
@property BOOL passwordVerifyFail; // @synthesize passwordVerifyFail=_passwordVerifyFail;
@property BOOL hintFail; // @synthesize hintFail=_hintFail;
@property NSTextField *fullNameField; // @synthesize fullNameField=_fullNameField;
@property(retain) DiagnosticsInfoSheetController *diagnosticsInfoSheet; // @synthesize diagnosticsInfoSheet;
@property NSLayoutConstraint *requirePasswordDistance; // @synthesize requirePasswordDistance;
@property NSLayoutConstraint *appleIDResetDistance; // @synthesize appleIDResetDistance;
@property NSTextView *diagnosticsTextView; // @synthesize diagnosticsTextView;
@property BOOL passwordFail; // @synthesize passwordFail;
@property BOOL fullNameFail; // @synthesize fullNameFail;
@property(retain) NSString *fullName; // @synthesize fullName;
@property BOOL setTimezoneAutomatically; // @synthesize setTimezoneAutomatically;
@property BOOL sendDiagnosticsToApple; // @synthesize sendDiagnosticsToApple;
@property BOOL allowAppleIDPasswordReset; // @synthesize allowAppleIDPasswordReset;
@property BOOL controlsEditable; // @synthesize controlsEditable;
@property BOOL allowAutofill; // @synthesize allowAutofill;
@property(readonly) BOOL useAppleIDAsLogin;
- (BOOL)textView:(id)arg1 clickedOnLink:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)autofill:(id)arg1;
- (id)windowLevelApplicationUIString;
- (BOOL)wantsWindowLevelApplicationUI;
- (void)forwardPaneWithHandler:(CDUnknownBlockType)arg1;
- (void)_presentErrorWithTitle:(id)arg1 message:(id)arg2;
- (void)_autofillShortnameBasedOnFullname;
- (void)controlTextDidEndEditing:(id)arg1;
- (BOOL)validateInputs;
- (void)clearPasswords;
- (void)setLayoutConstraints;
- (void)willBecomeVisible;
@property(readonly) LocalUserAccountManager *manager;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (id)init;
- (void)awakeFromNib;
@property(readonly) BOOL shouldOfferOptions; // @dynamic shouldOfferOptions;
@property(readonly) BOOL shouldOfferLocationServicesOption; // @dynamic shouldOfferLocationServicesOption;
@property(readonly) BOOL shouldOfferDiagnosticInfoOption; // @dynamic shouldOfferDiagnosticInfoOption;
@property(readonly, retain) CloudConfigurationManager *cloudConfigManager; // @dynamic cloudConfigManager;
- (id)previousViewIdentifier;
- (id)nextViewIdentifier;

@end

