//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "iCloudViewControllerBase.h"

@interface iCloudKeychainOptInController : iCloudViewControllerBase
{
    unsigned long long _setupKeychainOrNot;
}

@property unsigned long long setupKeychainOrNot; // @synthesize setupKeychainOrNot=_setupKeychainOrNot;
- (void)forwardPaneWithHandler:(CDUnknownBlockType)arg1;
- (id)init;
- (void)didBecomeVisible;
- (void)willBecomeVisible;
- (id)previousViewIdentifier;
- (id)nextViewIdentifier;

@end

