//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray, NSString;

@protocol MBFirstLoginConfiguration
- (void)completeSetupWithHandler:(void (^)(BOOL, NSError *))arg1 notifyingProgress:(void (^)(float, NSString *))arg2;
- (BOOL)isDiskIOBound;
- (double)maximumTimeToLive;
- (double)estimatedCompletionTime;
- (NSString *)pluginDisplayName;
- (NSString *)pluginIdentifier;

@optional
- (BOOL)canRunBeforeLogin;
- (NSArray *)pluginDependencies;
@end

