//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MigrationHiCloudViewController.h"

@interface MigrationWarnFDEController : MigrationHiCloudViewController
{
}

- (void)willBecomeVisible;
- (void)backwardPaneWithHandler:(CDUnknownBlockType)arg1;
- (void)forwardPaneWithHandler:(CDUnknownBlockType)arg1;
- (id)init;
- (id)nextViewIdentifier;

@end

