//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSAttributedString.h"

@interface NSAttributedString (TruncationExtensions)
- (id)truncatedStringToFit:(float)arg1;
- (id)truncatedStringToFit:(float)arg1 range:(struct _NSRange)arg2;
- (struct _NSRange)adjustRange:(struct _NSRange)arg1;
@end

