//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class _NCMachSendRight, _NCWidgetServiceViewController;

@interface _NCWidgetContainerView : NSView
{
    _Bool _inSetFrame;
    _NCMachSendRight *_currentFence;
    _Bool _sendFrameChangesToHost;
    _NCWidgetServiceViewController *_owner;
}

@property _Bool sendFrameChangesToHost; // @synthesize sendFrameChangesToHost=_sendFrameChangesToHost;
@property __weak _NCWidgetServiceViewController *owner; // @synthesize owner=_owner;
- (void).cxx_destruct;
- (void)setFrame:(struct CGRect)arg1;

@end

