//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSExtensionContext.h"

#import "NCPlugInProtocol.h"
#import "NSXPCListenerDelegate.h"

@class NCWidgetExtensionContext, NCWidgetViewService, NSBundle, NSObject<OS_dispatch_source>, NSString, _NCWidgetServiceViewController;

@interface NCPlugIn : NSExtensionContext <NSXPCListenerDelegate, NCPlugInProtocol>
{
    CDUnknownBlockType _readyBlock;
    NSBundle *_mainBundle;
    struct __CFBundle *_mainCFBundle;
    double _deathTime;
    _Bool _active;
    _Bool _activeForSnapshotOnly;
    NSObject<OS_dispatch_source> *_snapshot_timer;
    _NCWidgetServiceViewController *_topViewController;
    _Bool _wasEditing;
    _Bool _initailWidgetUpdateComplete;
    long long _widgetMode;
    NCWidgetViewService *_viewService;
    struct CGSize _maxSize;
    CDStruct_3c058996 _marginInset;
}

+ (void)initialize;
+ (id)_extensionAuxiliaryVendorProtocol;
+ (id)_extensionAuxiliaryHostProtocol;
@property _Bool initailWidgetUpdateComplete; // @synthesize initailWidgetUpdateComplete=_initailWidgetUpdateComplete;
@property(retain) NCWidgetViewService *viewService; // @synthesize viewService=_viewService;
@property(readonly) CDStruct_3c058996 marginInset; // @synthesize marginInset=_marginInset;
@property(readonly) struct CGSize maxSize; // @synthesize maxSize=_maxSize;
@property(readonly) NSBundle *mainBundle; // @synthesize mainBundle=_mainBundle;
@property(nonatomic) long long widgetMode; // @synthesize widgetMode=_widgetMode;
- (void).cxx_destruct;
- (void)invalidateViewControllers;
- (void)_stopEditMode;
- (BOOL)_startEditMode;
- (void)simulateCrash;
- (void)requestEditMode:(long long)arg1;
- (void)requestSnapshot:(double)arg1;
- (void)_sendSnapshoData:(id)arg1 scale:(double)arg2 result:(unsigned long long)arg3;
- (void)_getSnapshotAsLayer:(_Bool)arg1 result:(unsigned long long)arg2;
- (void)_exitOnTimeout;
- (void)deactivateNow;
- (void)changeDisplay:(unsigned int)arg1;
- (void)changeActiveState:(_Bool)arg1;
- (void)remoteViewReadyForDisplay:(unsigned int)arg1 block:(CDUnknownBlockType)arg2;
- (void)configureDeathTimeout:(double)arg1 leftMargin:(double)arg2 maxSize:(struct CGSize)arg3 enabledLogging:(_Bool)arg4 defaults:(id)arg5 reply:(CDUnknownBlockType)arg6;
@property(readonly) NCWidgetExtensionContext *extensionContext;
@property(readonly) _NCWidgetServiceViewController *topViewController;
@property(readonly) id hostPrincipal;
- (id)rootObjectForPlugIn:(id)arg1;
- (id)initWithInputItems:(id)arg1 listenerEndpoint:(id)arg2 contextUUID:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

