//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@interface NSView (_NCViewExtensions)
- (void)addSubview:(id)arg1 withInsets:(CDStruct_3c058996)arg2;
@end

