//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

#import "ECCoverFlowItem.h"
#import "ECEventHandling.h"

@class ECCoverFlowLabelLayer, NSString;

@interface ECCoverFlowItemLayer : CALayer <ECEventHandling, ECCoverFlowItem>
{
    CALayer *_imageLayer;
    ECCoverFlowLabelLayer *_labelLayer;
    CALayer *_highlightLayer;
    CALayer *_transformLayer;
    float _scaleFactor;
    unsigned int _highlighted:1;
    unsigned int _needsUpdate:1;
}

@property(nonatomic) BOOL needsUpdate; // @synthesize needsUpdate=_needsUpdate;
@property(nonatomic) BOOL highlighted; // @synthesize highlighted=_highlighted;
@property(readonly, nonatomic) ECCoverFlowLabelLayer *labelLayer; // @synthesize labelLayer=_labelLayer;
@property(readonly, nonatomic) CALayer *imageLayer; // @synthesize imageLayer=_imageLayer;
@property(readonly, nonatomic) CALayer *transformLayer; // @synthesize transformLayer=_transformLayer;
- (void).cxx_destruct;
- (id)maskLayerForHighlight;
- (void)layout;
- (struct CGRect)frameForHighlight;
- (void)setContentFromDataSource:(id)arg1 atIndex:(unsigned long long)arg2 withItemInfo:(id)arg3;
- (id)initWithScaleFactor:(float)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

