//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ECSBLabelLayer.h"

@interface ECSBProgressLabelLayer : ECSBLabelLayer
{
}

- (id)initWithString:(id)arg1 andScaleFactor:(float)arg2;

@end

