//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AUCodeSigning : NSObject
{
}

+ (BOOL)codeSignURL:(id)arg1 withIdentity:(id)arg2 error:(out id *)arg3;
+ (void)addMenuItemsToPopUpCell:(id)arg1;
+ (BOOL)isRuntimeOSAppleInternal;
+ (id)codeSignIdentityMenu;
+ (id)codeSigningCertificates;
+ (id)certificateKindForCertificate:(struct OpaqueSecCertificateRef *)arg1;

@end

