//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableCellView.h"

@class MCMessage, MessageListObjectProxy, NSColor;

@interface RichMessageCellBase : NSTableCellView
{
    NSColor *_textColor;
}

+ (id)keyPathsForValuesAffectingTextColor;
+ (id)keyPathsForValuesAffectingMessage;
+ (double)heightWithNumberOfSnippetLines:(unsigned long long)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSColor *textColor; // @synthesize textColor=_textColor;
@property(readonly, nonatomic) MCMessage *message;
- (void)setBackgroundStyle:(long long)arg1;

// Remaining properties
@property(retain) MessageListObjectProxy *objectValue;

@end

