//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AVCaptureDevice.h"

@interface AVCaptureDevice (PhotoBoothAdditions)
+ (id)inputCameraDevices;
@property(readonly) BOOL canOpenCamera;
@property(readonly) BOOL hasAudioMedia;
@property(readonly) BOOL hasVideoMedia;
@property(readonly) BOOL isBuiltIn;
@end

