//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVCaptureAudioDataOutputSampleBufferDelegate.h"
#import "AVCaptureVideoDataOutputSampleBufferDelegate.h"

@class AVCaptureAudioDataOutput, AVCaptureDevice, AVCaptureDeviceFormat, AVCaptureSession, FPS, NSMenu, NSObject<OS_dispatch_queue>, NSString, PBCaptureSession;

@interface CameraController : NSObject <AVCaptureVideoDataOutputSampleBufferDelegate, AVCaptureAudioDataOutputSampleBufferDelegate>
{
    PBCaptureSession *_captureSession;
    AVCaptureAudioDataOutput *_audioDataOutput;
    int _cameraStatus;
    struct CGSize _captureSize;
    AVCaptureDeviceFormat *_captureFormat;
    BOOL _videoPaused;
    FPS *_droppedFps;
    NSMenu *_cameraMenu;
    id _delegate;
    BOOL _performedInitialAddAnyDevice;
    NSObject<OS_dispatch_queue> *_videoCaptureQueue;
    NSObject<OS_dispatch_queue> *_audioCaptureQueue;
}

+ (id)sharedCameraController;
@property BOOL videoPaused; // @synthesize videoPaused=_videoPaused;
@property int cameraStatus; // @synthesize cameraStatus=_cameraStatus;
@property(readonly) AVCaptureSession *captureSession; // @synthesize captureSession=_captureSession;
@property id delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)avCaptureRuntimeError:(id)arg1;
- (void)_captureDeviceNotification:(id)arg1;
- (void)_captureDeviceNotificationMainThread:(id)arg1;
- (void)_captureDeviceWasConnected:(id)arg1;
- (void)_captureDeviceWasDisconnected:(id)arg1;
- (void)_updateVideoCapture;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
@property BOOL audioEnabled;
@property BOOL videoRunning;
@property(retain) AVCaptureDevice *captureDevice;
@property(retain) AVCaptureDevice *userDevice;
- (void)_setupOutputWithFormat:(id)arg1;
- (void)_addAudioDeviceToRecordingSession;
- (struct CGSize)captureSize;
- (id)captureFormat;
- (void)setupCaptureSizeWithFormat:(id)arg1;
- (id)bestDimensionsForCameraInputDevice:(id)arg1;
- (void)_addAnyCaptureDevice;
- (void)addAnyCaptureDeviceForLaunch;
- (void)dealloc;
- (id)init;
- (BOOL)validateMenuItem:(id)arg1;
- (void)menu:(id)arg1 willHighlightItem:(id)arg2;
- (void)menuDidClose:(id)arg1;
- (void)menuWillOpen:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;
- (void)_menuCameraSelected:(id)arg1;
- (void)awakeFromNib;
- (void)_repositionCameraMenu;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

