//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, PBCountdownView;

@interface PBCountdownController : NSObject
{
    PBCountdownView *ibCountdownView;
    NSMutableArray *_timers;
}

+ (long long)countdownStepCount;
+ (id)defaultCountdownController;
- (void).cxx_destruct;
- (void)cancel;
- (void)resetCameraImage:(id)arg1;
- (void)countdownFinished;
- (void)start;
- (void)delayCountDownStart;
- (id)countDownView;
- (void)dealloc;
- (id)init;
- (void)setCameraFrame:(long long)arg1;

@end

