//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PBDarkWakeHelper : NSObject
{
    id <PBDarkWakeHelperDelegate> _delegate;
    struct __CFRunLoopSource *_ioRunLoopSource;
}

+ (BOOL)screenShieldIsRaised;
@property(nonatomic) struct __CFRunLoopSource *ioRunLoopSource; // @synthesize ioRunLoopSource=_ioRunLoopSource;
@property __weak id <PBDarkWakeHelperDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

