//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindow.h"

#import "NSSharingServiceDelegate.h"
#import "NSSharingServicePickerDelegate.h"
#import "NSWindowDelegate.h"

@class CALayer, NSButton, NSLayoutConstraint, NSString, PBCountdownView, PBEmbossedTextField, PBFullscreenBorderView, PBMetalSwitcher, PBProfileController, PBRecordingTimerView, PBShutterButton, PBTabViewWithGradientBackground, PBTextureView, PBTransitionWindow, PBTrayView, PBView, QLAnimationWindowEffect;

@interface PBMainWindow : NSWindow <NSWindowDelegate, NSSharingServiceDelegate, NSSharingServicePickerDelegate>
{
    PBView *videoView;
    PBTabViewWithGradientBackground *tabView;
    PBCountdownView *countDownView;
    PBTextureView *textureView;
    PBTrayView *trayView;
    PBEmbossedTextField *statusView;
    PBMetalSwitcher *recordingSwitcher;
    PBMetalSwitcher *recordingSwitcherInStillTab;
    PBShutterButton *recordShutterButton;
    PBShutterButton *stillImageShutterButton;
    NSButton *fullscreenEffectsButton;
    NSButton *fullscreenShareButton;
    NSButton *stopRecordingButton;
    PBRecordingTimerView *recordingTimerView;
    NSLayoutConstraint *trayHeight;
    NSButton *shareButton;
    struct CGRect _windowFrame;
    struct CGRect _windowVideoViewFrame;
    struct CGRect _windowTrayBoxFrame;
    struct CGRect _windowTabViewFrame;
    BOOL _isFullScreen;
    BOOL _usesTextureUIStyle;
    BOOL _usesFullscreenLayout;
    BOOL _isAnimating;
    BOOL _isChangingLayout;
    CALayer *_pulsingGlowLayer;
    QLAnimationWindowEffect *_effect;
    PBFullscreenBorderView *_videoFullscreenBorderView;
    PBTransitionWindow *_transitionWindow;
    PBProfileController *_profileController;
    double _defaultTrayHeight;
}

+ (double)fullScreenTransitionDuration;
+ (id)photoBoothWindowScreen;
@property(readonly, nonatomic) __weak PBView *videoView; // @synthesize videoView;
@property(readonly, nonatomic) BOOL usesTextureUIStyle; // @synthesize usesTextureUIStyle=_usesTextureUIStyle;
- (void).cxx_destruct;
- (void)sheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)changeProfileSheet:(id)arg1;
- (id)sharingService:(id)arg1 sourceWindowForShareItems:(id)arg2 sharingContentScope:(long long *)arg3;
- (id)sharingService:(id)arg1 transitionImageForShareItem:(id)arg2 contentRect:(struct CGRect *)arg3;
- (struct CGRect)sharingService:(id)arg1 sourceFrameOnScreenForShareItem:(id)arg2;
- (id)sharingServicePicker:(id)arg1 delegateForSharingService:(id)arg2;
- (id)sharingServicePicker:(id)arg1 sharingServicesForItems:(id)arg2 proposedSharingServices:(id)arg3;
- (void)shareButtonClicked:(id)arg1;
- (id)textureView;
@property(readonly, nonatomic) BOOL isAnimating;
- (void)restoreStateWithCoder:(id)arg1;
- (void)windowDidExitFullScreen:(id)arg1;
- (void)window:(id)arg1 startCustomAnimationToExitFullScreenWithDuration:(double)arg2;
- (void)windowWillExitFullScreen:(id)arg1;
- (void)windowDidEnterFullScreen:(id)arg1;
- (void)windowWillEnterFullScreen:(id)arg1;
@property(readonly) BOOL isFullScreen;
- (struct CGSize)window:(id)arg1 willUseFullScreenContentSize:(struct CGSize)arg2;
- (void)toggleFullScreen:(id)arg1;
- (struct CGRect)rightSideAreaForShutterFrame:(struct CGRect)arg1 controlsFrame:(struct CGRect)arg2;
@property(readonly, nonatomic) double emptyHorizontalEdgeWidth;
- (struct CGRect)fullScreenFrame;
- (struct CGImage *)createSnapshotWithFrame:(struct CGRect *)arg1;
- (struct CGSize)windowWillResize:(id)arg1 toSize:(struct CGSize)arg2;
- (void)setFrame:(struct CGRect)arg1 display:(BOOL)arg2;
- (double)_windowWidthForHeight:(double)arg1;
- (void)changeLayoutToFullScreen:(BOOL)arg1;
- (void)_changeLayoutToFullScreen:(BOOL)arg1 withFrame:(struct CGRect)arg2;
- (void)setUsesTextureUIStyle:(BOOL)arg1;
- (struct CGRect)videoViewRect;
- (struct CGRect)rightSideFrame;
- (struct CGRect)leftSideFrame;
- (BOOL)validateMenuItem:(id)arg1;
- (BOOL)isResizable;
- (void)awakeFromNib;
- (struct CGRect)horizontallyCenteredRect:(struct CGRect)arg1 inView:(id)arg2;
- (void)saveWindowUIFrames;
- (void)_preloadFullscreenTextureWithSize:(struct CGSize)arg1;
- (void)preloadFullscreenTexture;
- (void)prefetchImageNamed:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

