//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSScrollView.h"

@interface PBOverlayScrollView : NSScrollView
{
}

- (void)tile;
- (void)setScrollerStyle:(long long)arg1;
- (BOOL)drawsBackground;
- (BOOL)isOpaque;
- (BOOL)wantsDefaultClipping;

@end

