//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSSharingServiceDelegate.h"
#import "NSTableViewDataSource.h"
#import "NSTableViewDelegate.h"

@class IKPTCropView, NSArray, NSButton, NSLayoutConstraint, NSMutableArray, NSPanel, NSProgressIndicator, NSString, NSTableView, NSTextField, ServiceCell;

@interface PBProfileController : NSObject <NSTableViewDataSource, NSTableViewDelegate, NSSharingServiceDelegate>
{
    NSMutableArray *_services;
    ServiceCell *_messageServiceCell;
    ServiceCell *_contactUserServiceCell;
    BOOL _isInitializing;
    IKPTCropView *_cropView;
    NSPanel *_panel;
    NSButton *_cancelButton;
    NSButton *_setButton;
    NSProgressIndicator *_progressIndicator;
    NSTableView *_servicesView;
    NSTextField *_chooseLabel;
    NSArray *_topLevelObjects;
    NSLayoutConstraint *_serviceTableViewHeightConstraint;
}

+ (id)nameOfService:(id)arg1;
@property(retain) NSLayoutConstraint *serviceTableViewHeightConstraint; // @synthesize serviceTableViewHeightConstraint=_serviceTableViewHeightConstraint;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 dataCellForTableColumn:(id)arg2 row:(long long)arg3;
- (void)tableView:(id)arg1 setObjectValue:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)sharingService:(id)arg1 didShareItems:(id)arg2;
- (void)sharingService:(id)arg1 didFailToShareItems:(id)arg2 error:(id)arg3;
- (void)sharingService:(id)arg1 willShareItems:(id)arg2;
- (void)_setupShareServices;
- (void)_addCustomUserAccountAndContactsService;
- (void)_addCustomMessagesService;
- (void)_setMessagesPicture;
- (void)_setContactPicture;
- (id)servicesWithUploadStatus:(long long)arg1;
- (void)setImage:(id)arg1;
- (void)showSheetInWindow:(id)arg1 didEndSelector:(SEL)arg2;
- (void)upload:(id)arg1;
- (void)endSheet:(id)arg1;
- (id)_cellForService:(id)arg1;
- (void)_updateView;
- (void)dealloc;
- (void)rowClicked:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

