//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ABAbstractMainWindowViewModelUIAction.h"

@interface ABAddContactUIAction : ABAbstractMainWindowViewModelUIAction
{
    id <ABPersonMergingControllerDelegate> _mergeDelegate;
}

- (void)performWithSender:(id)arg1;
- (BOOL)validateWithMenuItem:(id)arg1;
- (void)dealloc;
- (id)initWithMainWindowViewModel:(id)arg1 mergeDelegate:(id)arg2;

@end

