//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ABGroupActionHelper.h"

@class ABAccount, ABGroup, NSArray, NSString;

@interface ABBookGroupImportFilesHelper : NSObject <ABGroupActionHelper>
{
    ABAccount *_account;
    ABGroup *_group;
    NSArray *_filenames;
    id <ABPersonMergingControllerDelegate> _mergeDelegate;
    id <ABCommandExecutor> _commandExecutor;
    BOOL _showImportConfirmation;
}

- (void)performAction;
- (id)importActionName;
- (void)dealloc;
- (id)initWithAccount:(id)arg1 group:(id)arg2 filenames:(id)arg3 mergeDelegate:(id)arg4 commandExecutor:(id)arg5 showConfirmation:(BOOL)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

