//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ABMainWindowEditModeController.h"

@class ABCardView, ABContactPaneButtonController, NSArray, NSString;

@interface ABCardEditModeController : NSObject <ABMainWindowEditModeController>
{
    ABCardView *_cardView;
    ABContactPaneButtonController *_buttonController;
    NSArray *_tokens;
}

@property(readonly, nonatomic) BOOL canEdit;
- (void)toggleEditing;
@property(nonatomic, getter=isEditing) BOOL editing;
- (void)updateButtonVisibility:(id)arg1;
- (void)dealloc;
- (id)subscribeToKeyPathsOfCardView:(id)arg1;
- (id)initWithCardView:(id)arg1 buttonControler:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

