//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class ABColoredView, NSVisualEffectView;

@interface ABCleanPersonListBackgroundView : NSView
{
    NSVisualEffectView *_visualEffectView;
    ABColoredView *_coloredView;
}

- (void)showTranslucentBackground;
- (void)showColoredBackground;
- (void)setBackgroundMaterial:(long long)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)applyInitialConstraints;
- (id)initWithFrame:(struct CGRect)arg1;

@end

