//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ABEncodingPopUpButton, NSArray, NSMatrix, NSView;

@interface ABEncodingManager : NSObject
{
    NSMatrix *encodingMatrix;
    NSArray *encodings;
    ABEncodingPopUpButton *encodingPopupButton;
    NSView *encodingAccessory;
}

+ (BOOL)isEncodingASCIICompatible:(unsigned long long)arg1;
+ (id)allAvailableStringEncodings;
+ (id)sharedInstance;
- (void)revertToDefault:(id)arg1;
- (void)selectAll:(id)arg1;
- (void)clearAll:(id)arg1;
- (void)encodingListChanged:(id)arg1;
- (void)showPanel:(id)arg1;
- (BOOL)worksWhenModal;
- (id)encodingAccessory:(unsigned long long)arg1 includeDefaultEntry:(BOOL)arg2 encodingPopUp:(id *)arg3;
- (void)noteEncodingListChange:(BOOL)arg1 updateList:(BOOL)arg2 postNotification:(BOOL)arg3;
- (id)enabledEncodings;
- (void)setupPopUp:(id)arg1 selectedEncoding:(unsigned long long)arg2 withDefaultEntry:(BOOL)arg3;
- (void)setupEncodingsList;

@end

