//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ABApplicationScriptingModel.h"

@class ABExportArchiveService, ABMainWindowViewModel, NSString;

@interface ABMainWindowScriptingModel : NSObject <ABApplicationScriptingModel>
{
    ABMainWindowViewModel *_mainWindowViewModel;
    ABExportArchiveService *_exportArchiveService;
}

- (void)setSelectedRecords:(id)arg1;
- (id)selectedRecords;
- (void)setSelectedGroup:(id)arg1;
- (id)selectedGroup;
- (void)setSelectedGroups:(id)arg1;
- (id)selectedGroups;
- (void)exportToPath:(id)arg1;
- (void)dealloc;
- (id)initWithMainWindowViewModel:(id)arg1 exportArchiveService:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

