//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ABAddressBook, ABPersistentStoreCoordinatorCache, NSString;

@interface ABRestoreBackupTask : NSObject
{
    id <ABRestoreBackupDelegate> _delegate;
    NSString *_path;
    ABAddressBook *_addressBook;
    ABPersistentStoreCoordinatorCache *_coordinatorCache;
    BOOL _worked;
}

@property(readonly, copy) NSString *path; // @synthesize path=_path;
- (void)run;
- (void)restoreBackup;
- (void)forceServerSync;
- (void)forceSyncServicesSync;
- (void)forceASync;
- (void)resetSyncAnchorsIfNeeded;
- (void)restoreFromMetadataIfNeeded;
- (void)resetAddressBook;
- (void)copyOverNewFiles;
- (void)copySourcesDirectory;
- (void)copyImagesFolder;
- (void)copyMailRecents;
- (void)copyMainDatabase;
- (void)copyMetadataDirectory;
- (void)removeExistingFiles;
- (void)removeMetadataDirectory;
- (void)removeMainDatabase;
- (void)removeMailRecentsDatabase;
- (void)removeLastImportGroup;
- (void)removeImagesFolder;
- (void)startMetadataController;
- (void)stopMetaDataController;
- (void)dealloc;
- (id)initWithPath:(id)arg1 addressBook:(id)arg2 coordinatorCache:(id)arg3 delegate:(id)arg4;
- (id)init;

@end

