//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSButton, NSPopUpButton;

@interface ABShortNamePreferencesController : NSObject
{
    NSPopUpButton *_formatPopupButton;
    NSButton *_preferNicknameCheckbox;
}

@property NSButton *preferNicknameCheckbox; // @synthesize preferNicknameCheckbox=_preferNicknameCheckbox;
@property NSPopUpButton *formatPopupButton; // @synthesize formatPopupButton=_formatPopupButton;
- (void)togglePreferNicknames:(id)arg1;
- (void)updateFormat:(id)arg1;
- (void)restorePreferNicknamesPreference;
- (void)setShortNameStyleInPreferences:(unsigned long long)arg1;
- (unsigned long long)shortNameStyleFromPreferences;
- (void)restoreShortNameStyleFromPreferences;
- (void)restoreFromPreferences;
- (void)configurePreferNicknamesCheckbox;
- (void)addMenuWithTitle:(id)arg1 shortNameStyle:(unsigned long long)arg2;
- (void)configureFormatPopup;
- (void)configureControls;
- (void)awakeFromNib;

@end

