//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ABAccountFactoryDelegate.h"

@class NSMutableDictionary, NSString;

@interface ABTimeMachineAddressBookCache : NSObject <ABAccountFactoryDelegate>
{
    NSMutableDictionary *_addressBooksByPath;
    NSMutableDictionary *_accountsByPath;
    NSMutableDictionary *_coordinatorCachesByPath;
    NSMutableDictionary *_accountRepositoriesByPath;
}

+ (BOOL)isPathLiveAddressBook:(id)arg1;
- (void)accountFactory:(id)arg1 willCreateAccountFromBuilder:(id)arg2;
- (id)accountsForSnapshotPath:(id)arg1;
- (id)makeAccountCollectionForSnapshotPath:(id)arg1;
- (id)accountCollectionForSnapshotPath:(id)arg1;
- (id)makeCoordinatorCacheForSnapshotPath:(id)arg1;
- (id)coordinatorCacheForSnapshotPath:(id)arg1;
- (id)makeAddressBookForSnapshotPath:(id)arg1;
- (id)addressBookForSnapshotPath:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

