//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ABAddressBook, ABTimeMachineRestoreSource, NSArray, NSString, NSWindow;

@protocol ABTimeMachineWindowController <NSObject>
- (id <CNObservable>)windowAppearanceObservable;
- (id <ABTimeMachineWindowController>)cloneTimeMachineWindowController;
- (void)updateViewStateFromViewer:(id <ABTimeMachineWindowController>)arg1;
- (id <ABPersonMergingControllerDelegate>)mergeDelegate;
- (ABTimeMachineRestoreSource *)restoreSourceFromCurrentSelection;
- (void)setSearchString:(NSString *)arg1;
- (NSString *)searchString;
- (void)selectGroupEntryWithIdentifier:(NSString *)arg1;
- (NSString *)selectedGroupEntryIdentifier;
- (void)selectRecordsWithUIDs:(NSArray *)arg1;
- (NSArray *)selectedRecordUIDs;
- (void)setReadOnlyOverride:(BOOL)arg1;
- (BOOL)readOnlyOverride;
- (ABAddressBook *)addressBook;
- (NSWindow *)window;
- (void)viewTimeMachineAccounts:(NSArray *)arg1 addressBook:(ABAddressBook *)arg2;
- (void)restoreStateFromRetargeting;
- (void)saveStateForRetargeting;
- (void)applicationDidExitTimeMachine;
- (void)applicationWillEnterTimeMachine;
@end

