//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ABWindow : NSObject
{
}

+ (void)writeImageOfWindow:(id)arg1 toUrl:(id)arg2;
+ (id)bitmapRepresentationForWindow:(id)arg1;

@end

