//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSXPCConnection;

@interface ABInternetAccountsi386 : NSObject
{
    NSXPCConnection *_connection;
    id <ABInternetAccountsi386Protocol> _agent;
}

+ (id)shared;
- (id)clientAuthTokenForEmailAddress:(id)arg1;
- (id)brandingProviderInfoForAccountSettings:(id)arg1;
- (BOOL)shouldSendClientInfoHeaderForAccountSettings:(id)arg1;
- (id)accountBadgeForAccountSettings:(id)arg1;
- (id)aListPluginIDForAccountSettings:(id)arg1;
- (BOOL)aListPluginRequiresSeparateBirthdayCalendar:(id)arg1;
- (id)defaultDescriptionForAccountSettings:(id)arg1;
- (id)protectedSocialProfileServicesForPluginID:(id)arg1;
- (void)accountsChangedExternally;
- (void)dealloc;
- (id)init;

@end

