//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MessagesEventControllerHandler.h"

@class NSDate;

@interface ApplicationActionsControllerHandler : NSObject <MessagesEventControllerHandler>
{
    NSDate *_lastLoggedInDate;
}

+ (id)sharedInstance;
- (id)performActionsForEvent:(int)arg1 withIMHandle:(id)arg2 withObject:(id)arg3 withChat:(id)arg4 silent:(BOOL)arg5;
- (void)dealloc;

@end

