//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class AVChat, AVChatParticipant, NSData;

@protocol AVChatLegacyDelegate

@optional
- (NSData *)avChat:(AVChat *)arg1 bitmapDataForParticipant:(AVChatParticipant *)arg2;
@end

