//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SOAVPopUpButtonViewController.h"

@interface AVPopUpButtonViewController : SOAVPopUpButtonViewController
{
}

- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)buildMenuWithUpdateBlock:(CDUnknownBlockType)arg1;
- (id)initWithAVOptions:(unsigned long long)arg1 image:(id)arg2 title:(id)arg3;
- (void)_avVideoCapabilitiesDidChange:(id)arg1;
- (void)_commonAVPopUpButtonViewControllerInit;
- (void)legacyShareRemoteScreen:(id)arg1;
- (void)legacyShareMyScreen:(id)arg1;
- (void)inviteToLegacyAudioChat:(id)arg1;
- (void)inviteToLegacyVideoChat:(id)arg1;

@end

