//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMFileTransfer.h"

@interface IMFileTransfer (ScriptingAdditions)
- (id)objectSpecifier;
- (void)declineTransferCommand:(id)arg1;
- (void)acceptTransferCommand:(id)arg1;
- (id)scriptStarted;
- (id)scriptTransferStatus;
- (id)scriptSecure;
- (id)scriptTransferProgress;
- (id)scriptTransferSize;
- (id)scriptParticipant;
- (id)scriptFilePath;
- (id)scriptService;
- (id)scriptDirection;
- (id)scriptName;
- (id)scriptID;
@end

