//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMMessagePartChatItem.h"

@interface IMMessagePartChatItem (FezCopyAdditions)
- (BOOL)_isSafeToCopy;
- (id)_dictRepresentation;
- (id)_dictRepresentationGivenStartOffset:(unsigned long long)arg1 andEndOffset:(unsigned long long)arg2;
- (struct _NSRange)_rangeforString:(id)arg1 givenStartOffset:(unsigned long long)arg2 withEndOffset:(unsigned long long)arg3;
@end

