//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class IMHandle, NSDictionary;

@protocol MessagesEventControllerHandler
- (NSDictionary *)performActionsForEvent:(int)arg1 withIMHandle:(IMHandle *)arg2 withObject:(id)arg3 withChat:(id)arg4 silent:(BOOL)arg5;
@end

