//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSRecursiveLock.h"

@interface NSRecursiveLock (PrivateAdditions)
- (void)unlockFromLine:(int)arg1;
- (BOOL)lockBeforeTimeout:(double)arg1 fromLine:(int)arg2;
@end

