//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindow.h"

@interface NSWindow (iChatFrameSavingAdditions)
- (void)restoreWindowPositionUsingName:(id)arg1 restoreWidth:(BOOL)arg2 restoreHeight:(BOOL)arg3 defaultHeight:(int)arg4;
- (BOOL)hasSavedPositionUsingName:(id)arg1;
- (void)saveWindowPositionUsingName:(id)arg1 saveWidth:(BOOL)arg2 saveHeight:(BOOL)arg3;
@end

