//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SystemSound : NSObject
{
    unsigned int _soundID;
    id _delegate;
    unsigned int _delgateRespondsToSoundFinishedPlaying:1;
}

+ (id)soundForPath:(id)arg1;
- (void)play;
- (void)_finishedPlaying;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (void)dealloc;
- (id)_initWithSystemSoundID:(unsigned int)arg1;

@end

