//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBBackgroundView.h"

@class NSArray;

@interface FBMultiPreviewView : FBBackgroundView
{
    NSArray *_faces;
}

@property(copy) NSArray *faces; // @synthesize faces=_faces;
- (id)defaultFace;
- (void)updateFaces:(id)arg1;
- (void)dealloc;

@end

