//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOutlineView.h"

@interface FBOutlineView : NSOutlineView
{
}

- (void)print:(id)arg1;
- (void)expandAllItems;
- (void)textDidEndEditing:(id)arg1;
- (BOOL)preservesContentDuringLiveResize;
- (void)keyDown:(id)arg1;
- (BOOL)_shouldHeaderShowSeparatorForColumn:(long long)arg1;
- (unsigned long long)draggingSourceOperationMaskForLocal:(BOOL)arg1;
- (void)awakeFromNib;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_adjustUIForRTL;

@end

