//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BrailleDisplayTabController.h"

@class NSTextField;

__attribute__((visibility("hidden")))
@interface BrailleDisplayBluetoothTabController : BrailleDisplayTabController
{
    NSTextField *_bluetoothNameLabel;
    NSTextField *_bluetoothNameValue;
    NSTextField *_bluetoothAddressValue;
}

- (void)setBluetoothAddress:(id)arg1;
- (void)setBluetoothName:(id)arg1;

@end

