//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSImage, NSString;

__attribute__((visibility("hidden")))
@interface DecoratedTableItem : NSObject <NSCopying>
{
    NSString *_text;
    NSImage *_image;
}

+ (id)decoratedTableCellItemWithText:(id)arg1 andImage:(id)arg2;
- (id)image;
- (id)text;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithText:(id)arg1 andImage:(id)arg2;

@end

