//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSLayoutConstraint, NSTextField, NSView;

@interface SOProgressBarViewController : NSObject
{
    BOOL _iMessageable;
    BOOL _animatingSendingText;
    BOOL _hasSendingTextDisplayed;
    id <SOProgressBarViewControllerSendingTextDelegate> _sendingTextDelegate;
    NSView *_sendingView;
    NSView *_sendingTextContainingView;
    NSTextField *_simpleSendingTextLabel;
    NSTextField *_detailedSendingTextLabelEven;
    NSTextField *_detailedSendingTextLabelOdd;
    NSView *_progressBarView;
    NSLayoutConstraint *_progressBarViewWidthConstraint;
    unsigned long long _previousSendingCount;
    unsigned long long _previousTotalCount;
    NSDictionary *_sendingLabelAttributes;
}

@property(retain) NSDictionary *sendingLabelAttributes; // @synthesize sendingLabelAttributes=_sendingLabelAttributes;
@property unsigned long long previousTotalCount; // @synthesize previousTotalCount=_previousTotalCount;
@property unsigned long long previousSendingCount; // @synthesize previousSendingCount=_previousSendingCount;
@property BOOL hasSendingTextDisplayed; // @synthesize hasSendingTextDisplayed=_hasSendingTextDisplayed;
@property BOOL animatingSendingText; // @synthesize animatingSendingText=_animatingSendingText;
@property(retain) NSLayoutConstraint *progressBarViewWidthConstraint; // @synthesize progressBarViewWidthConstraint=_progressBarViewWidthConstraint;
@property(retain) NSView *progressBarView; // @synthesize progressBarView=_progressBarView;
@property(retain) NSTextField *detailedSendingTextLabelOdd; // @synthesize detailedSendingTextLabelOdd=_detailedSendingTextLabelOdd;
@property(retain) NSTextField *detailedSendingTextLabelEven; // @synthesize detailedSendingTextLabelEven=_detailedSendingTextLabelEven;
@property(retain) NSTextField *simpleSendingTextLabel; // @synthesize simpleSendingTextLabel=_simpleSendingTextLabel;
@property(retain) NSView *sendingTextContainingView; // @synthesize sendingTextContainingView=_sendingTextContainingView;
@property(retain) NSView *sendingView; // @synthesize sendingView=_sendingView;
@property(nonatomic, setter=setiMessageable:) BOOL iMessageable; // @synthesize iMessageable=_iMessageable;
@property(nonatomic) __weak id <SOProgressBarViewControllerSendingTextDelegate> sendingTextDelegate; // @synthesize sendingTextDelegate=_sendingTextDelegate;
- (void).cxx_destruct;
- (void)didDisplaySendingText:(CDUnknownBlockType)arg1 completionBlock:(CDUnknownBlockType)arg2 animate:(BOOL)arg3;
- (void)willDisplaySendingText:(CDUnknownBlockType)arg1 completionBlock:(CDUnknownBlockType)arg2 animate:(BOOL)arg3;
- (void)setProgressValue:(double)arg1 oldProgress:(double)arg2 sending:(unsigned long long)arg3 total:(unsigned long long)arg4 animate:(BOOL)arg5;
- (void)finish;
- (void)setup;
- (double)_sendingViewWidth;
- (void)_finishSendingView;
- (void)_fadeOutSendingView;
- (void)_setupSendingView;
- (void)_updateProgressBarConstraintWithMultiplier:(double)arg1;
- (void)_setProgressValue:(double)arg1 oldProgress:(double)arg2 animate:(BOOL)arg3;
- (void)_resetProgressBarColor;
- (void)_finishProgressBar;
- (void)_resetProgressBar;
- (void)_setupProgressBar;
- (void)_resetDetailedSendingText;
- (void)_setupDetailedSendingText;
- (void)_resetSimpleSendingText;
- (void)_setupSimpleSendingText;
- (void)_displaySendingTextCallback:(CDUnknownBlockType)arg1 completionBlock:(CDUnknownBlockType)arg2 before:(BOOL)arg3 animate:(BOOL)arg4;
- (void)_setSending:(unsigned long long)arg1 of:(unsigned long long)arg2;
- (void)_resetSendingTextContainingView;
- (void)_setupSendingTextContainingView;
- (void)awakeFromNib;
- (id)init;

@end

