//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSLayoutConstraint, NSString, TMACollectionViewItem;

@interface TMACollectionReusableView : NSView
{
    NSLayoutConstraint *_xConstraint;
    NSLayoutConstraint *_yConstraint;
    NSLayoutConstraint *_widthConstraint;
    NSLayoutConstraint *_heightConstraint;
    BOOL _selected;
    NSString *_reuseIdentifier;
    TMACollectionViewItem *_item;
}

@property(nonatomic, getter=isSelected) BOOL selected; // @synthesize selected=_selected;
@property(retain, nonatomic) TMACollectionViewItem *item; // @synthesize item=_item;
@property(copy, nonatomic) NSString *reuseIdentifier; // @synthesize reuseIdentifier=_reuseIdentifier;
- (void)setEditing:(BOOL)arg1 animation:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
@property(nonatomic) BOOL editing;
@property(readonly, nonatomic) struct CGSize selectionLabelSize;
@property(readonly, nonatomic) NSView *selectionLabelView;
@property(readonly, nonatomic) struct CGRect selectionContentFrame;
@property(readonly, nonatomic) NSView *selectionContentView;
- (void)applyLayoutAttributes:(id)arg1;
- (void)viewDidMoveToSuperview;
- (void)dealloc;

@end

