//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TMACollectionViewRowHeightCache : NSObject
{
    id <TMACollectionViewRowHeightCacheDelegate> _delegate;
    long long _numberOfRows;
    double *_rowHeights;
    BOOL _isValid;
    double _totalHeight;
}

@property(readonly, nonatomic) double totalHeight;
- (void)setHeight:(double)arg1 forRowAtIndex:(long long)arg2;
- (struct CGRect)frameForRowAtIndex:(long long)arg1;
- (long long)rowForHeigth:(double)arg1;
- (double)heightForRowAtIndex:(long long)arg1;
- (void)_cacheRowHeights;
- (void)_ensureRowHeights;
- (void)_createRowHeightsArray;
- (long long)numberOfRows;
- (void)invalidate;
@property(readonly, nonatomic) BOOL isValid;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

@end

