//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <SocialUI/TMACollectionViewItem.h>

@class MLMediaObject, NSImage, NSString;

@interface TMAMovieBrowserMovieItem : TMACollectionViewItem
{
    NSImage *_image;
    MLMediaObject *_mediaObject;
    struct CGSize _imageSize;
}

+ (id)itemWithMediaObject:(id)arg1 indexPath:(id)arg2;
@property(nonatomic) struct CGSize imageSize; // @synthesize imageSize=_imageSize;
@property(retain, nonatomic) MLMediaObject *mediaObject; // @synthesize mediaObject=_mediaObject;
@property(retain, nonatomic) NSImage *image; // @synthesize image=_image;
@property(readonly, nonatomic) NSString *duration;
- (id)displayName;
- (void)dealloc;
- (void)generateThumbnail:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)initWithMediaObject:(id)arg1 indexPath:(id)arg2;

@end

