//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSImageView.h"

@class NSString;

@interface TMAMovieBrowserMovieCellImageView : NSImageView
{
    double _imageBorderWidth;
    NSString *_duration;
}

@property(retain, nonatomic) NSString *duration; // @synthesize duration=_duration;
@property(nonatomic) double imageBorderWidth; // @synthesize imageBorderWidth=_imageBorderWidth;
- (void)drawRect:(struct CGRect)arg1;
- (struct CGSize)selectionSize;
- (void)dealloc;

@end

