//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CWKeychainProxySubsystem, NSXPCConnection;

@interface CWKeychainProxyConnection : NSObject
{
    CWKeychainProxySubsystem *_subsystem;
    NSXPCConnection *_connection;
}

@property(readonly, retain, nonatomic) NSXPCConnection *connection; // @synthesize connection=_connection;
- (void)queryIsWiFiCloudSyncEngineRunningWithReply:(CDUnknownBlockType)arg1;
- (void)removeCloudWiFiProfileWithSSID:(id)arg1 reply:(CDUnknownBlockType)arg2;
- (void)synchronizeWithReply:(CDUnknownBlockType)arg1;
- (void)deleteUserWiFiKeychainPasswordWithSSID:(id)arg1 reply:(CDUnknownBlockType)arg2;
- (void)setUserWiFiKeychainPasswordWithSSID:(id)arg1 password:(id)arg2 reply:(CDUnknownBlockType)arg3;
- (void)queryUserWiFiKeychainPasswordWithSSID:(id)arg1 reply:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)initWithXPCConnection:(id)arg1 subsystem:(id)arg2;

@end

