//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ACDEClient/ACMHTTPAuthenticationHandler.h>

@interface ACMHTTPExternalAuthenticationHandler : ACMHTTPAuthenticationHandler
{
}

- (BOOL)shouldReturnResponse:(id)arg1 orReportError:(id *)arg2;
- (BOOL)updatePublicKeyWithResponse:(id)arg1;

@end

