//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MCRemoteMessage.h"

#import "IMAPMessage.h"

@class NSString;

@interface IMAPMessage : MCRemoteMessage <IMAPMessage>
{
    unsigned int _uid;
}

+ (void)initialize;
- (void)setDataSource:(id)arg1;
- (id)dataSource;
- (id)account;
- (id)subject;
- (id)originalMailboxURLString;
- (id)remoteMailboxURLString;
- (id)remoteID;
- (id)mailboxName;
- (BOOL)isMessageContentsLocallyAvailable;
- (void)setUid:(unsigned int)arg1;
- (unsigned int)uid;
- (id)messageID;
@property(readonly, copy) NSString *description;
- (id)initWithFlags:(unsigned int)arg1 size:(unsigned long long)arg2 uid:(unsigned int)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

