//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL;

@interface LiAccessFile : NSObject
{
    BOOL _wasSecuritySandboxExtensionApplied;
    BOOL _isSecurityAccessed;
    NSString *_uuid;
    NSURL *_url;
    id <LiLibrary> _library;
}

@property(nonatomic) BOOL isSecurityAccessed; // @synthesize isSecurityAccessed=_isSecurityAccessed;
@property(nonatomic) BOOL wasSecuritySandboxExtensionApplied; // @synthesize wasSecuritySandboxExtensionApplied=_wasSecuritySandboxExtensionApplied;
@property(nonatomic) __weak id <LiLibrary> library; // @synthesize library=_library;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
- (void).cxx_destruct;
- (id)description;
- (id)initWithPath:(id)arg1;
- (id)initWithURL:(id)arg1;
- (id)initWithURL:(id)arg1 uuid:(id)arg2 forLibrary:(id)arg3;
- (void)dealloc;

@end

