//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PhotoLibraryPrivate/LiDeleter.h>

@class LiClientConnection;

@interface LiClientDeleter : LiDeleter
{
    LiClientConnection *_connection;
}

@property __weak LiClientConnection *connection; // @synthesize connection=_connection;
- (void).cxx_destruct;
- (void)deleteForModelIds:(id)arg1 forClient:(unsigned long long)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)deleteForModelId:(unsigned long long)arg1 forClient:(unsigned long long)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)initWithTable:(id)arg1 connection:(id)arg2;

@end

