//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LiFileUtils : NSObject
{
}

+ (id)generateSignatureForData:(id)arg1;
+ (void)generateSignatureForPath:(id)arg1 handler:(CDUnknownBlockType)arg2;
+ (id)encodedResourceIdentifierForURL:(id)arg1;
+ (id)resourceIdentifierForURL:(id)arg1;

@end

