//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "LiEncoding.h"
#import "NSCopying.h"

@class LiStringAtom, NSMutableArray, NSString;

@interface LiKeyPath : NSObject <NSCopying, LiEncoding>
{
    LiStringAtom *_keyAtom;
    NSMutableArray *_keyPathComponents;
    NSString *_atomPath;
    id _tagData;
}

@property(retain, nonatomic) id tagData; // @synthesize tagData=_tagData;
- (void).cxx_destruct;
- (void)addStringAtomsToArray:(id)arg1;
- (void)encodeToConsumer:(id)arg1 forLibrary:(id)arg2;
- (id)initWithDataProvider:(id)arg1 forLibrary:(id)arg2;
- (int)LiClassCode;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)isAnyPropertyKeyPath;
- (BOOL)isModelIdKeyPath;
- (long long)compare:(id)arg1;
- (id)atomAtIndex:(unsigned long long)arg1;
- (BOOL)isEquivalentToKeyPath:(id)arg1;
- (BOOL)isEqualToKeyPath:(id)arg1;
- (BOOL)isEqual:(id)arg1;
@property(readonly) unsigned long long hash;
- (long long)atomId;
- (id)atomPath;
- (id)stringValue;
- (id)asString;
- (id)componentAtIndex:(unsigned long long)arg1;
- (id)stringComponentAtIndex:(unsigned long long)arg1;
- (id)lastStringComponent;
- (unsigned long long)count;
- (BOOL)isSimple;
@property(readonly, copy) NSString *description;
- (id)initWithAtomPath:(id)arg1 withAtomCache:(id)arg2;
- (id)initWithPath:(id)arg1 forTable:(id)arg2;
- (id)initWithPath:(id)arg1 withAtomCache:(id)arg2;
- (id)initWithAtomId:(long long)arg1 withAtomCache:(id)arg2;
- (id)initWithAtom:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

