//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "LiEncoding.h"

@class NSString;

@interface LiMessage : NSObject <LiEncoding>
{
    unsigned char _type;
    unsigned char _status;
    long long _sequence;
}

@property(readonly, nonatomic) unsigned char status; // @synthesize status=_status;
@property(readonly, nonatomic) long long sequence; // @synthesize sequence=_sequence;
@property(readonly, nonatomic) unsigned char type; // @synthesize type=_type;
- (void)encodeToConsumer:(id)arg1 forLibrary:(id)arg2;
- (id)initWithDataProvider:(id)arg1 forLibrary:(id)arg2;
- (int)LiClassCode;
- (BOOL)appendToDescription:(id)arg1 forProperty:(SEL)arg2;
- (void)appendPropertiesToDescription:(id)arg1 forClass:(Class)arg2;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) NSString *typeString;
- (id)initWithType:(unsigned char)arg1 sequence:(long long)arg2;
- (id)initWithType:(unsigned char)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

