//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PhotoLibraryPrivate/LiReply.h>

@class LiModelChangeGroup;

@interface LiModelChangeReply : LiReply
{
    unsigned char _changeType;
    LiModelChangeGroup *_changes;
}

@property(nonatomic) unsigned char changeType; // @synthesize changeType=_changeType;
@property(retain, nonatomic) LiModelChangeGroup *changes; // @synthesize changes=_changes;
- (void).cxx_destruct;
- (void)encodeToConsumer:(id)arg1 forLibrary:(id)arg2;
- (id)initWithDataProvider:(id)arg1 forLibrary:(id)arg2;
- (int)LiClassCode;
- (id)initWithReplyStatus:(unsigned char)arg1 forRequest:(id)arg2 changes:(id)arg3 changeType:(unsigned char)arg4;

@end

