//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "LiEncoding.h"

@class LiArgs, LiCanceler, LiDropDef, LiQueryOptions, LiTable, NSArray, NSString;

@interface LiQuery : NSObject <LiEncoding>
{
    LiArgs *_whereClause;
    LiTable *_table;
    LiQueryOptions *_options;
    LiDropDef *_dropDef;
}

+ (id)queryTable:(id)arg1 where:(id)arg2;
+ (id)queryTable:(id)arg1 where:(id)arg2 options:(id)arg3;
@property(retain, nonatomic) LiDropDef *dropDef; // @synthesize dropDef=_dropDef;
@property(retain, nonatomic) LiQueryOptions *options; // @synthesize options=_options;
@property(nonatomic) __weak LiTable *table; // @synthesize table=_table;
@property(retain, nonatomic) LiArgs *whereClause; // @synthesize whereClause=_whereClause;
- (void).cxx_destruct;
- (void)encodeToConsumer:(id)arg1 forLibrary:(id)arg2;
- (id)initWithDataProvider:(id)arg1 forLibrary:(id)arg2;
- (int)LiClassCode;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
- (BOOL)hasLimit;
@property(nonatomic) unsigned long long limit;
@property(retain, nonatomic) LiCanceler *canceler;
@property(retain, nonatomic) NSArray *args;
@property(retain, nonatomic) NSString *where;
- (BOOL)waitForAsync_deleteModels;
- (void)deleteModels:(CDUnknownBlockType)arg1;
- (void)waitForAsync_updateColumn:(id)arg1 toValue:(id)arg2;
- (void)updateColumn:(id)arg1 toValue:(id)arg2 atEnd:(CDUnknownBlockType)arg3;
- (BOOL)waitForAsync_resolveModelExists;
- (void)resolveModelExists:(CDUnknownBlockType)arg1;
- (unsigned long long)waitForAsync_resolveCountOfModels;
- (void)resolveCountOfModels:(CDUnknownBlockType)arg1;
- (id)waitForAsync_resolveAnyModel;
- (void)resolveAnyModel:(CDUnknownBlockType)arg1;
- (id)waitForAsync_resolveOneValue:(id)arg1;
- (void)resolveOneValue:(id)arg1 atEnd:(CDUnknownBlockType)arg2;
- (id)waitForAsync_resolveDistinctList:(id)arg1;
- (void)resolveDistinctList:(id)arg1 atEnd:(CDUnknownBlockType)arg2;
- (id)waitForAsync_resolveDistinct:(id)arg1;
- (void)resolveDistinct:(id)arg1 atEnd:(CDUnknownBlockType)arg2;
- (void)resolveDistinct:(id)arg1 forEachData:(CDUnknownBlockType)arg2 atEnd:(CDUnknownBlockType)arg3;
- (id)waitForAsync_resolveModelsReturning:(id)arg1;
- (void)resolveModelsReturning:(id)arg1 atEnd:(CDUnknownBlockType)arg2;
- (id)waitForAsync_resolveModels;
- (void)resolveEachModel:(CDUnknownBlockType)arg1 returning:(id)arg2 atEnd:(CDUnknownBlockType)arg3;
- (void)resolveModels:(CDUnknownBlockType)arg1;
- (id)waitForAsync_resolveModelIdlistForProperties:(id)arg1;
- (void)resolveModelIdListForProperties:(id)arg1 atEnd:(CDUnknownBlockType)arg2;
- (id)waitForAsync_resolveModelIdList;
- (void)resolveModelIdList:(CDUnknownBlockType)arg1;
- (id)waitForAsync_resolveModelIds;
- (void)resolveModelIds:(CDUnknownBlockType)arg1;
- (void)performLoadQueryForProperties:(id)arg1 ridListHandler:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

