//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSSet, RDImageAdjustmentTable;

@interface RDAdjustmentConversionSession : NSObject
{
    RDImageAdjustmentTable *_adjustmentTable;
    NSArray *_adjustmentProperties;
    NSMutableDictionary *map_versionIdToProxyId;
    NSMutableDictionary *map_versionUuidToAdjustmentRidList;
    NSSet *_adjustedVersionUuids;
    NSObject<OS_dispatch_queue> *_serializer;
    unsigned long long _state;
    NSMutableDictionary *map_versionUuidToVersion;
    NSMutableArray *_adjustedVersions;
    NSMutableArray *_videoVersions;
    NSMutableDictionary *map_orientationToVersionRidList;
    NSMutableDictionary *map_orientationToProxyRidList;
}

+ (id)batchifyVersionArray:(id)arg1 batchSize:(unsigned long long)arg2;
+ (id)categorizeAdjustmentsByVersion:(id)arg1;
+ (void)sortVersionArrayByModelId:(id)arg1;
- (void).cxx_destruct;
- (id)adjustmentRidsInBatch:(id)arg1;
- (id)adjustmentsForRidList:(id)arg1;
- (BOOL)proccessVersionsWithBatchSize:(unsigned long long)arg1 onBatchCompleteBlock:(CDUnknownBlockType)arg2;
- (unsigned long long)workItemCount;
- (void)addVersion:(id)arg1 type:(unsigned char)arg2;
- (void)associateVersion:(id)arg1 withOrientation:(long long)arg2;
- (void)_enterState:(unsigned long long)arg1;
- (id)orientationToProxyRidLists;
- (id)orientationToVersionRidLists;
- (unsigned long long)adjustedVersionCount;
- (id)initWithLibrary:(id)arg1 proxies:(id)arg2 adjustments:(id)arg3;
- (id)init;

@end

