//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface RDAdjustmentConversionContext : NSObject
{
    BOOL _isRAW;
    NSString *_adjIndexKeyPath;
    long long _orientation;
    NSArray *_adjustments;
    struct PFIntSize_st _masterSize;
}

@property(retain) NSArray *adjustments; // @synthesize adjustments=_adjustments;
@property BOOL isRAW; // @synthesize isRAW=_isRAW;
@property long long orientation; // @synthesize orientation=_orientation;
@property struct PFIntSize_st masterSize; // @synthesize masterSize=_masterSize;
@property(retain) NSString *adjIndexKeyPath; // @synthesize adjIndexKeyPath=_adjIndexKeyPath;
- (void).cxx_destruct;
- (id)copyWithAdjustments:(id)arg1;
- (id)debugDescription;

@end

