//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PhotoLibraryPrivate/RDModel.h>

@class NSData, NSDate, NSNumber, NSString, RDAlbumTable;

@interface RDAlbumModel : RDModel
{
}

+ (Class)tableClass;
@property(nonatomic) long long cloudLibraryState;
@property(nonatomic) BOOL isPinned;
@property(retain, nonatomic) NSDate *streamLastContributionDate;
@property(retain, nonatomic) NSDate *streamLastInterestingChangeDate;
@property(retain, nonatomic) NSString *streamOwnerFullName;
@property(retain, nonatomic) NSString *streamOwnerEmail;
@property(retain, nonatomic) NSString *streamOwnerPersonId;
@property(retain, nonatomic) NSNumber *streamRelationshipState;
@property(retain, nonatomic) NSString *streamAlbumIdentifier;
@property(nonatomic) double printProjectAspectRatio;
@property(nonatomic) double printProjectThumbnailScale;
@property(nonatomic) long long printProjectType;
@property(retain, nonatomic) NSString *printProjectUuid;
@property(retain, nonatomic) NSData *slideshowData;
@property(retain, nonatomic) NSData *selectedVersionIds;
@property(retain, nonatomic) NSData *viewData;
@property(retain, nonatomic) NSData *queryData;
@property(retain, nonatomic) NSData *filterData;
@property(retain, nonatomic) NSDate *recentUserChangeDate;
@property(nonatomic) long long personId;
@property(retain, nonatomic) NSString *faceSortKeyPath;
@property(retain, nonatomic) NSNumber *colorLabelIndex;
@property(nonatomic) BOOL isMagic;
@property(nonatomic) BOOL isHidden;
@property(retain, nonatomic) NSDate *inTrashDate;
@property(nonatomic) BOOL isInTrash;
@property(nonatomic) BOOL isFavorite;
@property(retain, nonatomic) NSDate *createDate;
@property(nonatomic) long long versionCount;
@property(nonatomic) BOOL customSortAvailable;
@property(nonatomic) BOOL sortAscending;
@property(retain, nonatomic) NSString *sortKeyPath;
@property(retain, nonatomic) NSString *selectedTrackPathUuid;
@property(retain, nonatomic) NSString *posterVersionUuid;
@property(retain, nonatomic) NSString *queryFolderUuid;
@property(retain, nonatomic) NSString *folderUuid;
@property(retain, nonatomic) NSString *name;
@property(nonatomic) long long albumSubclass;
@property(nonatomic) long long albumType;
@property(readonly, nonatomic) RDAlbumTable *table;

@end

