//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PhotoLibraryPrivate/RDModel.h>

@class NSString, RDCustomSortEntryTable;

@interface RDCustomSortEntryModel : RDModel
{
}

+ (Class)tableClass;
@property(nonatomic) long long orderNumber;
@property(retain, nonatomic) NSString *objectUuid;
@property(retain, nonatomic) NSString *purpose;
@property(retain, nonatomic) NSString *containerUuid;
@property(readonly, nonatomic) RDCustomSortEntryTable *table;

@end

