//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RDSyncOperation.h"

@class NSString, RDImportContext;

@interface RDImportLibrary : NSObject <RDSyncOperation>
{
    id <RDSyncProgressDelegate> _importDelegate;
    RDImportContext *_importCtx;
    BOOL _inProgress;
    BOOL _stop;
    int _progressSpinLock;
}

- (void).cxx_destruct;
- (void)endTaskWithError:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)performStartTaskWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)stop;
- (void)startWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initWithSourceDatabase:(id)arg1 targetDatabase:(id)arg2 usingSettings:(id)arg3 andProgressDelegate:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

