//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PhotoLibraryPrivate/RDUndoRedoChange.h>

@class LiAddress, NSSet;

@interface RDKeywordForVersionUndoRedoChange : RDUndoRedoChange
{
    LiAddress *_versionAddress;
    NSSet *_keywordIds;
    NSSet *_keywordUuids;
    unsigned char _changeType;
}

@property(readonly, nonatomic) NSSet *keywordUuids; // @synthesize keywordUuids=_keywordUuids;
@property(readonly, nonatomic) NSSet *keywordIds; // @synthesize keywordIds=_keywordIds;
@property(readonly, nonatomic) unsigned char changeType; // @synthesize changeType=_changeType;
- (void).cxx_destruct;
- (id)description;
- (void)redo;
- (void)undo;
- (void)keywordsChanged;
- (id)version;
- (id)initWithVersion:(id)arg1 changeType:(unsigned char)arg2 keywords:(id)arg3;

@end

