//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSArray, NSDate, NSDictionary, NSMutableDictionary, NSString;

@interface RDMetadata : NSObject <NSCopying>
{
    NSDate *_imageDate;
    NSString *_filePath;
    NSMutableDictionary *_exifProperties;
    NSMutableDictionary *_iptcProperties;
    NSMutableDictionary *_basicProperties;
    NSMutableDictionary *_fileSystemProperties;
    NSMutableDictionary *_customInfo;
    NSMutableDictionary *_cgImageProperties;
    NSDictionary *_audioVideoProperties;
    NSArray *_focusPoints;
    NSString *_cameraTimeZoneName;
    NSString *_pictureTimeZoneName;
    long long _originalOrientation;
    long long _orientation;
    NSArray *_xmpImageAdjustments;
    NSString *_xmpOrientation;
    NSString *_fileTypeIdentifier;
    struct CGSize _originalUnrotatedSize;
}

@property(retain, nonatomic) NSString *fileTypeIdentifier; // @synthesize fileTypeIdentifier=_fileTypeIdentifier;
@property(retain, nonatomic) NSString *xmpOrientation; // @synthesize xmpOrientation=_xmpOrientation;
@property(retain, nonatomic) NSArray *xmpImageAdjustments; // @synthesize xmpImageAdjustments=_xmpImageAdjustments;
@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
@property(nonatomic) long long originalOrientation; // @synthesize originalOrientation=_originalOrientation;
@property(nonatomic) struct CGSize originalUnrotatedSize; // @synthesize originalUnrotatedSize=_originalUnrotatedSize;
@property(retain, nonatomic) NSString *pictureTimeZoneName; // @synthesize pictureTimeZoneName=_pictureTimeZoneName;
@property(retain, nonatomic) NSString *cameraTimeZoneName; // @synthesize cameraTimeZoneName=_cameraTimeZoneName;
@property(retain, nonatomic) NSArray *focusPoints; // @synthesize focusPoints=_focusPoints;
@property(retain, nonatomic) NSDictionary *audioVideoProperties; // @synthesize audioVideoProperties=_audioVideoProperties;
@property(retain, nonatomic) NSMutableDictionary *cgImageProperties; // @synthesize cgImageProperties=_cgImageProperties;
@property(retain, nonatomic) NSMutableDictionary *customInfo; // @synthesize customInfo=_customInfo;
@property(retain, nonatomic) NSMutableDictionary *fileSystemProperties; // @synthesize fileSystemProperties=_fileSystemProperties;
@property(retain, nonatomic) NSMutableDictionary *basicProperties; // @synthesize basicProperties=_basicProperties;
@property(retain, nonatomic) NSMutableDictionary *iptcProperties; // @synthesize iptcProperties=_iptcProperties;
@property(retain, nonatomic) NSMutableDictionary *exifProperties; // @synthesize exifProperties=_exifProperties;
@property(copy, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
- (void).cxx_destruct;
- (void)setEncodedAudioVideoData:(id)arg1;
- (void)setEncodedImageData:(id)arg1;
- (id)encodedData;
- (void)setWithLocation:(id)arg1;
- (id)location;
- (void)setAudioVideoAttributes:(id)arg1;
- (BOOL)parseISO6709String:(id)arg1 outLat:(float *)arg2 outLng:(float *)arg3;
- (void)enforceProperFormatting:(id)arg1;
- (id)_digestedExifAttributesFromRawAttributes:(id)arg1;
- (id)_digestedIptcAttributesFromRawAttributes:(id)arg1;
- (void)setCGImageProperties:(id)arg1;
- (id)description;
- (id)descriptionDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)replaceFocusPointNoteOn:(id)arg1;
- (id)attachFocusPointNoteTo:(id)arg1;
- (void)extractFocusPointsFrom:(id)arg1 orExifAux:(id)arg2;
- (id)iptcPropertyForKey:(id)arg1;
- (void)setIPTCProperty:(id)arg1 forKey:(id)arg2;
- (id)exifPropertyForKey:(id)arg1;
- (void)setExifProperty:(id)arg1 forKey:(id)arg2;
- (id)customPropertyForKey:(id)arg1;
- (void)setCustomProperty:(id)arg1 forKey:(id)arg2;
- (void)setRawFileSystemAttributes:(id)arg1;
- (void)setCustomProperties:(id)arg1;
- (void)mergeMetadata:(id)arg1;
- (void)clearImageAttributes;
@property(readonly, nonatomic) NSString *burstUuid;
@property(retain, nonatomic) NSDate *imageDate; // @synthesize imageDate=_imageDate;
- (id)init;

@end

