//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PhotoLibraryPrivate/RDModel.h>

@class NSData, NSDate, NSString, RDMomentTable;

@interface RDMomentModel : RDModel
{
}

+ (Class)tableClass;
@property(retain, nonatomic) NSData *userTitlesData;
@property(retain, nonatomic) NSData *secondaryPlaceData;
@property(retain, nonatomic) NSData *primaryPlaceData;
@property(nonatomic) BOOL needsRebuild;
@property(nonatomic) BOOL reverseLocationDataIsValid;
@property(retain, nonatomic) NSData *reverseLocationData;
@property(nonatomic) long long generationType;
@property(retain, nonatomic) NSString *collectionUuid;
@property(retain, nonatomic) NSString *yearUuid;
@property(nonatomic) long long versionCount;
@property(retain, nonatomic) NSDate *representativeDate;
@property(retain, nonatomic) NSDate *endDate;
@property(retain, nonatomic) NSDate *startDate;
@property(readonly, nonatomic) RDMomentTable *table;

@end

