//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PhotoLibraryPrivate/LiModel.h>

#import "RDModelAttachments.h"
#import "RDModelFingerprint.h"
#import "RDRepairable.h"

@class NSString, RDDatabase, RDTable;

@interface RDModel : LiModel <RDModelFingerprint, RDModelAttachments, RDRepairable>
{
    int _spinlock;
    BOOL _notifyOfChanges;
}

+ (id)libraryForModels:(id)arg1;
+ (id)addressesForModelIds:(id)arg1 fromLibrary:(id)arg2;
+ (id)uuidsForModelIds:(id)arg1 fromLibrary:(id)arg2;
+ (id)uuidsForModels:(id)arg1;
+ (id)modelIdListForModels:(id)arg1;
+ (id)modelIdsForModels:(id)arg1;
+ (id)addressesForModels:(id)arg1;
+ (id)anyModel:(id)arg1;
+ (id)modelUuidsForIds:(id)arg1 fromLibrary:(id)arg2;
+ (id)modelsForUuids:(id)arg1 fromLibrary:(id)arg2;
+ (id)modelForUuid:(id)arg1 fromLibrary:(id)arg2;
+ (void)deleteModels:(id)arg1;
+ (void)deleteModels:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
+ (void)deleteModelsForUuids:(id)arg1 fromLibrary:(id)arg2;
+ (void)deleteModelForUuid:(id)arg1 fromLibrary:(id)arg2;
+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
+ (id)tableForModelType:(short)arg1 forDatabase:(id)arg2;
+ (void)registerRepairBlocks:(id)arg1;
+ (id)uuidsForModelIds:(id)arg1 fromDatabase:(id)arg2;
+ (id)modelIdListForUuids:(id)arg1 fromDatabase:(id)arg2;
+ (id)modelIdsForUuids:(id)arg1 fromDatabase:(id)arg2;
+ (id)modelIdForUuid:(id)arg1 fromDatabase:(id)arg2;
+ (id)orderedModelsForUuids:(id)arg1 fromDatabase:(id)arg2;
+ (id)modelsForUuids:(id)arg1 fromDatabase:(id)arg2;
+ (id)modelForUuid:(id)arg1 fromDatabase:(id)arg2;
+ (id)modelsForIdList:(id)arg1 fromDatabase:(id)arg2;
+ (id)modelsForIds:(id)arg1 fromDatabase:(id)arg2;
+ (id)modelForId:(unsigned long long)arg1 fromDatabase:(id)arg2 loadOptions:(id)arg3;
+ (id)modelForId:(id)arg1 fromDatabase:(id)arg2;
+ (id)databasesForModels:(id)arg1;
+ (id)databaseForModels:(id)arg1;
+ (unsigned long long)waitForAsync_countOfModelsFromDatabase:(id)arg1 where:(id)arg2;
+ (id)waitForAsync_modelsFromDatabase:(id)arg1 where:(id)arg2 args:(id)arg3;
+ (id)waitForAsync_modelsFromDatabase:(id)arg1 where:(id)arg2;
@property(nonatomic) BOOL notifyOfChanges; // @synthesize notifyOfChanges=_notifyOfChanges;
@property(retain, nonatomic) NSString *migratedUuid;
- (id)readOnlyCopyLoadedWithOptions:(id)arg1;
- (BOOL)reloadWithOptions:(id)arg1;
- (BOOL)reloadWithOptionsMask:(unsigned char)arg1 additionalKeyPaths:(id)arg2;
- (BOOL)reloadWithOptionsMask:(unsigned char)arg1;
- (void)deleteModel;
- (BOOL)isEqual:(id)arg1;
- (id)modelIdAsNumber;
@property(retain, nonatomic) NSString *uuid;
@property(readonly, nonatomic) RDTable *table;
- (id)library;
@property(readonly) short modelType;
- (void)commonInit;
- (id)initWithAddress:(id)arg1 uuid:(id)arg2 inLibrary:(id)arg3;
- (id)initWithUuid:(id)arg1 forTable:(id)arg2;
- (id)initWithUuid:(id)arg1 forLibrary:(id)arg2;
@property(readonly, nonatomic) __weak RDDatabase *database;
- (id)initWithUuid:(id)arg1 inDatabase:(id)arg2;
- (id)initWithAddress:(id)arg1 uuid:(id)arg2 inDatabase:(id)arg3;
- (id)initWithModelId:(id)arg1 inDatabase:(id)arg2;
- (id)assetsPath;
- (void)setWasRecentlyUsed:(BOOL)arg1;
- (void)uncache;
- (BOOL)flushModel;
- (void)setIsDeleted;
- (BOOL)isDeleted;
- (id)fingerprintForData:(id)arg1;
- (void)fingerprintForPath:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)setGeneratedFingerprintWithData:(id)arg1;
- (void)setGeneratedFingerprintWithHandler:(CDUnknownBlockType)arg1;
- (id)attachmentsOfType:(id)arg1;
- (BOOL)hasAttachmentOfType:(id)arg1;
- (id)attachments;
- (BOOL)hasAttachments;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

