//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PhotoLibraryPrivate/RDTable.h>

@class LiKeyPath;

@interface RDNoteTable : RDTable
{
    LiKeyPath *_attachedToClassTypeKeyPath;
    LiKeyPath *_attachedToUuidKeyPath;
    LiKeyPath *_propertyKeyKeyPath;
    LiKeyPath *_noteKeyPath;
    LiKeyPath *_createDateKeyPath;
    LiKeyPath *_dataKeyPath;
}

+ (id)tableClassName;
+ (id)tableName;
+ (id)modelName;
+ (Class)modelClass;
@property(readonly, nonatomic) LiKeyPath *dataKeyPath; // @synthesize dataKeyPath=_dataKeyPath;
@property(readonly, nonatomic) LiKeyPath *createDateKeyPath; // @synthesize createDateKeyPath=_createDateKeyPath;
@property(readonly, nonatomic) LiKeyPath *noteKeyPath; // @synthesize noteKeyPath=_noteKeyPath;
@property(readonly, nonatomic) LiKeyPath *propertyKeyKeyPath; // @synthesize propertyKeyKeyPath=_propertyKeyKeyPath;
@property(readonly, nonatomic) LiKeyPath *attachedToUuidKeyPath; // @synthesize attachedToUuidKeyPath=_attachedToUuidKeyPath;
@property(readonly, nonatomic) LiKeyPath *attachedToClassTypeKeyPath; // @synthesize attachedToClassTypeKeyPath=_attachedToClassTypeKeyPath;
- (void).cxx_destruct;
- (id)defaultLoadPropertyPaths;
- (void)declareProperties;
- (id)initWithTableId:(unsigned long long)arg1 tableType:(unsigned char)arg2 withLibrary:(id)arg3;
- (id)notifyUpdateKeyPaths;
- (unsigned long long *)faultedKeyPath;
- (unsigned long long *)faultedModelKeyPath;

@end

