//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PhotoLibraryPrivate/RKAlbumRef.h>

@class RDMoment;

@interface RKMomentRef : RKAlbumRef
{
    RDMoment *_moment;
}

@property(readonly, nonatomic) RDMoment *moment; // @synthesize moment=_moment;
- (void).cxx_destruct;
- (id)initWithAlbum:(id)arg1;
- (id)initWithMoment:(id)arg1;
- (id)sortVersions:(id)arg1 byKeyPath:(id)arg2 ascending:(BOOL)arg3;

@end

