//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AVBTimeSyncClockManager : NSObject
{
    unsigned int connection;
}

+ (id)sharedNub;
+ (void)loadClockManagerNub;
- (void)dealloc;
- (void)finalize;
- (id)description;
- (BOOL)removeMappingFromClockIDToCoreAudioClockDomainForClockID:(unsigned long long)arg1 error:(id *)arg2;
- (BOOL)addMappingFromClockID:(unsigned long long)arg1 toCoreAudioClockDomain:(unsigned int *)arg2 error:(id *)arg3;
- (BOOL)releaseDynamicClockID:(unsigned long long)arg1 error:(id *)arg2;
- (BOOL)nextAvailableDynamicClockID:(unsigned long long *)arg1 error:(id *)arg2;
- (BOOL)getMachAbsoluteClockID:(unsigned long long *)arg1 error:(id *)arg2;
- (id)init;

@end

