//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AddressBookCompletion : NSObject
{
}

+ (id)completionsForString:(id)arg1 testEmail:(BOOL)arg2;
+ (id)instance;
- (id)completionsForString:(id)arg1 testEmail:(BOOL)arg2;
- (id)init;

@end

