//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ALHolder : NSObject
{
    struct IPAlbumList *mAlbumList;
}

+ (id)holdNoCopy:(struct IPAlbumList *)arg1;
+ (id)hold:(struct IPAlbumList *)arg1;
- (struct IPAlbumList *)albumList;
- (void)dealloc;
- (id)initWithAlbumListNoCopy:(struct IPAlbumList *)arg1;
- (id)initWithAlbumList:(struct IPAlbumList *)arg1;

@end

