//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AppVersion : NSObject
{
    long long _components[4];
}

- (long long)compare:(id)arg1;
- (id)description;
@property(readonly) NSString *stringVersion;
@property(readonly) long long dotDotVersion;
@property(readonly) long long dotVersion;
@property(readonly) long long minorVersion;
@property(readonly) long long majorVersion;
- (id)initWithString:(id)arg1;
- (id)initWithFloat:(float)arg1;
- (id)init;

@end

