//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@interface CAPGradientLayer : CALayer
{
    int mDirection;
    struct CGImage *mImage;
}

+ (void)drawLinearGradientInRect:(struct CGRect)arg1 startAlpha:(double)arg2 endAlpha:(double)arg3 forContext:(struct CGContext *)arg4;
- (void)drawInContext:(struct CGContext *)arg1;
- (void)setDirection:(int)arg1;

@end

