//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IP_DirectionView.h"

@interface HUDDirectionView : IP_DirectionView
{
}

- (id)imageForIndex:(int)arg1;
- (id)_bevelImage;
- (void)setCompositePoints;
- (void)initializeArt;

@end

