//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BackgroundColorView.h"

#import "MultiPanePaneProtocol.h"

@class ImageDB;

@interface ImportView : BackgroundColorView <MultiPanePaneProtocol>
{
    ImageDB *mDB;
}

- (struct IPSelectionList *)retrieveSelection;
- (void)drawRect:(struct CGRect)arg1;
- (BOOL)performDragOperation:(id)arg1;
- (unsigned long long)draggingEntered:(id)arg1;
- (void)setDropDB:(id)arg1;
- (void)awakeFromNib;

@end

