//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSMutableSet;

@interface ImportTracker : NSObject
{
    NSMutableDictionary *addedPhotos;
    NSMutableSet *putInTrash;
    NSMutableSet *removeFromTrash;
}

- (void)notify:(id)arg1;
- (void)collectPhoto:(struct IPPhotoInfo *)arg1 folder:(id)arg2;
- (void)dealloc;
- (id)init;

@end

