//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IPKTableView.h"

@class IPCompletionMenu;

@interface IPCompletionMenuTableView : IPKTableView
{
    IPCompletionMenu *_menu;
}

- (void)keyDown:(id)arg1;
- (void)setCompletionMenu:(id)arg1;
- (BOOL)acceptsFirstMouse:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

