//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IPHProgressIndicator.h"

@interface IPHProcessIndicator : IPHProgressIndicator
{
}

- (void)draw;
- (id)alternateIndeterminateIconsForAnimationFilenames;
- (id)alternateIconsForAnimationFilenames;
- (id)indeterminateIconsForAnimationFilenames;
- (id)iconsForAnimationFilenames;

@end

