//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IWSharingActivityTileViewPublish.h"

@interface IWSharingActivityTileViewEmail : IWSharingActivityTileViewPublish
{
}

- (void)performClickAction;
- (void)configureTextFieldCell:(id)arg1;
- (BOOL)isClickable;
- (BOOL)validateSharingActivityInfo;
- (id)emailPublishInfo;
- (id)tileText;
- (id)tileIcon;

@end

