//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

@interface KeywordInspectorButton : NSButton
{
    int mCount;
    BOOL mHighlight;
}

- (unsigned long long)draggingSourceOperationMaskForLocal:(BOOL)arg1;
- (void)mouseDown:(id)arg1;
- (void)highlight:(BOOL)arg1;
- (int)count;
- (void)setCount:(int)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)titleAttrs;
- (id)font;
- (BOOL)isFlipped;

@end

