//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MGScreenRegistry : NSObject
{
    struct __CFDictionary *_screenOwners;
}

+ (id)sharedScreenRegistry;
- (void)applicationDidChangeScreenParameters:(id)arg1;
- (void)removeOwnerForScreen:(id)arg1;
- (void)setOwner:(id)arg1 forScreen:(id)arg2;
- (id)bestAvailableScreenForPreferredScreen:(id)arg1;
- (void)dealloc;
- (id)init;

@end

