//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MPDocument.h"

@interface MPDocument (IPMarimbaDocumentAdditions)
- (id)previousEffectContainerFromContainer:(id)arg1;
- (id)firstEffectID;
- (id)visibleSlidesInView:(id)arg1;
- (id)firstEffectContainer;
- (id)currentEffectContainerInView:(id)arg1;
- (id)effectContainerWithPhotosForTime:(double)arg1;
- (id)effectContainerForTime:(double)arg1;
@end

