//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IPKToolbarView.h"

#import "MultiPanePaneProtocol.h"

@interface MultiPaneToolbarView : IPKToolbarView <MultiPanePaneProtocol>
{
    double _overlapMultiPaneContent;
    BOOL _backgroundMovesWindow;
}

@property BOOL backgroundMovesWindow; // @synthesize backgroundMovesWindow=_backgroundMovesWindow;
@property double overlapMultiPaneContent; // @synthesize overlapMultiPaneContent=_overlapMultiPaneContent;
- (id)accessibilityAttributeValue:(id)arg1;
- (BOOL)accessibilityIsAttributeSettable:(id)arg1;
- (id)accessibilityAttributeNames;
- (BOOL)accessibilityIsIgnored;
- (BOOL)toolbarHidden;
- (BOOL)mouseDownCanMoveWindow;
- (id)initWithFrame:(struct CGRect)arg1;

@end

