//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MWOneUpTransition;

@protocol MWOneUpTransitionAware <NSObject>

@optional
- (void)didOneUpTransition:(MWOneUpTransition *)arg1;
- (void)willOneUpTransition:(MWOneUpTransition *)arg1;
- (void)willParticipateInTransition:(MWOneUpTransition *)arg1;
@end

