//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (NSDataAdditions)
+ (id)dataWithBase64EncodedString:(id)arg1;
- (BOOL)hasPrefixBytes:(void *)arg1 length:(unsigned int)arg2;
- (BOOL)hasPrefix:(id)arg1;
- (id)base64EncodingWithLineLength:(unsigned int)arg1;
- (id)base64Encoding;
- (id)initWithBase64EncodedString:(id)arg1;
@end

