//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSEvent.h"

@interface NSEvent (iPhotoExtensions)
- (struct CGPoint)coalescedDeltaFromEventQueueIgnoringAcceleration:(BOOL)arg1;
- (id)mouseDownForContextPopupAtLocation:(struct CGPoint)arg1 inView:(id)arg2;
@end

