//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (NumberConversions)
+ (id)stringWithDouble:(double)arg1;
+ (id)stringWithUnsignedLong:(unsigned long long)arg1;
+ (id)stringWithLong:(long long)arg1;
- (double)doubleValue;
- (short)shortValue;
- (unsigned short)unsignedShortValue;
- (long long)longValue;
- (unsigned long long)unsignedLongValue;
- (unsigned long long)unsignedLongLongValue;
- (BOOL)stringToUnsignedLongInt:(unsigned long long *)arg1;
- (BOOL)stringToUnsignedLongLongInt:(unsigned long long *)arg1;
@end

