//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "KHPhotoFaceInfoProtocol.h"

@class IPPhotoObjCProxy, NSDictionary, NSString, NewFaceDetector, RKDetectedFace;

@interface PAPhotoFaceInfo : NSObject <KHPhotoFaceInfoProtocol>
{
    NewFaceDetector *_faceDetector;
    RKDetectedFace *_detectedFace;
    IPPhotoObjCProxy *_photoInfo;
    struct CGRect _unitRect;
    unsigned long long _faceKey;
}

- (id).cxx_construct;
@property(readonly) NSString *name;
- (struct CGRect)boundingRectForImageWidth:(unsigned long long)arg1 imageHeight:(unsigned long long)arg2;
@property(readonly) struct CGPoint unitBottomLeft;
@property(readonly) struct CGPoint unitBottomRight;
@property(readonly) struct CGPoint unitTopRight;
@property(readonly) struct CGPoint unitTopLeft;
@property(readonly) NSDictionary *attributes;
@property(readonly) NSString *personUid;
- (id)initWithFaceDetector:(id)arg1 photoInfo:(id)arg2 detectedFace:(id)arg3;
- (void)dealloc;

@end

