//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ReadAheadJob : NSObject
{
    NSString *_path;
    void *_data;
    BOOL _asHandle;
    char **_hData;
    int _dataLength;
    long long _key;
    BOOL _requested;
}

- (id)path;
- (id)initWithPath:(id)arg1 andKey:(long long)arg2;

@end

