//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindow.h"

@interface SimpleWindow : NSWindow
{
    BOOL _allowKey;
    BOOL _allowMain;
}

@property(nonatomic) BOOL allowMain; // @synthesize allowMain=_allowMain;
@property(nonatomic) BOOL allowKey; // @synthesize allowKey=_allowKey;
- (BOOL)usesProMenuTreatmentForView:(id)arg1;
- (BOOL)canBecomeMainWindow;
- (BOOL)canBecomeKeyWindow;

@end

