//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class XTIndexProvider;

@interface ThumbCacheEntry : NSObject
{
    void *_data;
    long long _size;
    XTIndexProvider *_indexProvider;
}

- (id)indexProvider;
- (long long)size;
- (void *)data;
- (void)dealloc;
- (id)initWithData:(void *)arg1 size:(long long)arg2 indexProvider:(id)arg3;

@end

