//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface AUParameterStripSizingManager : NSObject
{
    double preferredParamNameColumnWidth;
    double maximumParamNameColumnWidth;
    double preferredMinValueColumnWidth;
    double maximumMinValueColumnWidth;
    double preferredMaxValueColumnWidth;
    double maximumMaxValueColumnWidth;
    double preferredValueFieldWidth;
    double maximumValueFieldWidth;
    double preferredUnitsColumnWidth;
    double maximumUnitsColumnWidth;
    double preferredValueControlColumnWidth;
    double locationForParamLabel;
    double locationForMinValueLabel;
    double locationForMaxValueLabel;
    double locationForValueControl;
    double locationForValueField;
    double locationForUnitsLabel;
}

@property(readonly) double locationForUnitsLabel; // @synthesize locationForUnitsLabel;
@property(readonly) double locationForValueField; // @synthesize locationForValueField;
@property(readonly) double locationForValueControl; // @synthesize locationForValueControl;
@property(readonly) double locationForMaxValueLabel; // @synthesize locationForMaxValueLabel;
@property(readonly) double locationForMinValueLabel; // @synthesize locationForMinValueLabel;
@property(readonly) double locationForParamLabel; // @synthesize locationForParamLabel;
@property double maximumUnitsColumnWidth; // @synthesize maximumUnitsColumnWidth;
@property double preferredUnitsColumnWidth; // @synthesize preferredUnitsColumnWidth;
@property double maximumMaxValueColumnWidth; // @synthesize maximumMaxValueColumnWidth;
@property double preferredValueFieldWidth; // @synthesize preferredValueFieldWidth;
@property double preferredMaxValueColumnWidth; // @synthesize preferredMaxValueColumnWidth;
@property double preferredValueControlColumnWidth; // @synthesize preferredValueControlColumnWidth;
@property double maximumMinValueColumnWidth; // @synthesize maximumMinValueColumnWidth;
@property double preferredMinValueColumnWidth; // @synthesize preferredMinValueColumnWidth;
@property double maximumParamNameColumnWidth; // @synthesize maximumParamNameColumnWidth;
@property double preferredParamNameColumnWidth; // @synthesize preferredParamNameColumnWidth;
- (void)recalculateColumnsForWidth:(double)arg1;
- (id)init;

@end

