//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@interface SPLineView : NSView
{
}

- (void)drawRect:(struct CGRect)arg1;
- (BOOL)allowsVibrancy;
- (void)awakeFromNib;

@end

