//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class QLPreviewView, SPResult;

@interface SPPreviewController : NSViewController
{
    SPResult *_internalPreviewResult;
    CDUnknownBlockType _internalPreviewDoubleClickHandler;
    QLPreviewView *_qlView;
}

@property __weak QLPreviewView *qlView; // @synthesize qlView=_qlView;
@property(copy) CDUnknownBlockType internalPreviewDoubleClickHandler; // @synthesize internalPreviewDoubleClickHandler=_internalPreviewDoubleClickHandler;
@property(retain) SPResult *internalPreviewResult; // @synthesize internalPreviewResult=_internalPreviewResult;
- (void).cxx_destruct;
- (void)awakeFromNib;
- (void)mouseUp:(id)arg1;
- (void)configureForQLView:(id)arg1;
- (void)containerSizeChanged:(id)arg1 userInfo:(id)arg2;
@property(copy) CDUnknownBlockType previewDoubleClickHandler;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)show;
- (void)hide;

@end

