//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSLayoutConstraint, NSTextField, SPImageView;

@interface SPTrailersSliceView : NSView
{
    NSTextField *_titleTextField;
    SPImageView *_trailerImageView1;
    SPImageView *_trailerImageView2;
    SPImageView *_trailerImageView3;
    NSLayoutConstraint *_trailerImageViewHeightConstraint;
    NSTextField *_trailerTextField1;
    NSTextField *_trailerTextField2;
    NSTextField *_trailerTextField3;
}

@property NSTextField *trailerTextField3; // @synthesize trailerTextField3=_trailerTextField3;
@property NSTextField *trailerTextField2; // @synthesize trailerTextField2=_trailerTextField2;
@property NSTextField *trailerTextField1; // @synthesize trailerTextField1=_trailerTextField1;
@property NSLayoutConstraint *trailerImageViewHeightConstraint; // @synthesize trailerImageViewHeightConstraint=_trailerImageViewHeightConstraint;
@property SPImageView *trailerImageView3; // @synthesize trailerImageView3=_trailerImageView3;
@property SPImageView *trailerImageView2; // @synthesize trailerImageView2=_trailerImageView2;
@property SPImageView *trailerImageView1; // @synthesize trailerImageView1=_trailerImageView1;
@property NSTextField *titleTextField; // @synthesize titleTextField=_titleTextField;
- (void)mouseUp:(id)arg1;
- (void)_sendAction:(SEL)arg1 to:(id)arg2 from:(id)arg3;
- (id)trailerTextFieldAtIndex:(unsigned long long)arg1;
- (id)trailerImageViewAtIndex:(unsigned long long)arg1;
@property(readonly) unsigned long long maximumNumberOfTrailers;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

