//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QCView.h"

@interface QCView (IMAVManagerAdditions)
- (void)_IMGetOpenGLBufferContext:(struct _CGLContextObject **)arg1 pixelFormat:(struct _CGLPixelFormatObject **)arg2;
- (unsigned long long)_IMDataSourceVideoUpdateMechanism;
- (BOOL)_IMUsePixelBufferCallBacks;
@end

