//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APLSubConstraint.h"

@class APLElement;

@interface APLAlignment : APLSubConstraint
{
    APLElement *alignElement;
    APLElement *referenceElement;
}

- (void).cxx_destruct;
- (double)referencePosition;
- (double)alignPosition;
- (id)referenceElement;
- (id)alignElement;
- (id)referenceName;
- (id)alignName;
- (BOOL)resolveFromElement:(id)arg1;
- (id)initWithProperties:(id)arg1;

@end

