//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APLConstraint.h"

@interface APLDistributeConstraint : APLConstraint
{
}

- (struct CGRect)applyOnElementsRespectingMinimumSizes:(id)arg1;
- (struct CGRect)applyOnElementsRespectingWeights:(id)arg1;
- (struct CGRect)applyOnElements:(id)arg1 withQuality:(long long)arg2;
- (id)applyOnElements:(id)arg1 inFrame:(id)arg2;

@end

