//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSImage.h"

@interface CALColorSwatch : NSImage
{
}

+ (void)drawSwatch:(id)arg1 inRect:(struct CGRect)arg2 withBorderColor:(id)arg3 withBorderWidth:(long long)arg4;
+ (id)colorSwatch:(id)arg1 size:(struct CGSize)arg2 withBorderColor:(id)arg3 withBorderWidth:(long long)arg4;
+ (id)bigColorSwatch:(id)arg1 withBorderColor:(id)arg2 withBorderWidth:(long long)arg3;
+ (id)colorSwatch:(id)arg1 withBorderColor:(id)arg2 withBorderWidth:(long long)arg3;
+ (id)colorSwatch:(id)arg1;

@end

