//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSWindow;

@protocol CalPreferencesCustomFieldEditor <NSObject>

@optional
- (id)windowWillReturnFieldEditor:(NSWindow *)arg1 toObject:(id)arg2 withIdentifier:(NSString *)arg3;
@end

