//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CalPopoverController.h"

#import "CalUISuggestionsFieldDelegate.h"
#import "NSPopoverDelegate.h"

@class CalUISuggestionsField, EKCalendar, NSString, NSView;

@interface CalQuickEventPopoverController : CalPopoverController <NSPopoverDelegate, CalUISuggestionsFieldDelegate>
{
    EKCalendar *_calendarForEventCreation;
    NSView *_wrapperView;
    CalUISuggestionsField *_quickEntryField;
}

@property(retain) CalUISuggestionsField *quickEntryField; // @synthesize quickEntryField=_quickEntryField;
@property(retain) NSView *wrapperView; // @synthesize wrapperView=_wrapperView;
@property(retain) EKCalendar *calendarForEventCreation; // @synthesize calendarForEventCreation=_calendarForEventCreation;
- (void).cxx_destruct;
- (BOOL)popoverShouldClose:(id)arg1;
- (void)showPopoverWithCalendar:(id)arg1;
- (void)showPopover;
- (id)view;
- (void)suggestionSelected:(id)arg1;
- (id)viewForSuggestion:(id)arg1;
- (void)queryStringUpdatedToString:(id)arg1 suggestionsFoundHandler:(CDUnknownBlockType)arg2;
- (id)initWithPopoverButton:(id)arg1 mainController:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

