//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CalUILayerBackedView.h"

#import "NSAnimationDelegate.h"

@class CalUICalendarContentView, CalUICalendarViewsController, NSString, NSView;

@interface CalUICalendarContainerView : CalUILayerBackedView <NSAnimationDelegate>
{
    CalUICalendarContentView *_contentView;
    CalUICalendarViewsController *_viewsController;
    NSView *_leftEdgeBorder;
    NSView *_rightEdgeBorder;
}

@property(retain) NSView *rightEdgeBorder; // @synthesize rightEdgeBorder=_rightEdgeBorder;
@property(retain) NSView *leftEdgeBorder; // @synthesize leftEdgeBorder=_leftEdgeBorder;
@property __weak CalUICalendarViewsController *viewsController; // @synthesize viewsController=_viewsController;
@property(retain, nonatomic) CalUICalendarContentView *contentView; // @synthesize contentView=_contentView;
- (void).cxx_destruct;
- (void)addContentView:(id)arg1;
- (id)_newEdgeBorderView;
- (BOOL)isOpaque;
- (id)init;
- (BOOL)accessibilityIsAttributeSettable:(id)arg1;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityAttributeNames;
- (BOOL)accessibilityIsIgnored;
- (id)localizedDescriptionForViewType:(id)arg1;
- (id)bestFormattedDateStringForDate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

