//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CalUITimeZonePicker.h"

@class CalUIToolbar;

@interface CalUIResizingTimeZonePicker : CalUITimeZonePicker
{
    CalUIToolbar *_toolbar;
}

@property(retain) CalUIToolbar *toolbar; // @synthesize toolbar=_toolbar;
- (void).cxx_destruct;
- (void)viewWillDraw;

@end

