//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CoreEvent.h"

@interface CoreEvent (Scripting)
- (void)setLocationForScripting:(id)arg1;
- (id)locationForScripting;
- (id)rescheduleCommand:(id)arg1;
- (void)setFullDayEventForScripting:(BOOL)arg1;
- (BOOL)fullDayEventForScripting;
- (void)setEndNSCalendarDateForScripting:(id)arg1;
- (id)endNSCalendarDateForScripting;
- (void)setStartNSCalendarDateForScripting:(id)arg1;
@end

