//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CoreAlarm.h"

@interface CoreAlarm (Scripting)
- (void)setTriggerDuration:(id)arg1;
- (id)triggerDuration;
- (void)setTriggerDate:(id)arg1;
- (id)triggerDate;
@end

