//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "EKCalendar.h"

#import "CalUICalendarListViewNode.h"

@class NSString, NSURL;

@interface EKCalendar (CalendarListViewExtensions) <CalUICalendarListViewNode>
@property(readonly, nonatomic) BOOL isReorderable;
- (id)dataSourceContextForEditing;
- (void)removeChildNodes:(id)arg1;
- (void)removeChildNode:(id)arg1;
- (void)addChildNodes:(id)arg1;
- (void)addChildNode:(id)arg1;
- (id)childNodeAtIndex:(unsigned long long)arg1;
- (unsigned long long)numberOfChildNodes;
- (id)childNodes;
- (id)parentNode;
- (id)uid;
- (int)order;
- (BOOL)isCalendarDelegate;
- (BOOL)isRemoteCalendarOrGroup;
- (BOOL)isAffectingAvailability;
- (id)accountID;
- (BOOL)isSharedByMe;
- (BOOL)isSharedToMe;
- (BOOL)supportsSharing;
- (BOOL)isShared;
- (BOOL)supportsCalDAVPublish;
- (BOOL)isCalDAVPublished;
- (BOOL)supportsPublishing;
- (BOOL)isExpandable;
- (BOOL)isBusy;
- (BOOL)isRefreshable;
- (BOOL)isWritableCalendar;
- (BOOL)isCalDAV;
- (BOOL)isExchange;
- (BOOL)isBirthdayCalendar;
- (BOOL)isLocalCalendarGroup;
- (BOOL)isLocalCalendar;
- (BOOL)isCalendarType;
- (id)groupTitle;
- (BOOL)isCalendarGroup;
- (BOOL)isEnabledForCalendar;
- (id)displayTitle;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) BOOL isDeletable;
@property(readonly, nonatomic) BOOL isFacebookBirthdayCalendar;
@property(readonly, nonatomic) BOOL isRenameable;
@property(readonly, nonatomic) NSURL *publishURL;
@property(readonly) Class superclass;
@property(retain, nonatomic) NSString *title;
@end

