//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EKEvent, NSDictionary, NSSet;

@protocol EKDecisionDelegate <NSObject>
- (int)commitDecisionForCalendars:(NSSet *)arg1 forEditingAction:(int)arg2;
- (int)commitDecisionForEvents:(NSSet *)arg1 forEditingAction:(int)arg2 userImpliedDecision:(BOOL)arg3 diffSummary:(NSDictionary *)arg4;
- (unsigned long long)conflictDecisionForEvent:(EKEvent *)arg1 withConflictCount:(unsigned long long)arg2 outOfTotalCount:(unsigned long long)arg3;
- (int)spanDecisionForEvents:(NSDictionary *)arg1 forEditingAction:(int)arg2 diffSummary:(NSDictionary *)arg3;
- (BOOL)shouldSaveForEvents:(NSSet *)arg1 forEditingAction:(int)arg2 diffSummary:(NSDictionary *)arg3;
@end

