//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSColor.h"

@interface NSColor (CalUIAdditions)
+ (id)colorWithsRGBRed:(unsigned long long)arg1 green:(unsigned long long)arg2 blue:(unsigned long long)arg3;
- (BOOL)isGreenOrYellow;
- (id)overlayWithColor:(id)arg1;
- (id)burnWithColor:(id)arg1;
- (id)soverWithColor:(id)arg1;
- (double)differenceFromColor:(id)arg1;
- (double)luminance;
- (id)adjustedOccurrenceColor;
- (BOOL)isLightColor;
@end

