//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindow.h"

@interface NSWindow (CalUIPulseWindowAdditions)
- (void)pulseWithMagnificationFactor:(double)arg1 slowly:(BOOL)arg2;
- (void)pulseSlowly:(BOOL)arg1;
- (void)pulse;
- (void)setScaleX:(double)arg1 Y:(double)arg2;
- (struct CGPoint)convertPointToScreen:(struct CGPoint)arg1 isFlipped:(BOOL)arg2;
@end

