//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSUIMessageHandler.h"

@class NSArray, NSMutableSet;

@interface CSUIQuarantineMessageHandler : CSUIMessageHandler
{
    struct __LSASN *firstLaunchASN;
    NSArray *_fileDicts;
    NSMutableSet *_quarantineResolvers;
    CDUnknownBlockType _completionHandler;
    int _errorCode;
}

+ (void)askForUserConsentForFirstLaunchOfProcess:(struct __LSASN *)arg1;
- (void).cxx_destruct;
- (void)resolverDidChangeState:(id)arg1;
- (void)handleMessageWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)initWithMessageType:(int)arg1 connection:(id)arg2 object:(id)arg3;
- (BOOL)shouldBlockCallingProcessUntilComplete;
- (void)replyWithStatus:(int)arg1;
- (void)complete;

@end

