//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSAlertDelegate.h"

@class NSMutableArray, NSString, NSURL;

@interface GKQuarantineResolver : NSObject <NSAlertDelegate>
{
    int _state;
    id _delegate;
    NSURL *_appURL;
    NSURL *_dmgURL;
    NSURL *_serverURL;
    short _volume;
    NSURL *_backlinkURL;
    NSString *_agentIdentifier;
    struct __LSASN *_appASN;
    struct AuthorizationOpaqueRef *_authorization;
    BOOL _allowUnsigned;
    unsigned int _itemsType;
    NSMutableArray *_items;
    NSMutableArray *_itemsWhichAreOK;
    NSMutableArray *_itemsWhichAreMalware;
    NSMutableArray *_itemsToActuallyOpen;
    unsigned long long offsetOfItemBeingChecked;
    NSMutableArray *_malwareResultDicts;
    NSString *_riskCategory;
    CDStruct_4c969caf _clientAuditToken;
    int _sandboxStatus;
    NSMutableArray *_xProtectAnalysisObjects;
}

+ (id)formatStringForDetail:(id)arg1 date:(id)arg2 type:(id)arg3;
+ (id)formatStringForHeadline:(id)arg1 origin:(id)arg2 type:(id)arg3 isAlias:(BOOL)arg4;
- (void).cxx_destruct;
- (void)showGKAlertForPath:(id)arg1;
- (void)resolve;
- (void)handleMoveToTrashError:(id)arg1 forPath:(id)arg2 isEject:(BOOL)arg3;
- (void)malwareChecksFinished;
- (void)saveRejectionRecordForMalwareResult:(id)arg1;
- (void)malwareCheckNextItem;
- (void)malwareCheckEnded:(id)arg1 result:(id)arg2 forURL:(id)arg3;
- (void)malwareChecksBegin;
- (BOOL)alertShowHelp:(id)arg1;
- (id)alertForPath:(id)arg1 malwareInfo:(id)arg2;
- (void)layoutAlertPreservingTextFieldAttributes:(id)arg1;
- (id)informativeTextFieldForAlert:(id)arg1;
- (void)denyAndShow;
- (void)deny;
- (void)approveUpdatingQuarantineTarget:(BOOL)arg1 recursively:(BOOL)arg2 volume:(BOOL)arg3;
- (void)beginResolution;
- (int)state;
- (void)setState:(int)arg1;
- (void)dealloc;
- (id)initWithProperties:(id)arg1 delegate:(id)arg2 clientAuditToken:(const CDStruct_4c969caf *)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

