//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@interface DelayedLoginItems : NSOperation
{
}

+ (id)sharedDelayedLoginItems;
- (void)main;
- (void)dealloc;
- (void)performDelayedLoginItems;
- (void)messageTraceForLaunguageUse;
- (void)updateFMMComputerName;
- (void)notifyDelayedItemsStart;
- (void)warmUpUsefulItems;
- (void)launchStartupItemsFixerIfNeeded;
- (void)startStartupItemsFixer;

@end

