//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CALayer, NSObject<OS_dispatch_queue>, NSObject<OS_xpc_object>;

@interface DPRemoteDesktopPicture : NSObject
{
    NSObject<OS_xpc_object> *_connection;
    NSObject<OS_dispatch_queue> *_queue;
    unsigned int _did;
    CALayer *_desktopPictureLayer;
}

+ (void)queue:(id)arg1 remoteDesktopPictureForDisplay:(unsigned int)arg2 block:(CDUnknownBlockType)arg3;
@property(readonly) CALayer *desktopPictureLayer; // @synthesize desktopPictureLayer=_desktopPictureLayer;
- (void).cxx_destruct;
- (void)invalidate;
- (void)dealloc;
- (id)_initWithDisplay:(unsigned int)arg1 queue:(id)arg2 andBlock:(CDUnknownBlockType)arg3;

@end

