//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LUIProgressBar, NSMutableArray, NSWindow;

@interface LoginProgress : NSObject
{
    NSWindow *_progressIndicatorWindow;
    LUIProgressBar *_progressBar;
    struct __CFArray *_bootWindowList;
    NSMutableArray *_firstLoginShieldWindows;
    float _startingPercentage;
    float _loginUsableRange;
}

+ (id)sharedLoginProgress;
- (void)startLoginProgressBar;
- (struct CGRect)startingProgressRectForMainScreen;
- (float)startingPercentage;
- (void)progressAnimationComplete;
- (void)closeAndReleaseAllWindowsWithAnimation:(BOOL)arg1;
- (void)hideWindow:(id)arg1;
- (void)setBootListWindowLevels:(struct __CFArray *)arg1;
- (id)imageForCGWindow:(unsigned int)arg1;
- (struct CGRect)frameForCGWindowID:(unsigned int)arg1;
- (void)tearDownProgressImmediately;
- (void)incrementLoginProgressBarPercentage:(float)arg1;
- (void)setLoginProgressBarPercentage:(float)arg1;
- (BOOL)completeProgressBar;
- (BOOL)loginProgessBarShowing;
- (void)startLoginProgress;
- (void)dealloc;
- (id)init;

@end

