//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVAssetWriterInputPassDescription;

@interface AVAssetWriterInputPassDescriptionResponder : NSObject
{
    struct dispatch_queue_s *_callbackQueue;
    int _stoppedResponding;
    struct dispatch_queue_s *_serializationQueue;
    BOOL _hasRespondedAtLeastOnce;
    AVAssetWriterInputPassDescription *_mostRecentPassDescription;
    CDUnknownBlockType _callbackBlock;
}

- (BOOL)_hasStoppedResponding;
- (void)stopRespondingToPassDescriptions;
- (void)_releaseAndClearCallbackBlock_invokeOnSerializationQueue;
- (void)respondToNewPassDescription:(id)arg1;
- (void)finalize;
- (void)dealloc;
- (id)initWithCallbackQueue:(struct dispatch_queue_s *)arg1 block:(CDUnknownBlockType)arg2;
- (id)init;

@end

