//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Backup/BU_FlatControl.h>

__attribute__((visibility("hidden")))
@interface BU_ArrowedFlatControl : BU_FlatControl
{
    _Bool fIsPointingUp;
}

- (void)drawForeground:(struct CGContext *)arg1 bounds:(struct CGRect)arg2;
- (void)setIsPointingUp:(_Bool)arg1;
- (_Bool)isPointingUp;

@end

