//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CKContainerID, CKDMescalSession, CKDServerConfiguration, NSArray, NSDictionary, NSString, NSURL;

@protocol CKDAccountInfoProvider <NSObject>
- (NSString *)trafficContainerIdentifier;
- (BOOL)shouldFailAllTasks;
- (void)renewAuthTokenWithCompletionHandler:(void (^)(BOOL, NSError *))arg1;
- (NSString *)cloudKitAuthToken;
- (NSString *)iCloudAuthToken;
- (BOOL)accountWantsPushRegistration;
- (BOOL)isUnitTestingAccount;
- (BOOL)isAnonymousAccount;
- (NSArray *)enabledKeyboards;
- (NSString *)regionCode;
- (NSString *)languageCode;
- (NSString *)serverPreferredPushEnvironment;
- (NSString *)deviceName;
- (NSString *)hardwareID;
- (NSString *)sourceApplicationSecondaryIdentifier;
- (NSString *)bundleID;
- (CKContainerID *)containerID;
- (NSString *)containerScopedUserID;
- (NSString *)dsid;
- (void)renewMescalSessionWithCompletionHandler:(void (^)(BOOL))arg1;
- (void)resetMescalSession;
- (CKDMescalSession *)mescalSession;
- (void)fetchDeviceIDWithCompletionHandler:(void (^)(NSString *, NSError *))arg1;
- (void)fetchContainerScopedUserIDWithCompletionHandler:(void (^)(NSString *, NSError *))arg1;
- (void)fetchPublicURLForServerType:(long long)arg1 completionHandler:(void (^)(NSURL *, NSError *))arg2;
- (void)fetchConfigurationWithCompletionHandler:(void (^)(CKDServerConfiguration *, NSError *))arg1;
- (CKDServerConfiguration *)config;
- (NSURL *)baseURLForServerType:(long long)arg1 partitionType:(long long)arg2;

@optional
- (void)noteTimeSpentInNetworking:(double)arg1;
- (void)noteFailedProtocolRequest;
- (void)noteFailedNetworkRequest;
- (void)noteSuccessfulRequestWithNumDownloadedElements:(long long)arg1;
- (NSDictionary *)additionalHeaderValues;
@end

