//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSButton, NSString, NSTextField;

@interface _UIContentUnavailableView : NSView
{
    NSString *_buttonTitle;
    NSView *_container;
    NSTextField *_titleView;
    NSTextField *_messageView;
    CDUnknownBlockType _buttonAction;
    NSButton *_button;
}

@property(retain) NSButton *button; // @synthesize button=_button;
@property(retain) NSTextField *messageView; // @synthesize messageView=_messageView;
@property(retain) NSTextField *titleView; // @synthesize titleView=_titleView;
@property(retain) NSView *container; // @synthesize container=_container;
@property(copy, nonatomic) CDUnknownBlockType buttonAction; // @synthesize buttonAction=_buttonAction;
@property(copy, nonatomic) NSString *buttonTitle; // @synthesize buttonTitle=_buttonTitle;
- (void)buttonPressed:(id)arg1;
@property(copy, nonatomic) NSString *message; // @dynamic message;
@property(copy, nonatomic) NSString *title; // @dynamic title;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 title:(id)arg2 style:(unsigned long long)arg3 includeBackdrop:(BOOL)arg4;
- (id)initWithFrame:(struct CGRect)arg1 title:(id)arg2 style:(unsigned long long)arg3;
- (id)_commonInitWithFrame:(struct CGRect)arg1 title:(id)arg2 style:(unsigned long long)arg3 includeBackdrop:(BOOL)arg4;

@end

