//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GKTurnBasedEventHandlerDelegate.h"

@class GKLocalPlayer, NSArray, NSMutableArray, NSMutableDictionary, NSObjectController;

@interface MBCController : NSObject <GKTurnBasedEventHandlerDelegate>
{
    NSObjectController *fCurrentDocument;
    NSMutableArray *fMatchesToLoad;
    NSArray *fExistingMatches;
    NSMutableDictionary *fAchievements;
    BOOL logMouse;
    BOOL dumpLanguageModels;
    GKLocalPlayer *localPlayer;
}

@property(nonatomic) GKLocalPlayer *localPlayer; // @synthesize localPlayer;
- (void)handleMatchEnded:(id)arg1;
- (void)handleTurnEventForMatch:(id)arg1;
- (void)handleInviteFromGameCenter:(id)arg1;
- (void)updateApplicationBadge;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)loadAchievements;
- (void)setValue:(float)arg1 forAchievement:(id)arg2;
- (void)loadMatches;
- (void)loadMatch:(id)arg1;
- (void)startNewOnlineGame:(id)arg1 withDocument:(id)arg2;
- (id)documentForMatch:(id)arg1;
- (BOOL)applicationShouldOpenUntitledFile:(id)arg1;
@property(nonatomic) BOOL dumpLanguageModels; // @synthesize dumpLanguageModels;
@property(nonatomic) BOOL logMouse; // @synthesize logMouse;
- (BOOL)hideDebugMenu;
- (void)newGame:(id)arg1;
- (void)awakeFromNib;
- (id)init;
- (void)copyOpeningBooks:(int)arg1;
- (void)copyOpeningBook:(id)arg1;

@end

