//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CNContactPickerDelegate.h"

@class CNContactPicker, NSString;

@protocol CNPrivateContactPickerDelegate <CNContactPickerDelegate>

@optional
- (void)contactPicker:(CNContactPicker *)arg1 didShowSectionWithIdentifier:(NSString *)arg2;
- (void)contactPicker:(CNContactPicker *)arg1 didSearchForString:(NSString *)arg2;
@end

