//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface EKEventChangeSummarizer : NSObject
{
}

+ (id)diffSummaryBetweenEvent:(id)arg1 andEvent:(id)arg2;
+ (id)changeSummaryForEvent:(id)arg1;
+ (id)multiValueDiffKeys;
+ (id)singleValueDiffKeys;

@end

