//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface MZBookKeeperErrorHandler : NSObject
{
    NSMutableDictionary *_handles;
}

@property(retain, nonatomic) NSMutableDictionary *handles; // @synthesize handles=_handles;
- (void).cxx_destruct;
- (id)storeAccountMismatchHandle;
- (id)storeAccountNeedSignInHandle;
- (id)noStoreAccountHandle;
- (id)handleKeyForErrorDomain:(id)arg1 code:(long long)arg2;
- (void)handleError:(id)arg1 withController:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (BOOL)canHandleError:(id)arg1;
- (id)allHandles;
- (void)setHandle:(id)arg1 forErrorDomain:(id)arg2 code:(long long)arg3;
- (id)handleForErrorDomain:(id)arg1 code:(long long)arg2;
- (id)initWithGenericHandles;

@end

